### ISSUE TITLE
TraceCanary的插桩流程，能否提供其它编译环境的实现？

### ISSUE THREAD

**Issue by patrickKXMD** [Tencent/matrix#100]
Hi，现在Trace Canary的ASM字节码操作，是在gradle-plugin的Transform里实现的
有没有计划把这个部分变得更加通用

比如放在Annotation Processor里，通过编辑AST tree来实现？

这样也可以把插桩这一步提前到生成class之前。

**Comment by changelcai** [comment]
如果提前到生成class之前，会导致一些简单的函数本来可以在proguard的时候被优化内联，但因为这种插桩会导致没法优化，最终会应用的方法数得不到减少。

**Comment by patrickKXMD** [comment]
非常感谢，明白了

**Comment by conncui** [comment]
@changelcai 
我理解目前的插桩时机还有另一个好处：对依赖的jar 或者aar 也可以插桩，如果放在生成class之前会增加实现成本。因为现在很多Top应用都采用组件化，并且依赖各种第三方sdk。

BTW，反编译微信apk，发现方法中并没有插桩Method,i 和 Method,o,请问是只在Debug版本中插入么？即应用TraceCanary的时机是？
