### ISSUE TITLE
stack 如何分析

### ISSUE THREAD

**Issue by laobie** [Tencent/matrix#104]
![image](https://user-images.githubusercontent.com/7184320/51899746-9f1a4b80-23ee-11e9-99c0-caadaa809b80.png)
wiki 中写到的上传，请问上传到哪里？
此处的文档还是针对开源作一下调整吧，不然很难使用

**Comment by txfelixzhou** [comment]
有空我写一下本地Method_mapping.txt的解析脚本

**Comment by hfutgl** [comment]
tracecannry的结果输出是啥 wiki也没写

**Comment by wcglws** [comment]
> 有空我写一下本地Method_mapping.txt的解析脚本

demo跑出来的normal慢方法数据如下：

`{
    "cost": 2851,
    "cpu_app": 0.0022340297202052954,
    "detail": "NORMAL",
    "machine": "HIGH",
    "mem": 4041293824,
    "mem_free": 112852,
    "process": "sample.tencent.matrix",
    "stack": "0,97,1,2859
1,99,30,2859
",
    "stackKey": "99
",
    "subType": -1,
    "tag": "Trace_EvilMethod",
    "time": 1551256911070
}`
stack中的0,28591,2859 在Debug.methodmap文件中并没有，是根据Debug.methodmap文件解析堆栈么？请大神不吝赐教哇

**Comment by brunoduan** [comment]
sample里面的Debug.methodmap是插桩函数表，每一行的格式是：方法id，方法accessType，类名，方法名，方法描述；stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。
得到有意思的原始堆栈的话，可以利用插桩函数表，通过方法id找到方法信息。

**Comment by wcglws** [comment]
> sample里面的Debug.methodmap是插桩函数表，每一行的格式是：方法id，方法accessType，类名，方法名，方法描述；stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。
> 得到有意义的原始堆栈的话，可以利用插桩函数表，通过方法id找到方法信息。

stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。这里面的方法执行总耗时 和 cost的关系是？数据有点偏差

**Comment by txfelixzhou** [comment]
解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.

![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)

原理很简单:
1) 文件存在这个目录下
2) 文件内容(选一行)
-1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
 分析: a) 逗号分隔  String[] contents = tempString.split(",");
          b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));

解析过程:
![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)

** 注意 ** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动 
``` shell 
adp push Debug.methodmap storage/emulated/0 
``` 
当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.

**Comment by txfelixzhou** [comment]
@hfutgl 
> tracecannry的结果输出是啥 wiki也没写
请见[Matrix 输出内容的含义解析](
https://github.com/Tencent/matrix/wiki/Matrix--%E8%BE%93%E5%87%BA%E5%86%85%E5%AE%B9%E7%9A%84%E5%90%AB%E4%B9%89%E8%A7%A3%E6%9E%90)

**Comment by wcglws** [comment]
> 解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
> 请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.
> 
> ![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)
> 
> 原理很简单:
> 
> 1. 文件存在这个目录下
> 2. 文件内容(选一行)
>    -1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
>    分析: a) 逗号分隔  String[] contents = tempString.split(",");
>    b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));
> 
> 解析过程:
> ![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)
> 
> **注意** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动
> 
> ```shell
> adp push Debug.methodmap storage/emulated/0 
> ```
> 
> 当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.

非常感谢。。。解析的工具类我已经写好了，哈哈，顺便再请教下大神   stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。这里面的方法执行总耗时 和 cost的关系是？数据有点偏差呢？，为啥会有偏差啊

**Comment by txfelixzhou** [comment]
> > 解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
> > 请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.
> > ![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)
> > 原理很简单:
> > 
> > 1. 文件存在这个目录下
> > 2. 文件内容(选一行)
> >    -1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
> >    分析: a) 逗号分隔  String[] contents = tempString.split(",");
> >    b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));
> > 
> > 解析过程:
> > ![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)
> > **注意** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动
> > ```shell
> > adp push Debug.methodmap storage/emulated/0 
> > ```
> > 
> > 
> > 当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.
> 
> 非常感谢。。。解析的工具类我已经写好了，哈哈，顺便再请教下大神 stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。这里面的方法执行总耗时 和 cost的关系是？数据有点偏差呢？，为啥会有偏差啊

**Comment by txfelixzhou** [comment]
> > 解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
> > 请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.
> > ![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)
> > 原理很简单:
> > 
> > 1. 文件存在这个目录下
> > 2. 文件内容(选一行)
> >    -1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
> >    分析: a) 逗号分隔  String[] contents = tempString.split(",");
> >    b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));
> > 
> > 解析过程:
> > ![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)
> > **注意** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动
> > ```shell
> > adp push Debug.methodmap storage/emulated/0 
> > ```
> > 
> > 
> > 当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.
> 
> 非常感谢。。。解析的工具类我已经写好了，哈哈，顺便再请教下大神 stack每行的格式：stack层级，方法id，方法执行次数，方法执行总耗时。这里面的方法执行总耗时 和 cost的关系是？数据有点偏差呢？，为啥会有偏差啊

哈哈 解析的工具类方便也可以共享一下
有偏差是两者计算方式不同造成的,cost更准确一些, 方法执行耗时的计算采用一个粒度为5ms的计时器,in和out去读计时器时间,所以最大可能会造成-10到10ms的误差

**Comment by keyescgm** [comment]
> 解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
> 请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.
> 
> ![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)
> 
> 原理很简单:
> 
> 1. 文件存在这个目录下
> 2. 文件内容(选一行)
>    -1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
>    分析: a) 逗号分隔  String[] contents = tempString.split(",");
>    b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));
> 
> 解析过程:
> ![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)
> 
> **注意** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动
> 
> ```shell
> adp push Debug.methodmap storage/emulated/0 
> ```
> 
> 当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.

没考虑几十万行文件怎么办吗？

**Comment by hfutgl** [comment]
谁有完整的pc上解析工具提供下

**Comment by shuguangzhang1** [comment]
但是回退到之前的版本没有这行代码，不回退有报错

**Comment by qhy2013** [comment]
@hfutgl  https://github.com/qhy2013/matrix_evil_method_stack_parser

**Comment by haoxunwang** [comment]
Gradle copy task 拷贝编译生成 methodMapping 文件到 sdcard 下
```groovy
task copyFileForMethodMapping {
    group = ""
    description = 'Copies methodMapping.txt file from project to device...'
    doFirst {
        println 'Getting file for copy'
        def sourceFile = new File(project.buildDir.absolutePath + '/outputs/mapping/debug/methodMapping.txt')
        exec {
            println "sourceFile: " + sourceFile.absolutePath
            commandLine android.getAdbExecutable(), 'push', "${sourceFile.absolutePath}", '/storage/emulated/0'
        }
    }
}
```

**Comment by Mrnoknow** [comment]
线上返回的慢方法数据是先解析上传还是上传后进行解析，若是上传后解析，如何保证解析的准确性？

**Comment by JayRichrd** [comment]
> 解析逻辑很简单,写好很久,其它事耽搁就忘了上传.
> 请查看 hotfix/0.4.x sample-android项目中的IssuesListActivity文件.
> 
> ![image](https://user-images.githubusercontent.com/15136816/53804310-26c12000-3f82-11e9-8996-0daf9f1f7fde.png)
> 
> 原理很简单:
> 
> 1. 文件存在这个目录下
> 2. 文件内容(选一行)
>    -1,1,sample.tencent.matrix.resource.TestLeakActivity onWindowFocusChanged (Z)V
>    分析: a) 逗号分隔  String[] contents = tempString.split(",");
>    b) 构造hashmap.  methoMap.put(Integer.parseInt(contents[0]), contents[2].replace('\n', ' '));
> 
> 解析过程:
> ![image](https://user-images.githubusercontent.com/15136816/53804329-3476a580-3f82-11e9-8857-218042bc0c6e.png)
> 
> **注意** 因为编译和运行处于不同的文件环境, 所以为了正常访问, 还需要手动
> 
> ```
> adp push Debug.methodmap storage/emulated/0 
> ```
> 
> 当然是因为我偷懒了, 你也可以创建一个gradle任务,将文件拷入手机存储卡中.

这个也只能针对本地编译debug包并马上安装到真机

**Comment by thirtyyuan** [comment]
请问下 `${project.projectDir}/matrixTrace/methodMapping.txt` 这个文件是会在这里指定的目录也有吗？我目前发现没有，只有 `app/build/outputs/mapping/debug/methodMapping.txt` 这里有。

**Comment by bad-mask** [comment]
> Gradle copy task 拷贝编译生成 methodMapping.txt 文件到 sdcard 下
> 
> ```groovy
> task copyFileForMethodMapping {
>     group = ""
>     description = 'Copies methodMapping.txt file from project to device...'
>     doFirst {
>         println 'Getting file for copy'
>         def sourceFile = new File(project.buildDir.absolutePath + '/outputs/mapping/debug/methodMapping.txt')
>         exec {
>             println "sourceFile: " + sourceFile.absolutePath
>             commandLine android.getAdbExecutable(), 'push', "${sourceFile.absolutePath}", '/storage/emulated/0'
>         }
>     }
> }
> ```
> 
> OR
> 
> 在 assemble task 完成后自动执行 adb push 文件
> 
> ```groovy
> project.afterEvaluate {
>     tasks.getByName("assembleDebug") {
>         it.doLast {
>             println 'Copies methodMapping.txt file from project to device...'
>             def sourceFile = new File(project.buildDir.absolutePath + '/outputs/mapping/debug/methodMapping.txt')
>             assert file(sourceFile.absolutePath).exists()
>             exec {
>                 println "sourceFile: " + sourceFile.absolutePath
>                 commandLine android.getAdbExecutable(), 'push', "${sourceFile.absolutePath}", '/storage/emulated/0'
>             }
>         }
>     }
> }
> ```

所以一个线上App，只有一份对应的 methodMapping 文件 ，对么
