### ISSUE TITLE
IOCanary type 4适应所有线程，type 2、3（小buffer、重复打开小文件）这两类为何只检测主线程的，有何考虑么？

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#107]
这个函数每秒调用一次，byte数组是16字节，然后在listener中一直没有提示该类问题

把finally中代码删除，再次测试listener中会提示type 4，泄露类问题

    public void testFileInputStream3() { // abcdefgcde
        FileInputStream fis = null;
        try {
            File file = new File("hello.txt");
            fis = new FileInputStream(file);

            byte[] b = new byte[16];// 读取到的数据要写入的数组。

            int len;// 每次读入到byte中的字节的长度
            while ((len = fis.read(b)) != -1) {
                String str = new String(b, 0, len);
                System.out.print(str);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (fis != null) {
                try {
                    fis.close();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

            }

        }
    }

**Comment by hfutgl** [comment]
小buffer读写 这类问题的检测也限制在主线程中？

**Comment by lolobug** [comment]
这里是一个改进点。见#69
