### ISSUE TITLE
发布到本地maven 没有 配置文件,无法被其他项目依赖

### ISSUE THREAD

**Issue by conncui** [Tencent/matrix#111]
执行 buildAndPublishToLocalMaven 任务，在matrix/build/outputs/artifacts/下只有jar 和aar 文件，没有
maven-metadata.xml
maven-metadata.xml.md5
maven-metadata.xml.sha1 等配置文件，

如果修改源码后，其他项目无法通过依赖本地maven的方式依赖aar。

**Comment by txfelixzhou** [comment]
如sample中一样,在build.gradle中配置MavenLocal(), 会自动从本地寻找.
![image](https://user-images.githubusercontent.com/15136816/52768918-cf5a1f00-3069-11e9-88ec-2820b1f26241.png)

**Comment by conncui** [comment]
多谢。习惯了 用 自定义路径
`./gradlew -P repositoryUrl=file:///media/cui/s/work/localMaven uploadArchives`
