### ISSUE TITLE
TraceCanary 分配内存疑问

### ISSUE THREAD

**Issue by JackyAndroid** [Tencent/matrix#116]
已看完其他相关issues。

wiki中指出：“当前执行的是 MethodBeat i或者o、mehtod id 及时间 offset，存放到一个 long 类型变量中，记录到一个预先初始化好的数组 long[] 中 index 的位置（预先分配记录数据的 buffer 长度为 100w，内存占用约 7.6M）”。

疑问：
1. 请问buffer长度定为100w，是有什么根据吗？
2. 如果对buffer进行裁剪会出现什么问题？

**Comment by JackyAndroid** [comment]
@hzlzh @jasonross @lingol @lolobug 请问有人解答下吗？

**Comment by changelcai** [comment]
1，拍脑袋一个值，7.6M内存觉得是可接受的。但测试for循化调用一个空方法，5秒内没法占满整个buffer。

**Comment by JackyAndroid** [comment]
7.6M对一些业务量较小的应用还是蛮大的。
建议之后能给出一个能覆盖更多应用的实践值、范围，或者做成可配置项。
