### ISSUE TITLE
sample 编译不过

### ISSUE THREAD

**Issue by carl1990** [Tencent/matrix#117]
在编译过程中 资源下载不了
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.jar]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm/5.1/asm-5.1.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm/5.1/asm-5.1.jar]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-analysis/5.1/asm-analysis-5.1.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-analysis/5.1/asm-analysis-5.1.jar]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.jar]
 
所有的库都被指向了 dl.google.com ，导致下载不下来，需要配置其他maven仓库么

**Comment by txfelixzhou** [comment]
设置下代理吧

**Comment by carl1990** [comment]
已经解决了 是我本地host设置的Ip失效导致的
