### ISSUE TITLE
Matrix-ApkChecker 是否支持分析aar

### ISSUE THREAD

**Issue by Larnoo** [Tencent/matrix#12]
Matrix-ApkChecker 是否支持分析aar

问题描述：Matrix-ApkChecker 是否支持分析aar

**Comment by jqctop1** [comment]
直接分析的是apk文件

**Comment by jqctop1** [comment]
@Larnoo 你希望分析aar的什么呢？

**Comment by hfutgl** [comment]
@jqctop1  ApkChecker的接口能否在java中直接调用，现在的说明文档都是java -jar xxx.jar形式，我们现在有需求在python或java代码中直接调用

**Comment by jqctop1** [comment]
@hfutgl 当然可以啊，看下apkchecker的入口类就知道怎么调用量

**Comment by hfutgl** [comment]
@jqctop1 已解决

**Comment by Larnoo** [comment]
> @Larnoo 你希望分析aar的什么呢？

@jqctop1 想分析aar中的资源大小，以及那些资源没有被用到。
