### ISSUE TITLE
APK Checker 运行异常，提示无法删除 classes2.dex

### ISSUE THREAD

**Issue by fenghebaiyang** [Tencent/matrix#13]
异常类型：APK Checker 运行异常

运行平台：win10 cmd  java version 1.8.0_121

问题描述：APK Checker 运行时报错

堆栈/日志：
[INFO][Matrix.ApkJob]format list [mm.html, mm.json]
[DEBUG][Matrix.UnZipTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2.2.1-11-1221094719.apk
[DEBUG][Matrix.UnZipTask]outputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.UnZipTask]D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip exists, delete it.
[DEBUG][Matrix.ManifestAnalyzeTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.ShowFileSizeTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.MethodCountTask]input path:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.ResProguardCheckTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.MultiLibCheckTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[INFO][Matrix.MultiSTLCheckTask]toolnm pah is D:\Android\sdk\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-nm.exe
[DEBUG][Matrix.MultiSTLCheckTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[DEBUG][Matrix.UnusedAssetsTask]ignore assets 1
[INFO][Matrix.UnStrippedSoCheckTask]toolnm pah is D:\Android\sdk\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-nm.exe
[DEBUG][Matrix.UnStrippedSoCheckTask]inputPath:D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip
[INFO][Matrix.ResProguardCheckTask]directory anim has a non-proguard name!
[DEBUG][Matrix.MultiSTLCheckTask]lib: libijkplayer.so has stl link
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.ActionBar
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.ActionBar_background
。
。（Matrix.UnusedResourcesTask  ignore resource）
。
[DEBUG][Matrix.UnusedResourcesTask]find resource declarations 4302 items.
[DEBUG][Matrix.UnusedResourcesTask]find resource references in classes: 3143 items.
[DEBUG][Matrix.UnusedResourcesTask]find resource references 4194 items.
[DEBUG][Matrix.UnusedResourcesTask]find unused references 363 items
[DEBUG][Matrix.UnusedAssetsTask]find all assets count: 1
[DEBUG][Matrix.UnusedAssetsTask]find reference assets count: 1
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libijkffmpeg.so is not stripped
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libijkplayer.so is not stripped
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libijksdl.so is not stripped
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: libjcore121.so is not stripped
[DEBUG][Matrix.UnStrippedSoCheckTask]lib: librtmp-jni.so is not stripped
[DEBUG][Matrix.ApkJob]parse apk end, try to delete tmp un zip files
[ERROR][Matrix.ApkJob]Task executor execute with error:Unable to delete file: D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip\classes2.dex
java.io.IOException: Unable to delete file: D:\mvmplayerBak\122109\app-1221094719\app-website-2_unzip\classes2.dex
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
        at com.tencent.matrix.apk.model.job.ApkJob.execute(ApkJob.java:513)
        at com.tencent.matrix.apk.model.job.ApkJob.run(ApkJob.java:469)
        at com.tencent.matrix.apk.ApkChecker.run(ApkChecker.java:90)
        at com.tencent.matrix.apk.ApkChecker.main(ApkChecker.java:80)

**Comment by jqctop1** [comment]
@fenghebaiyang OK，我重现了这个问题，马上修复下，thx

**Comment by jqctop1** [comment]
@fenghebaiyang 在win平台下解压apk会遇到一些0KB的文件，导致最后删除unzip目录失败。不过其实分析结果已经输出了。

**Comment by jqctop1** [comment]
@fenghebaiyang 文件句柄泄露了，不过其实分析的结果这时候已经完整输出了。已经在fix，感谢反馈。

**Comment by txfelixzhou** [comment]
已修复，请在 master 分支中 README.md 中下载最新 jar包（0.4.10）使用
