### ISSUE TITLE
Matrix 上报到哪里呢？有没有网站可以查看到，要是有一个像bugly这种网站就好了

### ISSUE THREAD

**Issue by tianshaokai** [Tencent/matrix#138]
1 如题

**Comment by txfelixzhou** [comment]
在sample中已经会导出文字版本的内容到界面上，当前matrix只作为探针项目提供，对外，还没管理后台提供

**Comment by Valuebai** [comment]
> 在sample中已经会导出文字版本的内容到界面上，当前matrix只作为探针项目提供，对外，还没管理后台提供
---
希望能开发管理后台日志管理的
