### ISSUE TITLE
关于ResourceCanary的检测阶段和分析阶段

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#144]
检测阶段只检测Activity泄露，Activity泄露之后才会有hprof文件；如果没有发生Activity泄露，拿不到hprof文件，检测阶段怎么分析bitmap？

bitmap问题的分析必须依赖activity泄露才能分析？

**Comment by tomystang** [comment]
是的，bitmap问题的分析目前必须依赖activity泄漏检测得到的产物。不过在这里Activity泄漏只是一个触发点，如果要独立检测bitmap重复的话可以考虑以一段时间内内存占用超过某个阈值来触发hprof dump，然后把dump出来的产物传给resource-canary的cli工具就可以了。
