### ISSUE TITLE
FPS如何分析

### ISSUE THREAD

**Issue by keyescgm** [Tencent/matrix#147]
tag[Trace_FPS]type[null];key[null];content[{"machine":"HIGH","cpu_app":0.002791045673872224,"mem":3926458368,"mem_free":161364,"scene":"sample.tencent.matrix.issue.IssuesListActivity","dropLevel":{"DROPPED_FROZEN":0,"DROPPED_HIGH":0,"DROPPED_MIDDLE":0,"DROPPED_NORMAL":0,"DROPPED_BEST":61},"dropSum":{"DROPPED_FROZEN":0,"DROPPED_HIGH":0,"DROPPED_MIDDLE":0,"DROPPED_NORMAL":0,"DROPPED_BEST":0},"fps":60,"tag":"Trace_FPS","process":"sample.tencent.matrix","time":1553675665018}]

如这个数据，我怎么知道哪里有问题？列表哪里掉帧了，什么原因导致掉帧？都不知道

**Comment by txfelixzhou** [comment]
#掉帧的Activity#
"scene":"sample.tencent.matrix.issue.IssuesListActivity"

#掉帧程度#
dropLevel：DROPPED_BEST":61 
查看wiki中的trace技术类文档，
![image](https://user-images.githubusercontent.com/15136816/55205414-c1252400-520d-11e9-8ba0-f8f075aa3a74.png)
说明此activity的掉帧程度很低 
![image](https://user-images.githubusercontent.com/15136816/55205625-96879b00-520e-11e9-9e8b-f9ca0d06b2d0.png)

详细内容请参考Wiki：[Matrix-TraceCanary](https://github.com/Tencent/matrix/wiki/Matrix-TraceCanary)

**Comment by wcglws** [comment]
{
    "cpu_app": 0,
    "dropLevel": {
        "DROPPED_BEST": 13,
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 1,
        "DROPPED_NORMAL": 4
    },
    "dropSum": {
        "DROPPED_BEST": 8,
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 11,
        "DROPPED_NORMAL": 24
    },
    "fps": 17.70538330078125,
    "machine": "BEST",
    "mem": 5850492928,
    "mem_free": 897292,
    "process": "sample.tencent.matrix",
    "scene": "sample.tencent.matrix.trace.TestFpsActivity",
    "tag": "Trace_FPS",
    "time": 1554623339945
}

![](https://user-images.githubusercontent.com/16982083/55680658-11f3f580-594f-11e9-99e3-487bfd64f0a7.png)

大神能不能根据数据详细的解释下图中的横纵坐标的含义，这图是怎么画出来的，万分感谢，数据分析的很吃力啊

**Comment by hfutgl** [comment]
这个看着确实有点绕，掉帧数在3以内的是DROPPED_BEST，但是又说DROPPED_BEST有13帧 理解不了这个level咋划分的

**Comment by shaobin0604** [comment]
> 这个看着确实有点绕，掉帧数在3以内的是DROPPED_BEST，但是又说DROPPED_BEST有13帧 理解不了这个level咋划分的

在一个采样周期内
```
{
"cpu_app": 0,
"dropLevel": {
"DROPPED_BEST": 13, // 掉 3 帧以内的情况（包含未丢帧）出现了 13 次
"DROPPED_FROZEN": 0,
"DROPPED_HIGH": 0,
"DROPPED_MIDDLE": 1,
"DROPPED_NORMAL": 4
},
"dropSum": {
"DROPPED_BEST": 8, // 掉 3 帧以内的情况累计丢了 8 帧
"DROPPED_FROZEN": 0,
"DROPPED_HIGH": 0,
"DROPPED_MIDDLE": 11,
"DROPPED_NORMAL": 24
},
```

**Comment by luckyjmcc** [comment]
蒙圈了，我这个算好坏？
{
    "machine": "HIGH",
    "cpu_app": 0.482000901449198,
    "mem": 7670714368,
    "mem_free": 2726916,
    "scene": "xxxxxxxxxxxx",
    "dropLevel": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 746
    },
    "dropSum": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 4
    },
    "fps": 60,
    "tag": "Trace_FPS",
    "process": "com.huawei.mycenter",
    "time": 1628847710394
}

**Comment by luckyjmcc** [comment]
蒙圈了，我这个算好坏？
`{
    "machine": "HIGH",
    "cpu_app": 0.482000901449198,
    "mem": 7670714368,
    "mem_free": 2726916,
    "scene": "xxxxxxxxxxxx",
    "dropLevel": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 746
    },
    "dropSum": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 4
    },
    "fps": 60,
    "tag": "Trace_FPS",
    "process": "xxxxxxx",
    "time": 1628847710394
}`

**Comment by luckyjmcc** [comment]
蒙圈了，我这个算好坏？
{
    "machine": "HIGH",
    "cpu_app": 0.482000901449198,
    "mem": 7670714368,
    "mem_free": 2726916,
    "scene": "xxxxxxxxxxxx",
    "dropLevel": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 746
    },
    "dropSum": {
        "DROPPED_FROZEN": 0,
        "DROPPED_HIGH": 0,
        "DROPPED_MIDDLE": 0,
        "DROPPED_NORMAL": 0,
        "DROPPED_BEST": 4
    },
    "fps": 60,
    "tag": "Trace_FPS",
    "process": "xxxxxxx",
    "time": 1628847710394
}
