### ISSUE TITLE
EvilMethod如何分析

### ISSUE THREAD

**Issue by keyescgm** [Tencent/matrix#148]
tag[Trace_EvilMethod]type[null];key[null];content[{"machine":"HIGH","cpu_app":0.006043499792587521,"mem":3926458368,"mem_free":142408,"detail":"NORMAL","subType":-1,"cost":1616,"stack":"0,99,1,1611\n1,101,30,1611\n","stackKey":"101\n","tag":"Trace_EvilMethod","process":"sample.tencent.matrix","time":1553675841442}]

如何分析？我如何知道我哪个方法慢了？stack 里面都是啥？

**Comment by txfelixzhou** [comment]
cost 是整个堆栈执行的总时间 如1616ms 
那每个方法的执行时间是多少，谁最耗时，请看 #104 (反解出statck字段)
