### ISSUE TITLE
ApkChecker 输出日志中有一行 Error 日志

### ISSUE THREAD

**Issue by realxz** [Tencent/matrix#149]
apk-checker-result 分析结果已经正常生成，但我发现在打印的日志中有一行 Error 日志，

`[ERROR][Matrix.ApkResourceDecoder]Parse xml error,Expected: 0x00080003, got: 0x6d783f3c`

想请教一下，这是由于什么原因导致的

**Comment by jqctop1** [comment]
![image](https://user-images.githubusercontent.com/15994990/55373209-05c6fd00-5537-11e9-9bf9-2dc40b798e39.png)

看起来应该是某个二进制xml文件的格式有点问题，0x00080003是二进制xml文件的magic number

**Comment by realxz** [comment]
> ![image](https://user-images.githubusercontent.com/15994990/55373209-05c6fd00-5537-11e9-9bf9-2dc40b798e39.png)
> 
> 看起来应该是某个二进制xml文件的格式有点问题，0x00080003是二进制xml文件的magic number

所以有可能是我这边代码中某个 XML文件格式不规范导致的？看上去也不会影响到 Apk-Checker 的正常使用

**Comment by PeterXiaosa** [comment]
同样出现的类似的结果，我这提示的是Could not decode XML。如果是说某个XML格式不规范的问题，那通过日志也看不出来是哪个文件不规范呀。那还是没有办法正常使用app checker = =
