### ISSUE TITLE
ApkChecker有计划支持插件化吗？

### ISSUE THREAD

**Issue by wangrunxiang** [Tencent/matrix#15]
插件化支持有计划吗？

**Comment by wangrunxiang** [comment]
我说错了，是想问appchecker有没有计划支持插件化 @txfelixzhou

**Comment by astrozhou** [comment]
你说的插件化指的是什么？没有理解到

**Comment by wangrunxiang** [comment]
@astrozhou @txfelixzhou 比如说，我们有一些内置插件打包的时候是以其他后缀比如so的形式打到asset目录下的，apkchecker只会检测外层的壳，其实大部分的代码和资源都是以内置插件的形式打在apk里面，apkchecker就检测不到这些

**Comment by astrozhou** [comment]
close for no updates
