### ISSUE TITLE
ApkCheck.unusedResource 不支持res/raw/keep.xml

### ISSUE THREAD

**Issue by jiasonwang** [Tencent/matrix#150]
官方文档中对于资源是可以keep的：https://developer.android.com/studio/build/shrink
希望对res/raw/keep.xml进行支持

**Comment by jqctop1** [comment]
@jiasonwang 

1. ApkChecker unusedResources 支持通过参数ignoreResources来设置白名单

2. ApkChecker unusedResources 只是检测unusedResources，也可以在删除unusedResources阶段才添加白名单，可以参看matrix-gradle-plugin中的MatrixDelUnusedResConfiguration。这里在sample工程里漏掉了相关配置，我后续补上
