### ISSUE TITLE
监控主线程状态为什么需要用两个runloop observer呢?

### ISSUE THREAD

**Issue by Yincongxiao** [Tencent/matrix#167]
![image](https://user-images.githubusercontent.com/13636537/55548026-2e045680-5705-11e9-83d9-6ac0b365f000.png)
弱弱的问下,在`WCBlockMonitorMgr.m`中监控主线程状态,为什么需要两个observer呢?为什么不在一个observer回调中既处理`kCFRunLoopEntry`...又处理`BeforeWaiting`和`exit`呢

**Comment by txfelixzhou** [comment]
@chzhij5

**Comment by SuperSG** [comment]
这两个observer的优先级不一样吧，一个最高，一个最低 这样是不是能更好的处理g_bRun这个标志位

**Comment by Peterbald** [comment]
注册两个不同 order 的 Observer，保证在所有回调之前 beginCallback，在所有回调之后 endCallback，类似于 AutoreleasePool 的处理方式

**Comment by chzhij5** [comment]
> 注册两个不同 order 的 Observer，保证在所有回调之前 beginCallback，在所有回调之后 endCallback，类似于 AutoreleasePool 的处理方式

对，两个observer是希望在开始的最开始获得回调，也希望在结束的最晚时间点获得回调

**Comment by Yincongxiao** [comment]
嗯,开始没有注意到优先级不同

**Comment by 13538899384** [comment]
这样做的意义是啥？还是看不太明白。

**Comment by chzhij5** [comment]
> 这样做的意义是啥？还是看不太明白。

这样runloop开始的时候会有事件通知；runloop休眠前也会有事件通知。这样才能知道runloop的工作状态。

**Comment by alwaysblue3** [comment]
> 
但是autoreleasepool的监听应该只监听某个状态，但是此处的监听是kCFRunLoopAllActivities所有状态，还有创建多个observe的必要吗

**Comment by ZeroOnet** [comment]
我的理解是：为了让统计的卡顿时间更加精确，通知 observer 也是有先后顺序的，并且 observer 的执行也是要耗时的。
