### ISSUE TITLE
iOS needFilter 这个方法中的stackFeat的计算有问题

### ISSUE THREAD

**Issue by SuperSG** [Tencent/matrix#173]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：app 运行时异常/编译异常

手机型号：如: Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

matrix版本：如: 0.4.7

gradle版本：如: 3.0.0

问题描述：如：在 android O 出现系统不兼容 

堆栈/日志：
1. 如是编译异常，请在执行 gradle 命令时，加上 --stacktrace;
2. 日志我们需要过滤" Matrix. "关键字;
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种 issue 也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Matrix 是一个开源项目，希望大家遇到问题时要学会先思考，看看 Sample 与 Matrix 的源码，更鼓励大家给我们提 pr .

这个地方stackFeat的累加好像没有任何作用，就被覆盖了
![image](https://user-images.githubusercontent.com/7297607/55721306-9c168980-5a35-11e9-9242-56ca0ce060c7.png)

**Comment by chzhij5** [comment]
这里不是累加。

这里取堆栈最顶上的一个堆栈地址作为堆栈特征；堆栈栈顶地址相同，则认为整个堆栈是相同的。
我们认为取全部有点特多了，可能会有性能问题，这里取一个栈顶地址就已经够用了。这里需要算出绝对地址在binary image的地址相对偏移

**Comment by SuperSG** [comment]
> 这里不是累加。
> 
> 这里取堆栈最顶上的一个堆栈地址作为堆栈特征；堆栈栈顶地址相同，则认为整个堆栈是相同的。
> 我们认为取全部有点特多了，可能会有性能问题，这里取一个栈顶地址就已经够用了。这里需要算出绝对地址在binary image的地址相对偏移

但是stackFeat这个偏移量在for循环计算完成之后没有使用 就直接被 stackFeat = kssymbolicate_symboladdress(stack[0]); 覆盖了，虽然说没有副作用，但这里的计算是不是就没有意义了？

**Comment by chzhij5** [comment]
结合上面那段代码下方的代码： NSUInteger repeatCnt = [m_stackHandler addStackFeat:stackFeat];

以及 WCBlockMonitorConfiguration 的 bFilterSameStack 和 triggerToBeFilteredCount 这两个字段一起看

**Comment by hejunm** [comment]
与SuperSG 同样的疑惑。
@chzhij5  你说的对，但是你没有解答SuperSG的问题吧。
stackFeat += stack[i] 没有起作用。

**Comment by chzhij5** [comment]
> 与SuperSG 同样的疑惑。
> @chzhij5 你说的对，但是你没有解答SuperSG的问题吧。
> stackFeat += stack[i] 没有起作用。

对，我发现了，这里之前是想用整个堆栈特征来做特征的。后来验证发现，只要用栈顶堆栈就足够了。

stackFeat += stack[i] 多余了。  下个版本这行代码我删掉。

@SuperSG @hejunm
