### ISSUE TITLE
gzippedWithCompressionLevel: error: is not found

### ISSUE THREAD

**Issue by banshengXia** [Tencent/matrix#177]
项目中有使用GZIP（1.2.2)这个库，"NSData+Gzip.h"文件会找到GZIP库中的“NSData+GZIP.h”中导致下面的两个方法报错了
请问该如何解决？
gunzippedWithError: not found
需要替换为 
gunzippedData
-------------------
gzippedWithCompressionLevel: error: not found
 需要替换为
gzippedDataWithCompressionLevel:

**Comment by chzhij5** [comment]
是用什么方式引入的 Matrix 库呢？ 符号冲突的话，可以使用动态库的方式引入。

如果是 Pod 引入的话，使用 use_framework 参数。

说明：
为什么建议使用静态库？
KSCrash 这个库的捕捉 C++ Exception 的方式 ，如果用动态库引入 Matrix，会导致捕捉到的 C++ Exception 抓不到栈回溯前的堆栈。
如果工程没有什么C++代码，建议还是使用动态库引入，减少符号冲突的风险。

具体可以参考：https://github.com/kstenerud/KSCrash/issues/205

**Comment by ben46** [comment]
> 是用什么方式引入的 Matrix 库呢？ 符号冲突的话，可以使用动态库的方式引入。
> 
> 如果是 Pod 引入的话，使用 use_framework 参数。
> 
> 说明：
> 为什么建议使用静态库？
> KSCrash 这个库的捕捉 C++ Exception 的方式 ，如果用动态库引入 Matrix，会导致捕捉到的 C++ Exception 抓不到栈回溯前的堆栈。
> 如果工程没有什么C++代码，建议还是使用动态库引入，减少符号冲突的风险。
> 
> 具体可以参考：[kstenerud/KSCrash#205](https://github.com/kstenerud/KSCrash/issues/205)

使用的是swift4.2, pod引入方式, 使用了use_frameworks!, 依旧报`/Users/xiangzhen002/Documents/workspace/heika/Pods/matrix-wechat/matrix/matrix-apple/Matrix/WCCrashBlockMonitor/KSCrash/Reporting/Filters/KSCrashReportFilterGZip.m:29:9: 'NSData+GZip.h' file not found` 错误

**Comment by ben46** [comment]
我已经找到问题所在, 因为其他库也引入了这个nsdata, 所以造成冲突, 把其他库的nsdata的category删掉即可 @banshengXia

**Comment by chzhij5** [comment]
73013a497c58a5a4d1335331b319b5315a6c8b9f   NSData+GZip重命名，已经合入dev和master。  感谢 @jiangpengyun 的提交。
