### ISSUE TITLE
[Bug]onFront调用时机

### ISSUE THREAD

**Issue by Colibrow** [Tencent/matrix#181]
异常类型：bug

matrix版本： 0.4.10

gradle版本： 3.0.0

问题描述：onFront调用的时机

如果在应用初始化的时候, 调用了

```java
ActivityCompat.requestPermissions(this,
                new String[]{Manifest.permission.READ_LOGS}, 0);
```

那么ApplicationLifeObserver则会经历这么一个生命周期:

onActivityResume -> onActivityPaused -> onActivityResume

由于穿插了一个时间极短的onActivityPaused状态，所以此时的Activity处于前台状态，但是Observer并没有被通知到onFront函数,因为第一个onActivityResume时候的CheckRunnable无法执行，等到第二次判断wasBackground的时候已经变成了true，所以trace时候的前后台判断出错，变为:

```java
[onTimeExpire] pass this time, on Background!
```
所以无法真正的监控到方法的异常，当然也不止是之前那种状态会出现这个问题，只要存在这么一个短暂的状态切换，那么如果前后台发生改变都会通知不到

**Comment by txfelixzhou** [comment]
最新的版本中已fix，请关注最新的dev分支

**Comment by fvdcx** [comment]
@txfelixzhou 请问“dev分支”指的是dev还是feature-dev ?
