### ISSUE TITLE
广研卡顿监控系统跟matrix是一个东西吗

### ISSUE THREAD

**Issue by fvdcx** [Tencent/matrix#184]
http://www.10tiao.com/html/330/201801/2653579565/1.html

请问跟matrix是否是同一个解决方案？文章里很多技术原理是相似的

**Comment by txfelixzhou** [comment]
不是同一解决方案，是内部的不同产品，相互之间确实存在借鉴。
在traceCanary的那一篇介绍中，我们简单罗列了各个产品的对比情况：

Matrix-TraceCanary | TraceView | BlockCanary | BlockCanaryEx | ArgusAPM | ANR-WatchDog | 广研卡顿系统
-- | -- | -- | -- | -- | -- | --
定位精确度 | 高 | 高 | 中 | 高 | 中 | 中 | 中
字节码修改 | 是 | 否 | 否 | 是 | 否 | 否 | 否
资源占用 | 较低 | 较低 | 较低 | 较低 | 较低 | 较低 | 较低
线上采集 | 支持 | 不支持 | 支持 | 支持 | 支持 | 支持 | 支持
性能损耗 | 可忽略 | 非常大 | 可忽略 | 大 | 可忽略 | 可忽略 | 可忽略
界面展示 | 不支持 | 支持 | 支持 | 支持 | 支持 | 支持 | 未知
帧率计算 | 支持 | 不支持 | 不支持 | 不支持 | 支持 | 不支持 | 支持
ANR监控 | 支持 | 不支持 | 不支持 | 不支持 | 支持 | 支持 | 支持
启动耗时 | 支持 | 不支持 | 不支持 | 不支持 | 不支持 | 不支持 | 不支持
