### ISSUE TITLE
jar包如何使用

### ISSUE THREAD

**Issue by SnowMusic** [Tencent/matrix#19]
`java -jar ApkChecker.jar --apk debug.apk -manifest`
我把jar包0.4.7下载下来之后 将他和apk放在同一个文件夹中，输入如上命令,返回`null`。
看终端的doc貌似可以写在一个json文件里，是否可以给出正确的使用方式

**Comment by JichunMa** [comment]
`java  -jar matrix-apk-canary-0.4.7.jar --apk ./debug.apk`

**Comment by SnowMusic** [comment]
> `java -jar matrix-apk-canary-0.4.7.jar --apk ./debug.apk`
> 把jar包0.4.7下载下来之后 将他和apk放在同一个文件夹中，输入如上命令
> [matrix-apk-canary-0.4.7.jar](https://dl.bintray.com/matrix/maven/com/tencent/matrix/matrix-apk-canary/0.4.7/matrix-apk-canary-0.4.7.jar)

跑起来了 谢谢

**Comment by chenhongqing527** [comment]
java -jar matrix-apk-canary-0.4.7.jar --apk ./debug.apk
除了--apk，其他的参数怎么用呢？

**Comment by JichunMa** [comment]
> java -jar matrix-apk-canary-0.4.7.jar --apk ./debug.apk
> 除了--apk，其他的参数怎么用呢？

https://github.com/Tencent/matrix/wiki/Matrix-ApkChecker#matrix-apkchecker-%E7%9A%84%E4%BD%BF%E7%94%A8

**Comment by SnowMusic** [comment]
java -jar xxx.jar --apk ./debug.apk -manifest

chq <notifications@github.com> 于2018年12月26日周三 下午6:56写道：
