### ISSUE TITLE
couldn't find "libso-canary.so" 问题

### ISSUE THREAD

**Issue by orab** [Tencent/matrix#196]
升级到 0.5.1 之后运行时会报错提示 libio-canary.so 找不到。

看代码历史，最近一个[提交](https://github.com/Tencent/matrix/commit/b83c481938b21c0080540d0c2babb04caa5e72c9#diff-820ea5df75ade307aedbc0863b4f8f51)把 matrix-io-canary/build.gradle 中的 abiFilter 的 armeabi 选项删掉了，我觉得应该是这个原因导致的。

**Comment by txfelixzhou** [comment]
是的，内部已经废掉armeabi.
为了方便大家使用，现已加回来，并放到hotfix/0.5.x。后续会合入dev再提供新的aar

**Comment by BeWaterMF** [comment]
同样是这个问题，期待

**Comment by wuguifang** [comment]
貌似还没解决？已经使用.6.0版本
