### ISSUE TITLE
这个库的有做性能测试吗，会产生多大影响，能不能只在debug版本实现

### ISSUE THREAD

**Issue by nickming** [Tencent/matrix#2]
rt

**Comment by astrozhou** [comment]
trace 有性能方面的测试，后续 wiki 中会同步出来

**Comment by weikano** [comment]
楼主的意思是集成在release版中，会不会在性能方面对app有比较大的影响？
或者应该类似leakcanary一样提供一个no-op的依赖？

**Comment by astrozhou** [comment]
> 楼主的意思是集成在release版中，会不会在性能方面对app有比较大的影响？
> 或者应该类似leakcanary一样提供一个no-op的依赖？

目前还没有 benchmark，但 no-op 是个好主意！

**Comment by nickming** [comment]
> > 楼主的意思是集成在release版中，会不会在性能方面对app有比较大的影响？
> > 或者应该类似leakcanary一样提供一个no-op的依赖？
> 
> 目前还没有 benchmark，但 no-op 是个好主意！不过更多的性能问题，在用户侧更容易发现，测试阶段发现性能问题的范围有限，而且性能问题受手机硬件状态影响比较大

对，希望能有性能比较测试详细的对比

**Comment by conncui** [comment]
Trace Canary 模块集成到线上版本监控了么?

**Comment by Richard-Cao** [comment]
微信有在线上版本使用matrix吗？

**Comment by lolobug** [comment]
> > 楼主的意思是集成在release版中，会不会在性能方面对app有比较大的影响？
> > 或者应该类似leakcanary一样提供一个no-op的依赖？
> 
> 目前还没有 benchmark，但 no-op 是个好主意！不过更多的性能问题，在用户侧更容易发现，测试阶段发现性能问题的范围有限，而且性能问题受手机硬件状态影响比较大

SQLiteLint提供了一个no-op依赖，可以参考一下
