### ISSUE TITLE
执行ApkChecker.jar的时候报错

### ISSUE THREAD

**Issue by starry001** [Tencent/matrix#20]
执行ApkChecker.jar的时候报错
环境：win10
![image](https://user-images.githubusercontent.com/11625352/50429821-6b359d00-08fb-11e9-94f3-9364f269b0c0.png)
{
  "--apk":"C:/ibus/android/Android/app/release/release.apk",
  "--mappingTxt":"C:/ibus/android/Android/app/build/outputs/mapping/release/mapping.txt",
  "--resMappingTxt":"C:/ibus/android/Android/app/build/outputs/mapping/release/resources.txt",
  "--output":"C:/Users/starry/Desktop/outputs/apk-checker-result",
  "--format":"dt.html",
  "--formatConfig":
  [
    {
      "name":"-countMethod",
      "group":
      [
        {
          "name":"Android System",
          "package":"android"
        },
        {
          "name":"java system",
          "package":"java"
        },
      ]
    }
  ],
  "options": [
    {
      "name":"-manifest"
    },
    {
      "name":"-fileSize",
      "--min":"10",
      "--order":"desc",
      "--suffix":"png, jpg, jpeg, gif, arsc"
    },
    {
      "name":"-countMethod",
      "--group":"package"
    },
    {
      "name":"-checkResProguard"
    },
    {
      "name":"-findNonAlphaPng",
      "--min":"10"
    },
    {
      "name":"-checkMultiLibrary"
    },
    {
      "name":"-uncompressedFile",
      "--suffix":"png, jpg, jpeg, gif, arsc"
    },
    {
      "name":"-countR"
    },
    {
      "name":"-duplicatedFile"
    },
    {
      "name":"-unusedResources",
      "--rTxt":"C:/ibus/android/Android/app/build/intermediates/symbols/release/R.txt",
      "--ignoreResources"
      :["R.raw.*",
        "R.style.*",
        "R.attr.*",
        "R.id.*",
        "R.string.ignore_*"
      ]
    },
    {
      "name":"-unusedAssets",
      "--ignoreAssets":["*.so" ]
    }
  ]
}

**Comment by jqctop1** [comment]
CONFIG_FILE_PATH 是表示你的config文件路径，不用加在命令行里

**Comment by starry001** [comment]
> CONFIG_FILE_PATH 是表示你的config文件路径，不用加在命令行里

去掉这个之后还是报相同的错误

**Comment by starry001** [comment]
找到原因了，--format配置的自定义输出格式只能是html 、json、mm.html 以及 mm.json 四种。名字不能更改

**Comment by jqctop1** [comment]
@starry001 是的，暂时只支持了这4种格式，你可以自定义输出的格式，具体可以参考文档
