### ISSUE TITLE
[Bug]LoopMonitor内存问题

### ISSUE THREAD

**Issue by Colibrow** [Tencent/matrix#203]
异常类型：bug

matrix版本： 0.5.1

gradle版本： 3.0.1

问题描述：LoopMonitor对于内存的印象

因为LoopMonitor在监听的时候会加入一个printer进行日志的输出

    Looper.getMainLooper().setMessageLogging(printer = new Printer() {
                @Override
                public void println(String x) {
                	...
                }
            });

所以一旦有多个message快速进入的时候会存在内存不停增加的问题
<img width="1200" alt="profile" src="https://user-images.githubusercontent.com/11855760/56470483-31277280-6479-11e9-8572-e5344ef6637f.png">

**Comment by changelcai** [comment]
```
boolean hasPrinter = false;
Looper looper = Looper.getMainLooper();
Handler handler = new Handler(looper);
looper.setMessageLogging(hasPrinter ? new Printer() {
    @Override
     public void println(String x) {

     }
} : null);
for (int i = 0; i < 10 * 10000; i++) {
    handler.post(runnable);
}
```
是的，之前测试过上面的代码，确实会存在内存抖动的情况，比较极端，暂时没有想到更完美的方案。有什么好的建议吗

**Comment by lijiankun24** [comment]
TraceCanary 是使用 Looper.getMainLooper().setMessageLogging() 的方式实现卡顿帧率检测的吧？为什么我看有的地方说是使用 Choreographer 的方式实现的呢？是版本差异吗

**Comment by changelcai** [comment]
老版本是用Choreographer，现在是依赖Looper.getMainLooper().setMessageLogging()

**Comment by lijiankun24** [comment]
@changelcai 这种差异的原因是？

**Comment by sailor1861** [comment]
@changelcai  能否解释下，为啥改用Looper.getMainLooper().setMessageLogging()方案； 有啥考虑呢?

**Comment by chinacuizichao** [comment]
@changelcai 能否解释下，为啥改用Looper.getMainLooper().setMessageLogging()方案； 有啥考虑呢?

**Comment by buyi** [comment]
@changelcai 能否解释下，为啥改用Looper.getMainLooper().setMessageLogging()方案； 有啥考虑呢?

**Comment by aishang5wpj** [comment]
一直没人回答，小白盲猜一下，Choreographer 只是负责ui绘制部分的监听，ui卡顿不一定是绘制卡顿引起的，有可能是主线程耗时操作引起的ui卡顿，Choreographer监听不到这部分卡顿的逻辑，但是MainLooper可以监听到，就是说MainLooper监听的范围大于Choreographer，是这样吧
