### ISSUE TITLE
bool ksthread_getQueueName(const KSThread thread, char* const buffer, int bufLength)

### ISSUE THREAD

**Issue by lienbao** [Tencent/matrix#213]
bool ksthread_getQueueName(const KSThread thread, char* const buffer, int bufLength)
{
    // WARNING: This implementation is no longer async-safe!
    
    integer_t infoBuffer[THREAD_IDENTIFIER_INFO_COUNT] = {0};
    thread_info_t info = infoBuffer;
    mach_msg_type_number_t inOutSize = THREAD_IDENTIFIER_INFO_COUNT;
    kern_return_t kr = 0;
    
    kr = thread_info((thread_t)thread, THREAD_IDENTIFIER_INFO, info, &inOutSize);
    if(kr != KERN_SUCCESS)
    {
        KSLOG_TRACE("Error getting thread_info with flavor THREAD_IDENTIFIER_INFO from mach thread : %s", mach_error_string(kr));
        return false;
    }
    
    thread_identifier_info_t idInfo = (thread_identifier_info_t)info;
    if(ksmem_isMemoryReadable(idInfo, sizeof(*idInfo)))
    {
        KSLOG_DEBUG("Thread %p has an invalid thread identifier info %p", thread, idInfo);
        return false;
    }

 是不是写错了，应该是！ksmem_isMemoryReadable(idInfo, sizeof(*idInfo)) ？

**Comment by chzhij5** [comment]
https://github.com/kstenerud/KSCrash/blob/master/Source/KSCrash/Recording/Tools/KSThread.c 

这个是KSCrash框架的源码

原框架已经修复了
https://github.com/kstenerud/KSCrash/commit/5a0569bbd733fdf6e04b7f19796047818ddacc04#diff-492007156e854f9181d731e3dd1eca69

我同步下代码，也欢迎提PR

**Comment by chzhij5** [comment]
tag 0.6.0 以及最新master/dev代码，都已经同步最新的KSCrash代码了。 @lienbao
