### ISSUE TITLE
matrixTrace/methodMapping.txt  文件不能生成  

### ISSUE THREAD

**Issue by liuwangle** [Tencent/matrix#214]
我的项目 和 sample-android 都正常运行

但是 methodMapping.txt  文件不能生成  

![image](https://user-images.githubusercontent.com/8718792/57212087-293d0600-7015-11e9-9904-5d90a06f570c.png)

路径下 没有 methodMapping.txt  文件

![image](https://user-images.githubusercontent.com/8718792/57212461-5807ac00-7016-11e9-90da-c8e7abd9931e.png)

Debug.methodmap 文件 也找不到

**Comment by buyiyun** [comment]
我也遇到同样的问题

**Comment by SimplySu** [comment]
@buyiyun 遇到同样问题，windows环境，个人分析：
baseMethodMapFile是我们自己手动添加的方法索引文件methodMapping.txt，
最终需要的方法索引文件会在apk编译的时候，结合配置的baseMethodMapFile，打包一起生成一份最终的methodMapping.txt文件，也就是需要的Debug.methodmap文件；
如windows下生成的路径在build/outputs/mapping/下。

参考：
https://github.com/Tencent/matrix/blob/master/matrix/matrix-android/matrix-gradle-plugin/src/main/java/com/tencent/matrix/trace/transform/MatrixTraceTransform.java

**Comment by buyiyun** [comment]
@SimplySu  从官方给的例子可以知道 ， 在手机SD卡应该要存在一个 Debug.methodmap 文件，也就是说在 apk 编译的时候需要把 build/outputs/mapping/ 的文件拷贝到 手机SDK 这边去， 这个脚本难道需要自己改编译脚本实现吗

**Comment by SimplySu** [comment]
我这边参考：https://github.com/Tencent/matrix/issues/104
如果要在手机本地分析的话，应该是需要push文件到设备里的，官方建议是创建一个gradle的task来执行此工作。估计后期应该是分析工作可能在服务器上来做。

**Comment by buyiyun** [comment]
@SimplySu  看来确实是这样的  这边没有人帮忙写服务端的代码  只能先在本地把堆栈还原 然后记录下来分析

**Comment by SimplySu** [comment]
@buyiyun 抱拳，我来研究下自动化脚本task来看下

**Comment by SimplySu** [comment]
@buyiyun  写了一个脚本，主要在apk的build.gradle中加入任务监听，在assembleDebug task执行完成之后，通过执行adb push命令，自动将mappingMethod.txt文件导入到设备中，可根据需要监听assembleRelease等其它task
``` java
// logging on all the task end execute lifecycle
gradle.taskGraph.afterTask { Task task, TaskState state ->
    // assembleDebug task execute success
    if (!state.failure && "assembleDebug" == task.getName()) {
        String mappingFilePath = "${project.projectDir}/build/outputs/mapping/debug/methodMapping.txt"
        File mappingFile = new File(mappingFilePath)
        // mapping file exists and length > 0
        if (mappingFile.exists() && mappingFile.length() > 0) {
            // execute adb push command
            String cmd = "adb push " + mappingFilePath + " /storage/emulated/0/"
            String cmdRes = cmd.execute().text.trim()
            println cmdRes
        }
    }
}
```

**Comment by buyiyun** [comment]
@SimplySu   666 这个脚本可以用   路径有点不太一样  /build/outputs/mapping/classicNormal/debug/methodMapping.txt  我修改了就可以用
