### ISSUE TITLE
华为荣耀10(COL-AL10)点击sample中的TRACE_CANARY按钮crash

### ISSUE THREAD

**Issue by star3136** [Tencent/matrix#216]
由于运行sample的电脑和当前提交Issue的电脑不是同一台，就不贴堆栈了。

原因：
在显示FPS悬浮窗的时候crash，log显示没有权限。猜测是8.0的问题，看代码，有对8.0做了判断处理，但是缺少动态请求OVERLAY的权限。

解决：
在启动TestTraceMainActivity之前，通过Settings.canDrawOverlays(appContext)判断当前app是否有这个权限，没有的话需要通过这个Intent：
new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:" + getPackageName()))
进入Settings界面打开权限开关。

目前不方便贴代码，纯手敲的，见谅。

**Comment by txfelixzhou** [comment]
好的
