### ISSUE TITLE
iOS崩溃 Crashed: Memory Logging 

### ISSUE THREAD

**Issue by vitosubXX** [Tencent/matrix#220]
异常类型：崩溃

手机型号：iPhone 8

手机系统版本：iOS 11.0.0

matrix版本：matrix-wechat, 0.5.1

问题描述：在Crashlytics收集到崩溃

堆栈/日志：
```
#9
Crashed: Memory Logging
EXC_BREAKPOINT 0x0000000100fb502c

Crashed: Memory Logging
0  App_Name                       0x100fb502c disable_object_event_logger() (object_event_handler.cpp:387)
1  App_Name                       0x100faf49c __memory_logging_event_writing_thread(void*) (memory_logging.cpp:294)
2  libsystem_pthread.dylib        0x18307832c _pthread_body + 308
3  libsystem_pthread.dylib        0x1830781f8 _pthread_body + 310
4  libsystem_pthread.dylib        0x183076c38 thread_start + 4
```

**Comment by chzhij5** [comment]
感谢反馈；已知问题，今天我提commit修复。  

因为宏包围不完整，导致disable时访问了野指针。

**Comment by chzhij5** [comment]
这个 commit 5d103b3372c2cb0f1c55bfdbb20fad4511491826  解决了，已合入dev。 @vitosubXX

**Comment by kimiWu** [comment]
same as

**Comment by JaylonPan** [comment]
same as

**Comment by chzhij5** [comment]
> same as

which version?  tag 0.5.2 and the code after 5d103b3 have solved this problem.

**Comment by JaylonPan** [comment]
> > same as
> 
> which version? tag 0.5.2 and the code after [5d103b3](https://github.com/Tencent/matrix/commit/5d103b3372c2cb0f1c55bfdbb20fad4511491826) have solved this problem.

tag 0.5.1 . thanks,I'll get the tag 0.5.2!
