### ISSUE TITLE
battery、thread、memory相关的代码也开源了，建议wiki也补充下

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#228]
battery、thread、memory相关的代码也开源了，建议wiki也补充下

**Comment by txfelixzhou** [comment]
这块只是实验代码，暂未开源

**Comment by hengheng01** [comment]
请问一下，那功能可以用了吗？

**Comment by TedaLIEz** [comment]
+1, 我看到目前2.0.8已经有了battery的代码，配置项看上去也挺多的，目前只能通过读源码去粗略理解各个参数的含义。请问能否补充一下对应的文档？
