### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Unterminated object

### ISSUE THREAD

**Issue by tangmingscau** [Tencent/matrix#23]
环境：mac 10.13.6 
           java 1.8.0_111

我尝试着去分析apk，但是老是提示json的错误，我已经确认我的json文件是没有问题的
日记是
java -jar matrix-apk-canary-0.4.7.jar --config apkcheckconfig.json
com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 304 path $.--formatConfig

config文件添加到附件，github不支持上传json文件，我改成txt格式上传
[apkcheckconfig.txt](https://github.com/Tencent/matrix/files/2709928/apkcheckconfig.txt)

可以给点意见吗？

**Comment by jqctop1** [comment]
![image](https://user-images.githubusercontent.com/15994990/50441060-edda4e80-0933-11e9-814f-5fa85cefddf0.png)

formatConfig可以先去掉

@tangmingscau

**Comment by tangmingscau** [comment]
这是我的疏忽，谢谢了
