### ISSUE TITLE
代码疑惑咨询

### ISSUE THREAD

**Issue by zhhp1121** [Tencent/matrix#24]
在FrameTracer.java类里面：
public void doFrame(final long lastFrameNanos, final long frameNanos) {
           .....................
           listener.getHandler().post(new Runnable() {
                        @Override
                        public void run() {
                            listener.getHandler().post(new AsyncDoFrameTask(listener,
                                    lastFrameNanos, frameNanos, getScene(), droppedCount));
                        }
           });
}

1.Async异步的实现本质上是通过启动新线程(listener.getHandler()所属的线程，在demo里是HandlerThread("test"))来调用doFrame,AsyncDoFrameTask本身并没有同步或者异步的实现。
2.上面代码里向HandlerThread("test")所在的messagequeue里面抛送了两次runnable，是不是有些冗余，理论上等同于：
public void doFrame(final long lastFrameNanos, final long frameNanos) {
           .....................
           listener.getHandler().post(new AsyncDoFrameTask(listener,
                                    lastFrameNanos, frameNanos, getScene(), droppedCount));
}
个人的一点疑惑，冒昧提出，如果是自己理解错了还请海涵哈。

**Comment by changelcai** [comment]
是的，没有必要。准备fix~

**Comment by zhhp1121** [comment]
MatrixHandlerThread.java
定义了private static HashSet<HandlerThread> handlerThreads = new HashSet<>();
一个静态全局集合类，用来保存新建的HandlerThread。
使用静态handlerThreads集合保存对象一般有两个用途：
<1>延长对象生命周期，因为集合本身是静态的，被引用的对象在没从集合删除之前会存活。但是在代码中查看使用getNewHandlerThread的地方，一处在MethodBeat.java
创建了一个全局静态类对象，这个对象本身便是长生命周期对象；一处在EvilMethodTracer.java的onCreate方法中，由于HandlerThread
的底层实现是创建线程，线程启动以后如果没有通过标记或者中断等方式停止，会一直处于runnable或者wait状态。因此无需再通过
用一个静态集合类来增强HandlerThread对象的生命周期。
<2>使用对象池模式，避免对象重复建立。getNewHandlerThread方法并没有实现对象池模式，每次会根据name新建立一个对象。
因此，这里代码有些存疑。
个人的一点疑惑，冒昧提出，如果是自己理解错了还请海涵哈。

**Comment by zhhp1121** [comment]
MatrixHandlerThread.java
定义了private static HashSet<HandlerThread> handlerThreads = new HashSet<>();
一个静态全局集合类，用来保存新建的HandlerThread。
使用静态handlerThreads集合保存对象一般有两个用途：
<1>延长对象生命周期，因为集合本身是静态的，被引用的对象在没从集合删除之前会存活。但是在代码中查看使用getNewHandlerThread的地方，一处在MethodBeat.java
创建了一个全局静态类对象，这个对象本身便是长生命周期对象；一处在EvilMethodTracer.java的onCreate方法中，由于HandlerThread
的底层实现是创建线程，线程启动以后如果没有通过标记或者中断等方式停止，会一直处于runnable或者wait状态。因此无需再通过
用一个静态集合类来增强HandlerThread对象的生命周期。
<2>使用对象池模式，避免对象重复建立。getNewHandlerThread方法并没有实现对象池模式，每次会根据name新建立一个对象。
因此，这里代码有些存疑。
个人的一点疑惑，冒昧提出，如果是自己理解错了还请海涵哈。
@changelcai

**Comment by txfelixzhou** [comment]
bugfix with  aa3eda92a63c9eef9e8044d13f4d6d7c6d7b5c2d
