### ISSUE TITLE
关于 WCMemoryStatPlugin 的几个疑问

### ISSUE THREAD

**Issue by caiwb** [Tencent/matrix#243]
看代码内存监控通过malloc_logger和__syscall_logger的通知实现，有几个疑问想请教：
1、在避免使用私有api的前提下，是否不支持虚拟内存分配的监控；
2、使用malloc_logger是否也有审核被拒的风险？
3、debug下不支持内存监控，原因是什么？

**Comment by chzhij5** [comment]
1、不使用私有api情况下，不支持vm_allocate/vm_deallocate的监控（__syscall_logger），以及NSAllocateObject创建的对象获取不了类名等（__CFObjectAllocSetLastAllocEventNameFunction && __CFOASafe）；
2、malloc_logger没有被拒风险；
3、debug调试可以支持内存监控，考虑性能问题影响调试体验，而且debug调试下会影响启动类型的判断，所以关了。

**Comment by caiwb** [comment]
感谢回答

**Comment by gelinxiao** [comment]
@chzhij5 你好，请教一个问题，内存监控回调返回的是json数据，在本地存储的是json文件吗？为什么在本地文件里没有找到内存监控的数据？

**Comment by chzhij5** [comment]
> @chzhij5 你好，请教一个问题，内存监控回调返回的是json数据，在本地存储的是json文件吗？为什么在本地文件里没有找到内存监控的数据？

本地数据不一定是json，json是生成的。
内存监控数据在 Library/Cache/Matrix 里面找一找。

**Comment by gelinxiao** [comment]
![image](https://user-images.githubusercontent.com/10257340/62530796-c8230980-b873-11e9-8233-306116017ef6.png)

@chzhij5 找了好长时间才来问的，贴下截图，一直怀疑是这几个文件，但是打不开，看不到内存数据，尴尬。

**Comment by chzhij5** [comment]
@gelinxiao https://github.com/Tencent/matrix/blob/8e80e452d7100be9e67d4f6d9678aa4bcf88b73c/matrix/matrix-iOS/Matrix/WCMemoryStat/MemoryStatPlugin/WCMemoryStatPlugin.mm#L89  看一下这个generate，这个generate会把数据组合成json数据。
