### ISSUE TITLE
config配置选项放进json 命令行运行报错

### ISSUE THREAD

**Issue by SnowMusic** [Tencent/matrix#25]
`java -jar APKChecker.jar --config ./config.json`
[INFO][Matrix.ApkJob]format list [html]
Unknown option: null
直接用命令行配置正常输出，但是把配置写进配置文件(config.json)和jar包同一文件路径，报错如上，是使用方法不正确吗

**Comment by jqctop1** [comment]
看下你的config.json文件

**Comment by SnowMusic** [comment]
已解决，写好之后最好丢到json解析器里面查看一下，我的是多了个逗号
