### ISSUE TITLE
matrix can't catch crash make by assert().

### ISSUE THREAD

**Issue by kimiWu** [Tencent/matrix#260]
异常类型：app 运行时异常

手机型号：iPhone any device

手机系统版本：iOS any version

matrix版本：0.5.1

问题描述：
If run in code assert()，the App will killed. Fabric can catch this as a crash and report Log, but matrix can't catch?

**Comment by chzhij5** [comment]
I test it and I can get it.

Run the Matrix in debugging mode with Xcode?  
Both Matrix and Fabric cannot get the deadly signal callback in debugging mode. The signal is caught by the DeBugger not passed to app.

**Comment by kimiWu** [comment]
> I test it and I can get it.
> 
> Run the Matrix in debugging mode with Xcode?
> Both Matrix and Fabric cannot get the deadly signal callback in debugging mode. The signal is caught by the DeBugger not passed to app.

原因是fabric先截获assert()，并没有再次抛出，导致matrix无法捕获到

**Comment by chzhij5** [comment]
> > I test it and I can get it.
> > Run the Matrix in debugging mode with Xcode?
> > Both Matrix and Fabric cannot get the deadly signal callback in debugging mode. The signal is caught by the DeBugger not passed to app.
> 
> 原因是fabric先截获assert()，并没有再次抛出，导致matrix无法捕获到

got it.
