### ISSUE TITLE
Debug.methodmap 文件无法生成,

### ISSUE THREAD

**Issue by liubin519087720** [Tencent/matrix#265]
这个文件是自动生成吗?
是在手机sd卡路径还是会出现在build文件里?readme中也没找到正确的路径, 这个要手动生成吗

**Comment by JackyAndroid** [comment]
[WARN][MatrixTraceTransform][getMethodFromBaseMethod] not exist!/Users/xxx/Workspace/ThirdPartyProject/matrix/samples/sample-android/app/matrixTrace/methodMapping.txt

使用官方Demo也无法生成
@changelcai @zanyzhao

**Comment by woshishuxiong** [comment]
使用的官方demo，发现生成的mapping就2行：
1,1,sample.tencent.matrix.trace.TestFpsActivity$1 doFrameAsync (Ljava.lang.String;JI)V
1048574,1,android.os.Handler dispatchMessage (Landroid.os.Message;)V

**Comment by nicai1900** [comment]
同问。遇到同样的问题，

**Comment by nicai1900** [comment]
生成的文件目录在另外一个地方。

clean build 后

app/build/outputs/mapping/
![image](https://user-images.githubusercontent.com/2637193/61126435-fca6de00-a4de-11e9-8690-2cbae1a298b1.png)
