### ISSUE TITLE
gradle dependencies可以省略掉matrix-android-lib、matrix-android-commons

### ISSUE THREAD

**Issue by weikano** [Tencent/matrix#27]
像matrix-android-lib之类的应该是plugin都需要的吧，我看了下pom里面的denpendency的scope设置的runtime，这样在build.gradle里面就要多加上matrix-android-lib这些基础库了。

不如直接设置scope为compile，这样就不用把基础库也加上了。

**Comment by txfelixzhou** [comment]
对于“使用说明”来说，我们希望罗列清楚所有依赖，所以使用 runtime的方式； 而如果你觉得麻烦， 可以在 build.gradle 中用 api 来代替 implementation 。

**Comment by weikano** [comment]
这个问题是我没正确理解依赖传递，把scope中的runtime和provided弄混了。以为matrix-android-lib这些基本库是必须要在build.gradle中的dependencies中加上。
就比如使用retrofit，也不需要在build.gradle中加上okhttp和okio的依赖。
其实也算不上什么问题。
