### ISSUE TITLE
Cannot set the value of read-only property 'enable' for object

### ISSUE THREAD

**Issue by Iambigsea** [Tencent/matrix#271]
编译不通过，提示：Cannot set the value of read-only property 'enable' for object of type com.tencent.matrix.trace.extension.MatrixTraceExtension.
异常类型：编译异常

matrix版本： 0.5.2

gradle版本： 2.2.3

**Comment by devLiuGit** [comment]
@txfelixzhou @lambigsea
matrix/matrix-android/matrix-gradle-plugin/src/main/java/com/tencent/matrix/trace/extension/MatrixTraceExtension.java
实现所有字段的 get 方法即可.

这个类原来是 groovy 写的, 在 0.5.2 版本后改用 Java. 在低版本 gradle 会出现这个问题, 怀疑是 groovy 对 Java 字段访问的兼容问题.
