### ISSUE TITLE
deadlock issue:#321 for kscrash

### ISSUE THREAD

**Issue by JaylonPan** [Tencent/matrix#282]
matrix-wechat引用的KSCrash还存在 调用vm_deallocate 死锁的问题 这个问题在KSCrash已经被修复 commit：77a88b2f1c54b565ae93cd81c8613cfff251f811  issue：#321

**Comment by chzhij5** [comment]
Thanks, I update the KSCrash code using in Matrix recently.  I will release a version.

谢谢，Matrix使用到的KSCrash代码已经在我一个本地分支更新了，我最近会发一个大版本。即将有新特性加入。

**Comment by chzhij5** [comment]
最新代码以及tag 0.6.0 已经同步KSCrash的最新代码
