### ISSUE TITLE
SQLitelint接入程序后导致运行很慢

### ISSUE THREAD

**Issue by Cooliii** [Tencent/matrix#286]
程序在windows运行，只接入了sqlitelint，发现接入之后调试运行很卡顿，平均操作响应时间在5s左右吧，注释了publish_issues callback也没有改善。检测的数据库大概有30个，线程同时存在80个左右，想请问一下微信在接入sqlitelint之后会卡顿吗，能否提供一些建议或者可能排查的原因？

**Comment by lolobug** [comment]
微信android已经是在生产环境接入SQLiteLint，但目前没有专门对windows进行适配。
SQLiteLint的检查逻辑都是在单独的异步线程，理论上不会对UI产生卡顿才对。
可以具体说下你如何接入windows的及相关应用场景。

**Comment by Cooliii** [comment]
我是把sqlitelint编译成lib，然后包含进的工程中，在连接db的时候installsqlitelint，在函数sqlite3_trace_v2()的回调函数中调用notifysqlinfo，检查逻辑在异步线程实现我并没有改动。

**Comment by Cooliii** [comment]
谢谢回复，问题我已经找到了。。。
问题出在函数 void Lint::NotifySqlExecution()下的 bool IsInMainThread()调用，sqlitelint源码是在linux系统下写的，我需要在windows下使用，而两个系统在判断线程是否是主线程的时候有一点区别，我改了这一部分的代码，用了一个很蠢的办法。。。导致这里判断的时间很长，从而引起UI的卡顿

**Comment by lolobug** [comment]
可以考虑整理下适配windows代码，然后发个pr看看~~
刚好这边也有同学有相关需求 #268

**Comment by Cooliii** [comment]
我就是直接把sqlitelint的源码摘出来，然后实现了几个函数，编译好就能用了，添加的代码不多我就不放代码了，我把思路整理一下吧：
1、新建一个工程，把sqlitelint源码(https://github.com/Tencent/matrix/tree/master/matrix/matrix-android/matrix-sqlite-lint/src) 导入，记得再加上md5.h和md5.c两个文件，lemon-gen文件夹下的文件都不需要；
2、实现三个函数，分别是SqlExecutionCallback类型、OnPublishIssueCallback类型和sqlite3_trace_v2()函数的回调函数；
3、第一个函数内部就是执行sql语句，第二个函数是处理检测到的issue（输出日志还是弹框提醒或者别的方式随便你），第三个是sqlite3_trace_v2()的回调函数，内部实现调用sqlitelint::NotifySqlExecution()。
配置好路径什么的就可以编译了，我是编译成lib使用的。下面说一下sqlitelint在工程中的使用流程。
1、当建立数据库链接的时候，调用sqlitelint::InstallSQLiteLint()，第二个参数是上面实现的第二个；
2、sqlitelint::SetSqlExecutionDelegate()，参数是上面实现的第一个函数；
3、启用特定的checker，sqlitelint::EnableChecker()
4、追踪sqlite语句的执行，sqlite3_trace_v2()，回调函数是上面实现的第三个。

说的有点啰嗦，希望我表达清楚了。。。
