### ISSUE TITLE
iOS卡顿误报

### ISSUE THREAD

**Issue by caiwb** [Tencent/matrix#288]
异常类型：iOS卡顿误报

matrix版本: V0.5.2

系统版本：iOS 8~12 都有

问题描述：
卡顿日志监控到的主线程卡顿的时间在递增，从用户操作日志观测到用户当时是在正常操作的，偶现。
是否有类似问题，或有什么解决思路吗？

**Comment by chzhij5** [comment]
没有类似问题。

是怎么判别用户能正常操作的？观测到的用户操作是指什么样子的操作？用户在主线程能操作吗？会不会只是因为子线程有日志？

把主线程的堆栈贴出来看看。
