### ISSUE TITLE
ios异常堆栈解析

### ISSUE THREAD

**Issue by zhilinli** [Tencent/matrix#290]
异常类型：ios异常堆栈解析

matrix版本: V0.5.2

系统版本：iOS 11

堆栈：threads =    [
            {
                backtrace =    {
                    skipped = 0;
                    contents =    [
                        {
                            object_name = libsystem_kernel.dylib;
                            symbol_name = semaphore_wait_trap;
                        },
                        {
                            object_name = MyAPP;
                        },
                        {
                            object_name = MyAPP;
                        },
                        {
                            object_name = MyAPP;
                        },
                        {
                            object_name = MyAPP;
                        },
                        {
                            object_name = UIKitCore;
                            symbol_name = <redacted>;
                        }
                                       ]
                                 }
                }]

问题描述：MyAPP对应的symbol_name没有内容。
若要发布到线上是需要将matrix-wechat构建的Strip Style设置 为Debugging Symbols么？
我看Cocoapods引入默认是Debugging Symbols【谢谢回答】

**Comment by chzhij5** [comment]
稍等，我贴一篇wiki上来。

**Comment by chzhij5** [comment]
@zhilinli https://github.com/Tencent/matrix/wiki/About-macOS-&-iOS-symbol  看看这篇wiki能不能解答你的一些问题， 如果有问题欢迎继续提问。

**Comment by zhilinli** [comment]
感谢解答，WCCrashReportInterpreter这个类的目的是什么，我用它来符号化原始的.crash文件，并不能成功解析出对应的函数名称

**Comment by zhilinli** [comment]
主要问题是没法对整个文件一次性符号化解析，一个地址一个地址去解析的效率太慢

**Comment by chzhij5** [comment]
> 感谢解答，WCCrashReportInterpreter这个类的目的是什么，我用它来符号化原始的.crash文件，并不能成功解析出对应的函数名称

这个类利用了二进制未裁掉的符号来自解析符号。需要你编译运行的包，没有裁掉符号，而且生成Crash日志的包要和运行时的安装包是同一次编译生成的。

微信平时用这个类看自己编译的真机包的Crash。微信内部自己编译的包不用把dSYM文件留存起来，这时候把相关Crash导入自己的包，自解析下就能看到符号了。

**Comment by gelinxiao** [comment]
@chzhij5 你好，如果是 Release 版本，把符号信息都裁掉的情况下，部分是没有 symbol_name 字段的，那怎么去解析 symbol_name？

**Comment by chzhij5** [comment]
> @chzhij5 你好，如果是 Release 版本，把符号信息都裁掉的情况下，部分是没有 symbol_name 字段的，那怎么去解析 symbol_name？

参考  https://github.com/Tencent/matrix/wiki/About-macOS-&-iOS-symbol 

用 dsym 文件，google关键字 symblicatecrash, atos。
