### ISSUE TITLE
是必须有SplashActivity才行么？如何在没有SplashActivity的情况下检测启动时间？

### ISSUE THREAD

**Issue by maxdylan** [Tencent/matrix#294]
是不是我对StartUp监控有误解，在我使用的时候，如果没有SplashActivity是无法正常获取到启动时间，不管设置成null还是设置成""，splashActivitiesSet.isEmpty()都是返回false，如何在没有SplashActivity的情况下检测启动时间？

**Comment by changelcai** [comment]
不要配置splashActivitiesSet即可

**Comment by forrey09** [comment]
还遇到个蛋疼的问题，SplashActivity 不能继承AndroidX的activity否则还是无法检测时间
