### ISSUE TITLE
无法编译 语法错误

### ISSUE THREAD

**Issue by 704480904** [Tencent/matrix#296]
036433
![image](https://user-images.githubusercontent.com/6984303/62017481-661a3280-b1e9-11e9-9d14-50740d829093.png)

![image](https://user-images.githubusercontent.com/6984303/62017498-6f0b0400-b1e9-11e9-87e9-cd7b3d38d9c2.png)

**Comment by Lynch201** [comment]
TestTraceMainActivity类中报错处理方法：
1、按照提示删除重复定义的方法
2、未定义的变量、无法引入的包删除
3、重新运行工程即可

**Comment by Lynch201** [comment]
已经提交pr
