### ISSUE TITLE
0.5.2版本 项目里依赖的代码和远程master分支上的代码不一致

### ISSUE THREAD

**Issue by maxdylan** [Tencent/matrix#297]
异常类型：远程代码和本地依赖代码不一致

matrix版本：如: 0.5.2

gradle版本：如: 3.0.0

问题描述：项目里依赖的代码（使用ctrl+左键查看源码）和远程master分支上的代码不一致，和release里面对应版本下载下来的source code也不一致，source code 和 master分支代码是一致的。

主要发现问题的类和方法是  trace-canary 里面的 TraceConfig.java里面的getSplashActivity()方法
 
本地代码
<img width="966" alt="local-trace-config" src="https://user-images.githubusercontent.com/12027183/62049559-1451c680-b242-11e9-819b-d004feb8b301.png">

远程代码

<img width="960" alt="master-trace-config" src="https://user-images.githubusercontent.com/12027183/62050417-c6d65900-b243-11e9-93af-84a1a5db1ec3.png">

**Comment by txfelixzhou** [comment]
master是最新最稳定的代码，而release是稳定的里程碑的代码，所以代码上，release会比master要老
