### ISSUE TITLE
iOS版本中flush_last_data方法有问题

### ISSUE THREAD

**Issue by jseanj** [Tencent/matrix#299]
```
//event_buffer = open_or_create_allocation_event_buffer(log_dir);
event_buffer = open_or_create_allocation_event_buffer_static();
```
不知这里为啥注释掉了，注释掉的话，调用flush_last_data就会有问题，因为在flush_last_data 中，event_buffer是从文件映射过来的，因为这个文件从来没有写入过，所以执行到这就会退出。
```
allocation_event_buffer *event_buffer = open_or_create_allocation_event_buffer(log_dir);
if (event_buffer == NULL) {
	return;
}
if (has_event_in_buffer(event_buffer) == false) {
	__malloc_printf("has no event in buffer");
	close_allocation_event_buffer(event_buffer);
	return;
}
```

**Comment by chzhij5** [comment]
赞

最开始的时候 allocation_event_buffer（当初大小 16M，具体 STACK_LOGGING_EVENT_BUFFER_SIZE 控制） 是写在文件里，下次启动 flush_last_data 把上次没写完的数据写在 allocation_event_db 里，open_or_create_allocation_event_buffer 和 flush_last_data 搭配使用

后面为了性能， buffer 大小改成 4M，并且放进内存里不写文件，可能存在漏写 app 最后一刻内存事件的问题

你可以根据项目实际情况选择适合的方式

**Comment by jseanj** [comment]
了解了，谢谢！
