### ISSUE TITLE
如何重写APKChecker的输出

### ISSUE THREAD

**Issue by SnowMusic** [Tencent/matrix#30]
去哪里重写或者说如何重新定义apkchecker的输出呢？https://github.com/Tencent/matrix/wiki/Matrix-ApkChecker
其中的task不知道在哪

**Comment by jqctop1** [comment]
![image](https://user-images.githubusercontent.com/15994990/50463827-cbdedb80-09c8-11e9-8e71-dbd63c19693d.png)

**Comment by jqctop1** [comment]
不知在哪里是什么意思？有两种途径：
1. 直接改源码，增加自己的format
2. 按照上述截图的指引打包成jar，然后加上--formatJar参数指定自定义格式jar包（你可以直接在eclipse中依赖apk-checker的jar包，然后开发你自己的格式）
