### ISSUE TITLE
iOS卡顿监控的数据量是否可以配置

### ISSUE THREAD

**Issue by BaffinBu** [Tencent/matrix#302]
想要做监控数据的可视化,但是发现回调数据体积很大,  binary_image和所有cpu寄存器的值好像对定位卡顿用处不大,可不可以让这些数据变的可配置

**Comment by chzhij5** [comment]
没有Binary_Image信息，堆栈中的地址就找不到它们对应的符号了。 如果是当机自解析符号，可能Binary_Image不需要；但如果是用dSYM文件去解符号，Binary_Image中的uuid信息是依据，是一定要的。

如果你不需要这一段数据，你可以改一下 KSCrashReport.c 中的代码

卡顿数据和Crash数据格式是比较标准了。据我所知一个卡顿数据的json文本文件，大概是500k以内？为什么监控可视化和大小有关呢？

**Comment by BaffinBu** [comment]
谢谢回复,但是目前binary_image,包含了所有的 image,如果能只提供卡顿的部分 image是否更好,debug开发自己看卡顿和大小没关系,但想upload到server以后画图来监控,所以500k就挺大的了,我们现在是自己mapping重新组装了一份精简版的json

**Comment by chzhij5** [comment]
> 谢谢回复,但是目前binary_image,包含了所有的 image,如果能只提供卡顿的部分 image是否更好,debug开发自己看卡顿和大小没关系,但想upload到server以后画图来监控,所以500k就挺大的了,我们现在是自己mapping重新组装了一份精简版的json

压缩再上传后，应该差别不大？ 微信目前是多份json组合压缩上传的。

**Comment by HOMHOG** [comment]
> 谢谢回复,但是目前binary_image,包含了所有的 image,如果能只提供卡顿的部分 image是否更好,debug开发自己看卡顿和大小没关系,但想upload到server以后画图来监控,所以500k就挺大的了,我们现在是自己mapping重新组装了一份精简版的json

自己mapping是怎么做的 我们有类似的需求

**Comment by aiquantong** [comment]
自己mapping是怎么做的 我们有类似的需求
