### ISSUE TITLE
[matrix-apk-canary] 使用 CRC-32 代替 MD5 值检查文件的重复性

### ISSUE THREAD

**Issue by SmartDengg** [Tencent/matrix#308]
`DuplicateFileTask` 重新计算了每个文件的 MD5 值，而不是在解压 apk 时记录每个 `ZipEntry` 的 CRC-32，来判断多个文件的相同，是出于什么考虑吗？

**Comment by txfelixzhou** [comment]
crc更多是用于少量数据的校验，比如网络报文等，对于文件通常还是用md5。
