### ISSUE TITLE
matrix-thread-canary 的版本号未更新

### ISSUE THREAD

**Issue by chentao7v** [Tencent/matrix#310]
matrix-thread-canary 的版本号（0.4.10.3）未随主库 版本号（0.6）更新

**Comment by txfelixzhou** [comment]
能给出在哪儿还显示有0.4.10.3吗，我已经搜索完全部代码

**Comment by chentao7v** [comment]
https://dl.bintray.com/matrix/maven/com/tencent/matrix/matrix-thread-canary/
我直接跑的 demo 没跑起来，改了版本号就可以了

**Comment by 18Gray** [comment]
上面显示4天前，我今天拉代码还没改，matrix-thread-canary不对，不是0.6.0

**Comment by txfelixzhou** [comment]
thread模块当前只处在feature/dev(也就是微信的内部使用中），还没达到开源标准，不应该上传到bintray。后续开源后会同步更新的
