### ISSUE TITLE
allocation_event_buffer实现

### ISSUE THREAD

**Issue by HuangXiZhu** [Tencent/matrix#313]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
matrix版本：如: 0.4.7

问题描述：如：STACK_LOGGING_EVENT_BUFFER_SIZE为什么必须是2^n?


Matrix 是一个开源项目，希望大家遇到问题时要学会先思考，看看 Sample 与 Matrix 的源码，更鼓励大家给我们提 pr .

**Comment by chzhij5** [comment]
@HuangXiZhu 更详细的问题描述？

**Comment by HuangXiZhu** [comment]
感谢回复，主要是想请教一下关于allocation_event_buffer.cpp中STACK_LOGGING_EVENT_BUFFER_SIZE为什么是(4ll << 20) ，并且不理解为什么一定要是2^n次方，这么设计的目的是什么呢？谢谢您回复。

**Comment by chzhij5** [comment]
> 感谢回复，主要是想请教一下关于allocation_event_buffer.cpp中STACK_LOGGING_EVENT_BUFFER_SIZE为什么是(4ll << 20) ，并且不理解为什么一定要是2^n次方，这么设计的目的是什么呢？谢谢您回复。

因为 allocation_event_buffer 是循环数组实现的，里面的 read_index 和 write_index 要与 STACK_LOGGING_EVENT_BUFFER_SIZE 取模

而 index %  (2^n) 可优化为 index & (2^n - 1)

所以 STACK_LOGGING_EVENT_BUFFER_SIZE 必须 2^n 。

**Comment by HuangXiZhu** [comment]
清楚明白，十分感谢您！
