### ISSUE TITLE
appmethodbeat不能停止

### ISSUE THREAD

**Issue by jackqpf** [Tencent/matrix#316]
`
    private static void realExecute() {
        MatrixLog.i(TAG, "[realExecute] timestamp:%s", System.currentTimeMillis());

        sCurrentDiffTime = SystemClock.uptimeMillis() - sDiffTime;

        sHandler.removeCallbacksAndMessages(null);
        sHandler.postDelayed(sUpdateDiffTimeRunnable, Constants.TIME_UPDATE_CYCLE_MS);
        sHandler.postDelayed(checkStartExpiredRunnable = new Runnable() {
            @Override
            public void run() {
                synchronized (statusLock) {
                    MatrixLog.i(TAG, "[startExpired] timestamp:%s status:%s", System.currentTimeMillis(), status);
                    if (status == STATUS_DEFAULT || status == STATUS_READY) {
                        status = STATUS_EXPIRED_START;
                    }
                }
            }
        }, Constants.DEFAULT_RELEASE_BUFFER_DELAY);

        ActivityThreadHacker.hackSysHandlerCallback();
        LooperMonitor.register(looperMonitorListener);
    }
`
当在messagequeue中post了更新时间的任务，由于这个任务会循环执行，后面的start启动超时任务不可能会执行到呀。反编译看微信中也是这样 emmmmm

**Comment by changelcai** [comment]
Handler的机制你理解错的吧？sUpdateDiffTimeRunnable虽然是循环执行，但并不会饿死checkStartExpiredRunnable的。

**Comment by jackqpf** [comment]
我这边用demo实测在不初始化的情况下，这个超时handler不会执行


原始邮件
发件人:changelcainotifications@github.com
收件人:Tencent/matrixmatrix@noreply.github.com
抄送:jackqpfjack.qin@ximalaya.com; Authorauthor@noreply.github.com
发送时间:2019年8月15日(周四) 10:52
主题:Re: [Tencent/matrix] appmethodbeat不能停止 (#316)


Handler的机制你理解错的吧？sUpdateDiffTimeRunnable虽然是循环执行，但并不会饿死checkStartExpiredRunnable的。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
Handler的机制你理解错的吧？sUpdateDiffTimeRunnable虽然是循环执行，但并不会饿死checkStartExpiredRunnable的。

**Comment by jackqpf** [comment]
用了你们的demo实测以及用了之下写的测试代码，都不会执行，麻烦check一下

HandlerThread handlerThread = new HandlerThread("");
        handlerThread.start();
        Handler handler = new Handler(handlerThread.getLooper());
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    SystemClock.sleep(150);
                    synchronized (object) {
                        try {
                            object.wait();
                            Log.i(TAG, "22222");
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }
        }, 50);
        Looper.getMainLooper().setMessageLogging(new Printer() {
            @Override
            public void println(String x) {
                synchronized (object) {
                        object.notify();
                }
            }
        });
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.i(TAG, "111111");
            }
        }, 5000);
