### ISSUE TITLE
请问stack信息在后台是如何聚合的？

### ISSUE THREAD

**Issue by tanglie1993** [Tencent/matrix#317]
在TraceCanary的EvilMethod中，同一stackKey可以对应很多不同的stack。
请问在你们的管理后台中，是怎样将相同stackKey的不同stack聚合起来的？根据stack去掉调用次数、去掉耗时之后的结果吗？还是不聚合，直接一条条看？

**Comment by tanglie1993** [comment]
而且这个stack和一般的堆栈不太一样，同一depth的元素可能有多个，实际上是树形的。你们会把它裁剪成正常的调用栈再去聚合吗？

**Comment by txfelixzhou** [comment]
stackey是matrix判断出一个堆栈中最有可能出现问题的一行堆栈（没有调用次数和耗时），所以会出现你说的同一stackey不同stack的情况，这里的stackkey就已经是我们聚合的条件了。

在我们的后台，查找某种stackey的类型问题时，会把此stackey的所有堆栈放在一起展示

**Comment by tanglie1993** [comment]
@txfelixzhou 谢谢！
请问如果一个stackkey有几百种不同的stack，那么如何把堆栈排序呢？

**Comment by txfelixzhou** [comment]
这块我们做了处理，会按执行时间来排序
