### ISSUE TITLE
请问支持Android SDK level 17, 18 吗？

### ISSUE THREAD

**Issue by stepforfuture** [Tencent/matrix#325]
我们的项目主要泡在android level 17，18上面 ，但是我集成matrix后说 最低sdk版本要求19

**Comment by txfelixzhou** [comment]
![image](https://user-images.githubusercontent.com/15136816/63482219-b3c54a80-c4ca-11e9-92ed-e98bc4bd70ab.png)
从上图来看，你们应该要升级了，17，18太老了
