### ISSUE TITLE
WCBlockMonitorConfiguration.h 头文件里面没有定义 bGetPowerConsumeStack

### ISSUE THREAD

**Issue by YY-Wei** [Tencent/matrix#326]
![image](https://user-images.githubusercontent.com/54052330/63399385-f28fcd80-c402-11e9-9001-40d932dbee0d.png)

**Comment by chzhij5** [comment]
https://github.com/Tencent/matrix/blob/8e80e452d7100be9e67d4f6d9678aa4bcf88b73c/matrix/matrix-iOS/Matrix/WCCrashBlockMonitor/CrashBlockPlugin/Main/BlockMonitor/WCBlockMonitorConfiguration.h#L60
