### ISSUE TITLE
debug环境不会插入at（）方法

### ISSUE THREAD

**Issue by BeWaterMF** [Tencent/matrix#327]
版本：0.4.10

打debug包时mCollectedClassExtendMap中不包含FragmentActivity的继承关系，所以isActivityOrSubClass（）为false，导致不插入at（）方法。
release包mCollectedClassExtendMap中包含FragmentActivity的继承关系。

为什么？

**Comment by changelcai** [comment]
0.4.10比较老了，用最新的版本试试看先

**Comment by BeWaterMF** [comment]
用了0.6.0，依然是这样

**Comment by BeWaterMF** [comment]
升级了gradle版本，升级前应该是没问题

**Comment by changelcai** [comment]
debug clean build 也不行？gradle版本 从多少升级到多少

**Comment by BeWaterMF** [comment]
clean 后也不行，
gradle 版本从3.3 升到 5.5.1
gradle 插件版本从 2.2.3 升到3.4.2

**Comment by BeWaterMF** [comment]
debug包收集到的method数只有release包的一半
从matrix_output/classes下的文件来看，比之前少了很多第三方的文件，还有一点不同的是debug包的matrix_output/classes下的文件最终没有打成jar包，而是按目录结构散落的

**Comment by BeWaterMF** [comment]
这个问题能解决下吗，我下了0.6.0版本的demo，也是能复现这个

**Comment by BeWaterMF** [comment]
@changelcai 这个问题能解决下吗，我下了0.6.0版本的demo，也是能复现这个

**Comment by changelcai** [comment]
加下微信了解下具体情况caicy1662

**Comment by BeWaterMF** [comment]
发申请了

**Comment by whataa** [comment]
#319

**Comment by JackyAndroid** [comment]
#321
