### ISSUE TITLE
matrix-trace在vivo X5SL android4.4手机上点击崩溃

### ISSUE THREAD

**Issue by chenguo4930** [Tencent/matrix#328]
异常类型：app 运行时异常/编译异常

手机型号：vivo X5SL

手机系统版本: Android 4.4

matrix版本： 0.5.2

gradle版本：5.0

问题描述：在这台手机上，点击会崩溃，在小米4的android版本4.4上面没有问题

堆栈/日志：
![image](https://user-images.githubusercontent.com/11734169/63563329-4fba8900-c593-11e9-87a0-6aeb05c2fa9f.png)

**Comment by chenguo4930** [comment]
项目中使用到了混淆，是没有添加到防止混淆吗

**Comment by txfelixzhou** [comment]
请使用最新的0.6.0

**Comment by chenguo4930** [comment]
> 请使用最新的0.6.0
还是会崩溃，升级了0.6.0
![image](https://user-images.githubusercontent.com/11734169/64932740-98542200-d873-11e9-9936-95783f1c8a88.png)

**Comment by chenguo4930** [comment]
> 请使用最新的0.6.0

升级了0.6.0，还是会崩溃
![image](https://user-images.githubusercontent.com/11734169/64932765-d4878280-d873-11e9-89c4-4d18609614df.png)

**Comment by chenguo4930** [comment]
我在testin上用4.4版本测试都会出现崩溃，日志如下，三星手机
![image](https://user-images.githubusercontent.com/11734169/65138741-fe8ca080-da3d-11e9-9218-6d405d394fe4.png)
