### ISSUE TITLE
ks2apple.py 解析出错

### ISSUE THREAD

**Issue by yantao13145210** [Tencent/matrix#331]
![image](https://user-images.githubusercontent.com/5452615/63577540-2fa1be80-c5c1-11e9-90a0-4b5a84aab572.png)
ks2apple.py 解析出错，错误如上图所示

**Comment by chzhij5** [comment]
可以帮忙兼容一下，并提个 pull request 过来吗？  这边没有例子可以复现这个问题，或者把出问题的 json 贴一下。

**Comment by yantao13145210** [comment]
> 可以帮忙兼容一下，并提个 pull request 过来吗？ 这边没有例子可以复现这个问题，或者把出问题的 json 贴一下。

@chzhij5 ，能否加个微信单聊，沟通效率高一点，谢谢；

**Comment by huakucha** [comment]
ks2apple.py 转换之后 生成的产物 好像不能用symbolicatecrash符号化了 最后也要一行一行的符号化？

**Comment by chzhij5** [comment]
> > 可以帮忙兼容一下，并提个 pull request 过来吗？ 这边没有例子可以复现这个问题，或者把出问题的 json 贴一下。
> 
> @chzhij5 ，能否加个微信单聊，沟通效率高一点，谢谢；

发信息给我邮箱 johnzjchen@tencent.com，我给你个二维码。  工作太忙，这里回复效率很低。

**Comment by chzhij5** [comment]
> ks2apple.py 转换之后 生成的产物 好像不能用symbolicatecrash符号化了 最后也要一行一行的符号化？

不能，需要自己加一下 otool 解析。

**Comment by MIyulong** [comment]
问题修复的，我这边也碰到这个的，解析报错的
![image](https://user-images.githubusercontent.com/8175565/66734053-4d3e2680-ee94-11e9-8bfe-c46f9bac44b6.png)

**Comment by KorolZhu** [comment]
@MIyulong json是个数组，需要把里面的字段拆出来，然后再调用脚本解析

**Comment by MIyulong** [comment]
嗯嗯，看过脚本后，已经解决了的

发自我的 iPhone

**Comment by linziyiwj** [comment]
> @MIyulong json是个数组，需要把里面的字典拆出来，然后再调用脚本解析

请问是拆哪个字典？
