### ISSUE TITLE
耗电量

### ISSUE THREAD

**Issue by feng562925462** [Tencent/matrix#344]
最近提交的耗电量检测，为什么出现了一次cpu使用量超标，就追踪一分钟的数据（追踪时间、cpu总量等），而不是直接取当前堆栈就结束，这里是如何定义耗电量检测的

**Comment by chzhij5** [comment]
首先不叫“耗电量检测”，耗电监控没有量化耗了多少电，“量”字应该去掉。

耗电监控是追踪一段时间内最耗 CPU 的堆栈，关注的是让 CPU 在一分钟内平均超过 80 % 的堆栈是什么。

当 CPU 过高，就取当前堆栈，并不能说明耗电，这有可能是正常的使用，比如突然绘制个动画。
而一分钟内 CPU 占用一直超量使用，那么就很有可能是滥用了。

**Comment by zt1993** [comment]
你好，我想问下你们这个只获取cpu的使用情况的话，耗电量较多的网络、定位、蓝牙等也是只能通过各自占用线程去监控吗？

**Comment by chzhij5** [comment]
> 你好，我想问下你们这个只获取cpu的使用情况的话，耗电量较多的网络、定位、蓝牙等也是只能通过各自占用线程去监控吗？

网络可以通过I/O去做的；定位和蓝牙可以通过收敛业务接口，看看业务是否有滥用接口，比如开了定位但是忘记关了。

**Comment by zt1993** [comment]
> > 你好，我想问下你们这个只获取cpu的使用情况的话，耗电量较多的网络、定位、蓝牙等也是只能通过各自占用线程去监控吗？
> 
> 网络可以通过I/O去做的；定位和蓝牙可以通过收敛业务接口，看看业务是否有滥用接口，比如开了定位但是忘记关了。

感谢回复，因为我们现在是需要量化单个App具体消耗了多少电量（百分比），当然第一阶段主要是用于线下测试，能有一个参考指标。看了下metrix 的方案主要是针对线上的，算是对资源浪费的推测，参考了手Q的方案后发现大多都是如此。不管怎么样，非常感谢您的分享
