### ISSUE TITLE
WCBlockMonitorMgr 的 m_currentState 相关问题请教

### ISSUE THREAD

**Issue by wang9262** [Tencent/matrix#356]
`m_currentState` 在主线程被赋值，但是在子线程中被读取，这样可能导致在子线程读取到的值可能是错误的。目前我们采用类似 `WCBlockMonitorMgr` 的逻辑，上线后发现，检测到了一些只有回到后台才会执行的调用栈，同时根据我们记录的日志，发现这种卡顿时的 `m_currentState` 和 ` [UIApplication sharedApplication].applicationState` 并不一致。

比如[如下代码片段](https://github.com/Tencent/matrix/blob/8e80e452d7100be9e67d4f6d9678aa4bcf88b73c/matrix/matrix-iOS/Matrix/WCCrashBlockMonitor/CrashBlockPlugin/Main/BlockMonitor/WCBlockMonitorMgr.mm#L575-L584)

```
// 用户 Home 键回到后台，此处打印 [UIApplication sharedApplication].applicationState 和 m_currentState 可能并不一致，前者为 UIApplicationStateBackground ，后者为 UIApplicationStateActive

if (m_currentState == UIApplicationStateBackground) {
            if (g_enterBackground.tv_sec != 0 || g_enterBackground.tv_usec != 0) {
                unsigned long long enterBackgroundTime = [WCBlockMonitorMgr diffTime:&g_enterBackground endTime:&tvCur];
                if (__timercmp(&g_enterBackground, &tvCur, <) && (enterBackgroundTime > APP_SHOULD_SUSPEND)) {
                    MatrixInfo(@"may mistake block %lld", enterBackgroundTime);
                    return EDumpType_Unlag;
                }
            }
            return EDumpType_BackgroundMainThreadBlock;
}
```

不知微信内部是否有类似情况？
这里没有选择直接在子线程读取 `[UIApplication sharedApplication].applicationState`而是使用实例变量来存储当前应用状态除了线程安全是否还有其他方面的考虑呢？

**Comment by chzhij5** [comment]
“发现这种卡顿时的 m_currentState 和 [UIApplication sharedApplication].applicationState 并不一致。”

理论上，现在微信这种写法有时机会出现这种问题，但是目前在微信中没有发现，再想了下，这里的 m_currentState 加上 atomic 标记会更好点。

“这里没有选择直接在子线程读取 [UIApplication sharedApplication].applicationState而是使用实例变量来存储当前应用状态除了线程安全是否还有其他方面的考虑呢？”

只是考虑到这一点： [UIApplication sharedApplication].applicationState 这个按系统要求需要在主线程去获取。

**Comment by wang9262** [comment]
明白了，谢谢解答
