### ISSUE TITLE
说明文档写得不认真，有坑

### ISSUE THREAD

**Issue by feer921** [Tencent/matrix#357]
1、光看github上的描述使用步骤的话，压根就不起作用；
2、sample-android里面定义 group: "com.tencent.matrix", name: "matrix-thread-canary", version: "MATRIX_VERSION", changing: true,错误，jcenter上压根没有该版本，而是 0.4.10.3
3、github上说明文档里，定义MATRIX_VERSION代码写得有误，应该是ext.MATRIX_VERSION = '0.6.0' 
认真点，老铁们

**Comment by txfelixzhou** [comment]
非常抱歉，是我们分支管理上存在不足，将内部还在孵化的thread功能提前合入了dev，而发布到Jcenter是没有这块功能的。感谢老铁的意见 ，我们下次一点再多check几遍。
目前已经修复 #359
