### ISSUE TITLE
ApkChecker 不支持dex 038格式反编译

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#36]
dex2jar 最新版已经支持了，这个是否有兼容计划呢

**Comment by jqctop1** [comment]
好的，后续也兼容下

**Comment by hfutgl** [comment]
@jqctop1 
git clone git://github.com/iBotPeaches/Apktool.git
apkchecker里的apktool.jar 你们增加的源码能开源出来么？我比较了下，发现你们增加了一些包

**Comment by jqctop1** [comment]
@hfutgl 我看看哈，记得并没有改apktool的源码，只是精简了一下他的可执行jar

**Comment by jqctop1** [comment]
@hfutgl 
![image](https://user-images.githubusercontent.com/15994990/50515828-fbcdd200-0ae1-11e9-9546-c6e761f9866a.png)

目前的ApkTool.jar是从这个commit编出的包，这里不太记得历史了。但是没有修改源码的，过两天我换成最新的ApkTool.jar

**Comment by hfutgl** [comment]
@jqctop1  之前说的XXXAPK_unzip文件删除失败，是因为这个文件夹还在被其他task使用，线程池用shutdown函数并没有把所有task都关掉；之前已经设置10分钟超时，后面可以用shudownnow强关

**Comment by jqctop1** [comment]
@hfutgl 好的，正在排查是哪个task

**Comment by hfutgl** [comment]
@jqctop1  可以从测试机里pull一些系统预制APP测试看看，能发现一下问题；除了dex 038没改，我本地改了一些BUG适配系统应用解析
