### ISSUE TITLE
iOS 卡顿检查如何获取卡顿耗时？

### ISSUE THREAD

**Issue by bmcciscoding** [Tencent/matrix#362]
运行环境：iOS 模拟器
Matrix版本：0.6.0

想知道如何获取卡顿的耗时。我们项目需要把卡顿耗时上报。

首先我从 log 里找不到耗时的字段。我看安卓是提供了这个字段的

```Objective-C
NSString *jsonString = [[NSString alloc] initWithData:issue.issueData encoding:NSUTF8StringEncoding];
```

然后我看到这个代理提供卡顿时间，但是我不知道如何对应到某个卡顿？我能否先纪录这个时间，然后在 onAppendAdditionalInfoCallBack 再写入？

```Objective-C
#pragma mark - WCCrashBlockMonitorDelegate

- (void)onCrashBlockMonitorBeginDump:(EDumpType)dumpType blockTime:(uint64_t)blockTime {
    
}
```

之后我看源码，发现这个参数 blockTime 传到最后的时居然没有使用。
```Objective-C
+ (NSString *)dumpReportWithReportType:(EDumpType)dumpType
                         withBlockTime:(uint64_t)blockTime
                   withExceptionReason:(NSString *)exceptionReason
                       selfDefinedPath:(BOOL)bSelfDefined
{
    KSCrash *handler = [KSCrash sharedInstance];
    NSString *name = [NSString stringWithFormat:@"%lu", (unsigned long) dumpType];
    NSString *crashReportPath = @"";
    if (bSelfDefined) {
        crashReportPath = [WCDumpInterface genFilePathWithReportType:dumpType];
        [handler reportUserException:name
                              reason:exceptionReason
                            language:@""
                          lineOfCode:NULL
                          stackTrace:NULL
                       logAllThreads:true
                    terminateProgram:false
                        dumpFilePath:crashReportPath
                            dumpType:(int)dumpType];
    } else {
        [handler reportUserException:name
                              reason:exceptionReason
                            language:@""
                          lineOfCode:NULL
                          stackTrace:NULL
                       logAllThreads:true
                    terminateProgram:false];
    }
    return crashReportPath;
}

```

最后，想知道如何获取到卡顿时间？还是我需要再配置什么吗？
```Objective-C
    // 监控能力
    WCCrashBlockMonitorConfig *crashBlockConfig = [[WCCrashBlockMonitorConfig alloc] init];
    crashBlockConfig.appVersion = [CompassUtils defaultAppVersion];
    crashBlockConfig.appShortVersion = [CompassUtils defaultAppVersion];
    crashBlockConfig.enableCrash = NO;
    crashBlockConfig.enableBlockMonitor = YES;
    crashBlockConfig.blockMonitorDelegate = self;
    crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;
    crashBlockConfig.reportStrategy = EWCCrashBlockReportStrategy_All;

    // 监控指标
    WCBlockMonitorConfiguration *blockMonitorConfig = [WCBlockMonitorConfiguration defaultConfig];
    blockMonitorConfig.bMainThreadHandle = YES;
    blockMonitorConfig.bFilterSameStack = YES;
    blockMonitorConfig.bPrintMemomryUse = YES;
    blockMonitorConfig.bGetCPUHighLog = YES;
    blockMonitorConfig.bPrintCPUUsage = YES;
    blockMonitorConfig.bGetCPUHighLog = YES;
    crashBlockConfig.blockMonitorConfiguration = blockMonitorConfig;
```

**Comment by BaffinBu** [comment]
dev分支已经支持blocktime为微秒单位
blocktime默认没有,可以使用kscrash_crashCallback自定义传递给WCCrashBlockMonitorConfig的onAppendAdditionalInfoCallBack
ex:
void kscrash_crashCallback(const KSCrashReportWriter *writer) {
    writer->beginObject(writer, "BlockTime");
    writer->addFloatingPointElement(writer,"blockTime",threadBlockTime);
    writer->endContainer(writer);
}
 crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;

**Comment by huakucha** [comment]
threadBlockTime怎么传递出来

**Comment by bmcciscoding** [comment]
> dev分支已经支持blocktime为微秒单位
> blocktime默认没有,可以使用kscrash_crashCallback自定义传递给WCCrashBlockMonitorConfig的onAppendAdditionalInfoCallBack
> ex:
> void kscrash_crashCallback(const KSCrashReportWriter *writer) {
> writer->beginObject(writer, "BlockTime");
> writer->addFloatingPointElement(writer,"blockTime",threadBlockTime);
> writer->endContainer(writer);
> }
> crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;

通过这个方法 我们检测到的数据有卡顿 50s 70s 的，这个卡顿也太久了吧？

**Comment by chzhij5** [comment]
> > dev分支已经支持blocktime为微秒单位
> > blocktime默认没有,可以使用kscrash_crashCallback自定义传递给WCCrashBlockMonitorConfig的onAppendAdditionalInfoCallBack
> > ex:
> > void kscrash_crashCallback(const KSCrashReportWriter *writer) {
> > writer->beginObject(writer, "BlockTime");
> > writer->addFloatingPointElement(writer,"blockTime",threadBlockTime);
> > writer->endContainer(writer);
> > }
> > crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;
> 
> 通过这个方法 我们检测到的数据有卡顿 50s 70s 的，这个卡顿也太久了吧？

看一下是不是在 suspend 后出现的？

**Comment by SnailLife** [comment]
> dev分支已经支持blocktime为微秒单位
> blocktime默认没有,可以使用kscrash_crashCallback自定义传递给WCCrashBlockMonitorConfig的onAppendAdditionalInfoCallBack
> ex:
> void kscrash_crashCallback(const KSCrashReportWriter *writer) {
> writer->beginObject(writer, "BlockTime");
> writer->addFloatingPointElement(writer,"blockTime",threadBlockTime);
> writer->endContainer(writer);
> }
> crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;

请问BlockTime从什么地方获取

**Comment by SnailLife** [comment]
> > dev分支已经支持blocktime为微秒单位
> > blocktime默认没有,可以使用kscrash_crashCallback自定义传递给WCCrashBlockMonitorConfig的onAppendAdditionalInfoCallBack
> > ex:
> > void kscrash_crashCallback(const KSCrashReportWriter *writer) {
> > writer->beginObject(writer, "BlockTime");
> > writer->addFloatingPointElement(writer,"blockTime",threadBlockTime);
> > writer->endContainer(writer);
> > }
> > crashBlockConfig.onAppendAdditionalInfoCallBack = kscrash_crashCallback;
> 
> 通过这个方法 我们检测到的数据有卡顿 50s 70s 的，这个卡顿也太久了吧？

请问卡顿时间 是怎么拿到的 通过你之前说的代理 好像拿不到blocktime
