### ISSUE TITLE
iOS卡顿监控数据格式疑问

### ISSUE THREAD

**Issue by huakucha** [Tencent/matrix#367]
异常类型：matrix内部crash

手机型号：iPhone 16G77 arm64

手机系统版本：12.4

matrix版本：如: 0.5.1

问题描述：crash拿到堆栈

scm_reportUserExceptionSelfDefinePath (in EbikeMaintain) (KSCrashMonitor_User.c:72)

kscrash_reportUserExceptionWithSelfDefinedPath (in EbikeMaintain) (KSCrashC.c:305)

-[KSCrash reportUserException:reason:language:lineOfCode:stackTrace:logAllThreads:terminateProgram:dumpFilePath:dumpType:] (in EbikeMaintain) (KSCrash.m:497)

+[WCDumpInterface dumpReportWithReportType:withBlockTime:withExceptionReason:selfDefinedPath:] (in EbikeMaintain) (WCDumpInterface.mm:52)

+[WCDumpInterface dumpReportWithReportType:withBlockTime:withExceptionReason:] (in EbikeMaintain) (WCDumpInterface.mm:0)

-[WCBlockMonitorMgr dumpFileWithType:] (in EbikeMaintain) (WCBlockMonitorMgr.mm:0)

-[WCBlockMonitorMgr threadProc] (in EbikeMaintain) (WCBlockMonitorMgr.mm:444)

**Comment by huakucha** [comment]
只看到matrix内部函数的调用堆栈 看不到自己工程代码堆栈 crash的reason也未找到，还有一个疑问就是 我怎么通过产生的json，分辨出是crash 还是lag

**Comment by chzhij5** [comment]
json 里有 dump type ，通过 dump type 区分下。

**Comment by chzhij5** [comment]
> 异常类型：matrix内部crash
> 
> 手机型号：iPhone 16G77 arm64
> 
> 手机系统版本：12.4
> 
> matrix版本：如: 0.5.1
> 
> 问题描述：crash拿到堆栈
> 
> scm_reportUserExceptionSelfDefinePath (in EbikeMaintain) (KSCrashMonitor_User.c:72)
> 
> kscrash_reportUserExceptionWithSelfDefinedPath (in EbikeMaintain) (KSCrashC.c:305)
> 
> -[KSCrash reportUserException:reason:language:lineOfCode:stackTrace:logAllThreads:terminateProgram:dumpFilePath:dumpType:] (in EbikeMaintain) (KSCrash.m:497)
> 
> +[WCDumpInterface dumpReportWithReportType:withBlockTime:withExceptionReason:selfDefinedPath:] (in EbikeMaintain) (WCDumpInterface.mm:52)
> 
> +[WCDumpInterface dumpReportWithReportType:withBlockTime:withExceptionReason:] (in EbikeMaintain) (WCDumpInterface.mm:0)
> 
> -[WCBlockMonitorMgr dumpFileWithType:] (in EbikeMaintain) (WCBlockMonitorMgr.mm:0)
> 
> -[WCBlockMonitorMgr threadProc] (in EbikeMaintain) (WCBlockMonitorMgr.mm:444)

这不是 Crash 是 Lag。  Lag 是一次“假性”的 Crash。

**Comment by huakucha** [comment]
大致明白了 还有一个疑问啊 dump type为 EDumpType_BlockAndBeKilled 这种类型 触发的大概时机是怎样的啊？

**Comment by huakucha** [comment]
Lag 是一次“假性”的 Crash,我看到Crashed 为true的时候 展示的就是上述堆栈，lag会产生一组json（2个） 我需要做比较的两个堆栈 是哪个啊

**Comment by huakucha** [comment]
![image](https://user-images.githubusercontent.com/5646613/66555590-85d2bd00-eb81-11e9-83e0-70ba3746462f.png)
matrix版本：如: 0.5.1

**Comment by chzhij5** [comment]
@huakucha 因为是合并返回。 

上报时，同一类型的卡顿日志，会合并返回。  这个不是做对比用的，是不同卡顿日志。

**Comment by huakucha** [comment]
@chzhij5 你说的同一类型是根据dump type做合并的吗 那极端情况下 一次app使用可以积累很多这种怎么办？，能不能有参数让其不合并返回，因为后续你需要对其符号化也要遍历数组...

**Comment by huakucha** [comment]
吐槽一下 matrix的版本控制  tag 一会v 一会V 0.5.2版本 发布版本跟git上面的还不一样vV
