### ISSUE TITLE
iOS卡顿监控数据格式疑问

### ISSUE THREAD

**Issue by huakucha** [Tencent/matrix#375]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：app 运行时异常/编译异常

手机型号：ios 

手机系统版本：12.4.1

matrix版本：0.5.1

gradle版本：如: 3.0.0

问题描述：iOS卡顿监控json数据格式是以数组的形式存在
![image](https://user-images.githubusercontent.com/5646613/66882017-6e6d5700-effb-11e9-816c-4aad0718add0.png)


我的问题：数组的数量一定是2个吗，我理解的就是存在两个 做对比用...

**Comment by txfelixzhou** [comment]
麻烦更新一下图片的url，看不到图片内容

**Comment by huakucha** [comment]
![image](https://user-images.githubusercontent.com/5646613/66882061-90ff7000-effb-11e9-8b92-20beaf685d0a.png)

**Comment by huakucha** [comment]
https://github.com/Tencent/matrix/issues/367
这两个issues都是我提的 劳烦看一下367 这个描述更详尽

**Comment by chzhij5** [comment]
因为是合并返回。

上报时，同一类型的卡顿日志，会合并返回。
