### ISSUE TITLE
Cannot set the value of read-only property 'enable' for object of type com.tencent.matrix.trace.extension.MatrixTraceExtension.

### ISSUE THREAD

**Issue by devLiuGit** [Tencent/matrix#381]
异常类型：app 编译异常

matrix版本：如: 0.5.2 - 0.6.0

gradle版本：如: 2.14.1
Android gradle plugin : 2.2.3

问题描述 : 

Cannot set the value of read-only property 'enable' for object of type com.tencent.matrix.trace.extension.MatrixTraceExtension.

解决方案 : 
matrix/matrix-android/matrix-gradle-plugin/src/main/java/com/tencent/matrix/trace/extension/MatrixTraceExtension.java
实现所有字段的 get 方法即可.

这个类原来是 groovy 写的, 在 0.5.2 版本后改用 Java. 在低版本 gradle 会出现这个问题, 怀疑是 groovy 对 Java 字段访问的兼容问题.

临时解决方案, 更改上述类文件并上传到私有 maven 仓库.

**Comment by changelcai** [comment]
ok, you right
