### ISSUE TITLE
iOS被系统强杀的情况，会上报崩溃么？

### ISSUE THREAD

**Issue by zhilinli** [Tencent/matrix#391]
请问下，APP被系统强杀的情况下会上报么？怎么区分这种情况？

**Comment by chzhij5** [comment]
系统强杀有两种情况：
1、卡死被强杀，这个会有卡死卡顿上报（卡顿监控捕获的）；
参考这个：https://github.com/Tencent/matrix/wiki/Matrix-for-iOS-macOS-%E5%8D%A1%E9%A1%BF%E7%9B%91%E6%8E%A7%E5%8E%9F%E7%90%86#%E5%8D%A1%E6%AD%BB%E5%8D%A1%E9%A1%BF

2、爆内存被强杀，这个有内存监控。

还可以看一下这个应用重启类型分析的实现：
https://github.com/Tencent/matrix/blob/master/matrix/matrix-iOS/Matrix/Matrix/AppReboot/MatrixAppRebootAnalyzer.h
