### ISSUE TITLE
matrix目前已经有三个多月没发布正式版

### ISSUE THREAD

**Issue by SmallBlueWhale** [Tencent/matrix#393]
请问下，目前有进一步更新计划嘛？
想研究一下fps那一块的源码，看见dev是有在不停更新的，但是master已经停了，代码已经相对较旧，这样的话，dev分支是否可供直接使用，还是说有其它稳定的分之？

**Comment by chzhij5** [comment]
🤔

**Comment by txfelixzhou** [comment]
dev的分支是稳定的，master的分支是打tag需要用的，因为没有增加新的特性，所以没有发TAG

**Comment by SmallBlueWhale** [comment]
OK，谢谢回复，理解，我close了
