### ISSUE TITLE
Transform除了支持增量，是否可以支持一下并发，缓存

### ISSUE THREAD

**Issue by Leaking** [Tencent/matrix#40]
Transform处理class/jar对编译速度的影响还是比较明显的，从Android build gradle插件自带的几个transform看，大部分除了支持增量，还支持并发与缓存。

目前看MatrixTraceTransform只支持了增量，是否可以支持一下并发，缓存

**Comment by changelcai** [comment]
是的，这里应该要并发处理下，在有增量的情况下，缓存意义也不大。不过应该还能减少一次扫描class文件，可以提升插桩效率，下版本优化下这里。

**Comment by TellH** [comment]
> Transform处理class/jar对编译速度的影响还是比较明显的，从Android build gradle插件自带的几个transform看，大部分除了支持增量，还支持并发与缓存。
> 
> 目前看MatrixTraceTransform只支持了增量，是否可以支持一下并发，缓存

并发是指并发扫描Class文件吗

**Comment by Leaking** [comment]
> > Transform处理class/jar对编译速度的影响还是比较明显的，从Android build gradle插件自带的几个transform看，大部分除了支持增量，还支持并发与缓存。
> > 目前看MatrixTraceTransform只支持了增量，是否可以支持一下并发，缓存
> 
> 并发是指并发扫描Class文件吗

嗯

**Comment by angusHeZZ** [comment]
> Transform处理class/jar对编译速度的影响还是比较明显的，从Android build gradle插件自带的几个transform看，大部分除了支持增量，还支持并发与缓存。
> 
> 目前看MatrixTraceTransform只支持了增量，是否可以支持一下并发，缓存

Transform 目前支持gradle的建立cache和从cache恢复吗？
