### ISSUE TITLE
关于IOS卡顿堆栈的问题

### ISSUE THREAD

**Issue by pengcong06** [Tencent/matrix#401]
请教一下，卡顿监控的不是主线程的堆栈么，道理上最后上报的json数组里面每一项都应该是主线程的堆栈，为甚么上报上来的是很多个线程的呢，这样定位问题的时候如何知道哪个线程时主线程，是因为哪个操作卡了呢？
例如示例中的：
Thread 0:
0   libsystem_platform.dylib        0x0000000239a6e5ec 0x239a66000 + 34284            (_platform_memset)
1   libsystem_malloc.dylib          0x0000000239a2ea90 0x239a2d000 + 6800             (nanov2_allocate$VARIANT$mp)
2   libsystem_malloc.dylib          0x0000000239a2eeec 0x239a2d000 + 7916             (nanov2_calloc$VARIANT$mp)
3   libsystem_malloc.dylib          0x0000000239a3db74 0x239a2d000 + 68468            (malloc_zone_calloc)
4   libsystem_malloc.dylib          0x0000000239a3e3fc 0x239a2d000 + 70652            (calloc)
5   libdispatch.dylib               0x00000002398679b8 0x239839000 + 190904
6   libdispatch.dylib               0x000000023983ee60 0x239839000 + 24160
7   MatrixDemo                      0x00000001023bd568 0x10236c000 + 333160           (__52-[MatrixTester generateMainThreadBlockToBeKilledLog]_block_invoke)
8   libdispatch.dylib               0x00000002398996c8 0x239839000 + 394952
9   libdispatch.dylib               0x000000023989a484 0x239839000 + 398468
10  libdispatch.dylib               0x00000002398469a4 0x239839000 + 55716
11  CoreFoundation                  0x0000000239df1ce4 0x239d45000 + 707812
12  CoreFoundation                  0x0000000239decbac 0x239d45000 + 687020
13  CoreFoundation                  0x0000000239dec0e0 0x239d45000 + 684256           (CFRunLoopRunSpecific)
14  GraphicsServices                0x000000023c065584 0x23c05a000 + 46468            (GSEventRunModal)
15  UIKitCore                       0x0000000267180c00 0x266898000 + 9341952          (UIApplicationMain)
16  MatrixDemo                      0x000000010237a0a4 0x10236c000 + 57508            (main)
17  libdyld.dylib                   0x00000002398aabb4 0x2398aa000 + 2996

Thread 1:
0   MatrixDemo                      0x00000001023bd574 0x10236c000 + 333172           (__52-[MatrixTester generateMainThreadBlockToBeKilledLog]_block_invoke)
1   libdispatch.dylib               0x00000002398996c8 0x239839000 + 394952
2   libdispatch.dylib               0x000000023989a484 0x239839000 + 398468
3   libdispatch.dylib               0x000000023983d490 0x239839000 + 17552
4   libdispatch.dylib               0x0000000239849a18 0x239839000 + 68120
5   libdispatch.dylib               0x000000023984a2c0 0x239839000 + 70336
6   libsystem_pthread.dylib         0x0000000239a7d17c 0x239a71000 + 49532            (_pthread_wqthread)

Thread 2:
0   MatrixDemo                      0x00000001023bd574 0x10236c000 + 333172           (__52-[MatrixTester generateMainThreadBlockToBeKilledLog]_block_invoke)
1   libdispatch.dylib               0x00000002398996c8 0x239839000 + 394952
2   libdispatch.dylib               0x000000023989a484 0x239839000 + 398468
3   libdispatch.dylib               0x000000023983d490 0x239839000 + 17552
4   libdispatch.dylib               0x0000000239849a18 0x239839000 + 68120
5   libdispatch.dylib               0x000000023984a2c0 0x239839000 + 70336
6   libsystem_pthread.dylib         0x0000000239a7d17c 0x239a71000 + 49532            (_pthread_wqthread)

Thread 3:
0   libsystem_kernel.dylib          0x00000002399ebea4 0x2399d4000 + 97956            (mach_msg_trap)
1   libsystem_kernel.dylib          0x00000002399eb37c 0x2399d4000 + 95100            (mach_msg)
2   MatrixDemo                      0x000000010239f6ec 0x10236c000 + 210668           (handleExceptions)
3   libsystem_pthread.dylib         0x0000000239a7c25c 0x239a71000 + 45660
4   libsystem_pthread.dylib         0x0000000239a7c1bc 0x239a71000 + 45500            (_pthread_start)

Thread 4:
0   libsystem_kernel.dylib          0x00000002399ebea4 0x2399d4000 + 97956            (mach_msg_trap)
1   libsystem_kernel.dylib          0x00000002399eb37c 0x2399d4000 + 95100            (mach_msg)
2   libsystem_kernel.dylib          0x00000002399e74ec 0x2399d4000 + 79084            (thread_suspend)
3   MatrixDemo                      0x000000010239f6b4 0x10236c000 + 210612           (handleExceptions)
4   libsystem_pthread.dylib         0x0000000239a7c25c 0x239a71000 + 45660
5   libsystem_pthread.dylib         0x0000000239a7c1bc 0x239a71000 + 45500            (_pthread_start)
.
.
.
Thread 10:
0   libsystem_kernel.dylib          0x00000002399f7b9c 0x2399d4000 + 146332           (__workq_kernreturn)
1   libsystem_pthread.dylib         0x0000000239a7d1c0 0x239a71000 + 49600            (_pthread_wqthread)

这里一共有10个线程的堆栈上报，如何确定是哪个导致卡顿的呢？

**Comment by chzhij5** [comment]
Thread 0 即是主线程，卡顿关注主线程。

上报的是当前的整个应用的现场快照；上报其他线程堆栈，可以方便定位死锁等类型的问题。

**Comment by CrazyZombies** [comment]
> Thread 0 即是主线程，卡顿关注主线程。
> 
> 上报的是当前的整个应用的现场快照；上报其他线程堆栈，可以方便定位死锁等类型的问题。

子线程的快照采集时机是啥时候，50ms 采集主线程堆栈的时候，会同时采集所有线程的堆栈吗？

**Comment by chzhij5** [comment]
“子线程快照”，“快照”，生成卡顿堆栈日志的时候。

不会采集所有线程。
