### ISSUE TITLE
Android sample 编译异常

### ISSUE THREAD

**Issue by qingguoguo** [Tencent/matrix#404]
异常类型：编译异常
matrix版本： 0.6.0
gradle版本： 5.1.1

sample是否还有维护更新啊！跑起来各种问题
这两行依赖拉不下来，得注释掉：
    //compile group: "com.tencent.matrix", name: "matrix-thread-canary", version: MATRIX_VERSION, changing: true
    //apkCheckerDependency group: "com.tencent.matrix", name: "matrix-apk-canary", version:MATRIX_VERSION, changing: true

run还有空指针：
java.lang.NullPointerException: Cannot invoke method getAbsolutePath() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)

建了个Android沟通交流群，方便大家交流：343816731

**Comment by txfelixzhou** [comment]
抱歉，是我们版本管理上的问题，对外开源的代码混入了内部还不成熟的模块依赖。我们将sample变成干净可用

**Comment by txfelixzhou** [comment]
请用最新master

**Comment by Qiang11** [comment]
> 异常类型：编译异常
> matrix版本： 0.6.0
> gradle版本： 5.1.1
> 
> sample是否还有维护更新啊！跑起来各种问题
> 这两行依赖拉不下来，得注释掉：
> //compile group: "com.tencent.matrix", name: "matrix-thread-canary", version: MATRIX_VERSION, changing: true
> //apkCheckerDependency group: "com.tencent.matrix", name: "matrix-apk-canary", version:MATRIX_VERSION, changing: true
> 
> run还有空指针：
> java.lang.NullPointerException: Cannot invoke method getAbsolutePath() on null object
> at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
> at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
> at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
> 
> 建了个Android沟通交流群，方便大家交流：343816731

你这群不让加了  唉  也是遇到这些问题
