### ISSUE TITLE
什么时候会加上 Android 的耗电监控呢？有没有这方面的计划？

### ISSUE THREAD

**Issue by crazy1235** [Tencent/matrix#405]
什么时候会加上 Android 的耗电监控呢？有没有这方面的计划？

**Comment by txfelixzhou** [comment]
这块计划是有的，而且在很早的时候我们就关注了这一块功能（你可在feature/dev中可见batterycanary这个模块），但遗憾的是，目前这块功能还不够准确，所以暂时没有开源。
