### ISSUE TITLE
iOS监测数据上报后，如何归类？

### ISSUE THREAD

**Issue by RainesGit** [Tencent/matrix#418]
上传至后台后如何将同一方法引起的问题进行归类呢？

**Comment by chzhij5** [comment]
微信大致的归类方法：

1、Crash 用 Crash 线程归类；第一层取 Crash 线程应用（微信）的第一个堆栈，第二层取 Crash 原因，第三层用 LR ；

2、卡顿根据主线程堆栈（优先用耗时堆栈提取出来的主线程堆栈）归类，第一层取应用的前三个堆栈，第二层取前五堆栈。
（如果主线程是 main 函数，第二层取整个主线程堆栈的前五个堆栈）
