### ISSUE TITLE
iOS arm64e crash 堆栈日志堆栈只有指令地址且指令地址超大

### ISSUE THREAD

**Issue by huakucha** [Tencent/matrix#420]
异常类型：crash 日志采集异常

手机型号：iPhone

手机系统版本：10.0.1

matrix版本：如: 0.5.2

问题描述：iOS arm64e crash 堆栈日志出现如下问题

堆栈/日志：
![image](https://user-images.githubusercontent.com/5646613/69696479-c333df80-111a-11ea-823f-daece54ece67.png)

**Comment by chzhij5** [comment]
苹果在 arm64e 架构（Apple A12 芯片）引进了 PAC 机制，指令地址的高位被用来做校验。

参考：https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication

在解析指令的时候，需要将高位抹去，只使用 64 位中低位的 36 位。

伪代码：

new_instruction = instruction & 0x0000000fffffffff

**Comment by chzhij5** [comment]
找到一篇不错的文章：https://justinyan.me/post/4129

**Comment by czlitony** [comment]
这个crash最终是怎么解决的
