### ISSUE TITLE
堆栈定位的卡顿地方和后面给的符号为什么对不上?

### ISSUE THREAD

**Issue by hrstruggle1** [Tencent/matrix#423]
hi:

卡顿类型: dump_type = 2010

举个例子

0   libsystem_kernel.dylib          0x0000000199ee8a2c 0x199ec1000 + 162348           (kevent_id)
1   libdispatch.dylib               0x0000000199dbf63c 0x199d9f000 + 132668
2   libdispatch.dylib               0x0000000199daea90 0x199d9f000 + 64144
3   libdispatch.dylib               0x0000000199dae698 0x199d9f000 + 63128
4   XXXX                            0x000000010552fd50 0x102414000 + 51494224         (_ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE)
5   CoreFoundation                  0x000000019a14b9e0 0x199fc9000 + 1583584
6   CoreFoundation                  0x0000000199fcbca0 0x199fc9000 + 11424
7   XXXX                            0x000000010552e850 0x102414000 + 51488848         (_ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE)
8   XXXX                            0x000000010552a770 0x102414000 + 51472240         (_ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE)
9   XXXX                            0x0000000105524054 0x102414000 + 51445844         (_ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE)
10  XXXX                            0x0000000105521e44 0x102414000 + 51437124         (_ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE)

比如第 4 行: 我用 atos 符号化 0x000000010552fd50 0x102414000 + 51494224 后指向的堆栈 和 后面给的 _ZN5GraphIfffE21process_source_orphanEPNS0_4nodeE 为什么对不上呢?

完全是两个不相关的业务场景, 请问我该以什么为准呢?

**Comment by chzhij5** [comment]
以 atos 为准。

从设备上上传的符号是，在运行时尝试解析的，取的是离指令地址最近的符号；如果应用的符号已经进行了裁剪，那么会设备解析出来的符号会错得很离谱。

当机自解析在一种情况下很有用，debug 编包自用，可执行文件不裁掉调试符号，使用过程中 Crash 的日志都能有符号。

关于符号可以参考：
https://github.com/Tencent/matrix/wiki/About-macOS-&-iOS-symbol
