### ISSUE TITLE
iOS的handleSuspend怎么用？

### ISSUE THREAD

**Issue by titman** [Tencent/matrix#441]
1. 看matrix本身没有调用这个方法，是依靠接入方自行调用吗？
2. 如果接入方调用的话需要在什么时机调？
3. 如果不需要调的话，会有后台被挂起后被误认为卡顿吗？
感谢解答！

**Comment by chzhij5** [comment]
1、是的，需要接入方自行调用，因为 suspend 这个时机和业务强相关，matrix 里无法内置；

2、调用实际：

在调用这个方法，交回后台权限之后调用一下
- (UIBackgroundTaskIdentifier)beginBackgroundTaskWithExpirationHandler:(void(^ __nullable)(void))handler  API_AVAILABLE(ios(4.0)) NS_REQUIRES_SUPER;

2、不调用的话，在某些时间点，suspend的时间被算进了卡顿时长，很容易在后台出现误判。
