### ISSUE TITLE
关于微信C++内存泄漏检测工具开源

### ISSUE THREAD

**Issue by sevenmine** [Tencent/matrix#45]
前段时间在微信公众号中看到过微信内存优化的文章，里面提到目前微信有一套检测Native内存泄漏的工具，性能开销很小检测效率高，不只是否能开源，以解决目前Android上Native内存泄漏定位困难的处境。谢谢

**Comment by astrozhou** [comment]
C++内存检测工具还需要一些时间来打磨，还待定
