### ISSUE TITLE
耗电堆栈解析

### ISSUE THREAD

**Issue by KT9999** [Tencent/matrix#470]
stack_info:
    36 __semwait_signa (libsystem_kernel.dylib + 89724) [0x000000001c441e7c]
      36 uslee (libsystem_c.dylib + 41021) [0x000000001c39603d]
        36 _Z37__memory_logging_event_writing_threadP (LDemoTest + 9581333) [0x000000000094f315]
          36 &lt;redacted (libsystem_pthread.dylib + 14651) [0x000000001c4f893b]
            36 _pthread_star (libsystem_pthread.dylib + 14429) [0x000000001c4f885d]
    18 &lt;redacted (libsystem_malloc.dylib + 10188) [0x000000001c47a7cc]
      18 malloc_zone_callo (libsystem_malloc.dylib + 14183) [0x000000001c47b767]
        18 callo (libsystem_malloc.dylib + 14033) [0x000000001c47b6d1]
          18 class_createInstanc (libobjc.A.dylib + 71145) [0x000000001bf055e9]
            18 &lt;redacted (CoreFoundation + 1050473) [0x000000001cc79769]
              18 &lt;redacted (CoreFoundation + 65477) [0x000000001cb88fc5]
                18 &lt;redacted (CoreFoundation + 55305) [0x000000001cb86809]
                  18 &lt;redacted (CoreFoundation + 96769) [0x000000001cb90a01]
                    18 &lt;redacted (CoreFoundation + 301443) [0x000000001cbc2983]
                      18 -[JSONModel __doesDictionary:matchModelWithKeyMapper:error: (LDemoTest + 7052645) [0x00000000006e5d65]
                        18 -[JSONModel initWithDictionary:error: (LDemoTest + 7052095) [0x00000000006e5b3f]
                          18 +[JSONModel arrayOfModelsFromDictionaries:error: (LDemoTest + 7080987) [0x00000000006ecc1b]
                            18 -[JSONModel __transform:forProperty:error: (LDemoTest + 7071355) [0x00000000006ea67b]
                              18 -[JSONModel __importDictionary:withKeyMapper:validation:error: (LDemoTest + 7059563) [0x00000000006e786b]
                                18 -[JSONModel initWithDictionary:error: (LDemoTest + 7052263) [0x00000000006e5be7]
                                  18 +[JSONModel arrayOfModelsFromDictionaries:error: (LDemoTest + 7080987) [0x00000000006ecc1b]
                                    18 -[JSONModel __transform:forProperty:error: (LDemoTest + 7071355) [0x00000000006ea67b]
                                      18 -[JSONModel __importDictionary:withKeyMapper:validation:error: (LDemoTest + 7059563) [0x00000000006e786b]
                                        18 -[JSONModel initWithDictionary:error: (LDemoTest + 7052263) [0x00000000006e5be7]
                                          18 +[JSONModel arrayOfModelsFromDictionaries:error: (LDemoTest + 7080987) [0x00000000006ecc1b]
                                            18 -[JSONModel __transform:forProperty:error: (LDemoTest + 7071355) [0x00000000006ea67b]
                                              18 -[JSONModel __importDictionary:withKeyMapper:validation:error: (LDemoTest + 7059563) [0x00000000006e786b]
                                                18 -[JSONModel initWithDictionary:error: (LDemoTest + 7052263) [0x00000000006e5be7]
                                                  18 -[JSONModel initWithData:error: (LDemoTest + 7050889) [0x00000000006e5689]
                                                    18 -[LDemoTestM getData: (LDemoTest + 5686023) [0x0000000000598307]
                                                      18 -[LDemoTestYY upload: (LDemoTest + 4533361) [0x000000000047ec71]

以上是用python格式化后的耗电堆栈，请问下这种格式的如何符号化解析呢？麻烦提供下思路，谢谢。

**Comment by chzhij5** [comment]
可以参考一下这篇 https://github.com/Tencent/matrix/wiki/About-macOS-&-iOS-symbol 

至于符号如何解析，搜索下关键词 atos + iOS 有很多相关文章， 使用 uuid + dsym 即可进行解析。
