### ISSUE TITLE
iOS 的 WCMemoryStatPlugin 是否 Start 交由使用者控制

### ISSUE THREAD

**Issue by ZenonHuang** [Tencent/matrix#486]
## 现在的情况

如题,在 iOS 的内存检查插件中，WCMemoryStatPlugin 的 `Start` 方法，有在 `Debug` 下就直接 return 的逻辑:
```objc
- (void)start
{
    if ([MatrixDeviceInfo isBeingDebugged]) {
        MatrixDebug(@"app is being debugged, cannot start memstat");
        return;
    }
   ...
}
```

## 希望

期望可以将是否 Start 的条件交给使用者自己去控制，而不是在 Debug 下直接就无法开启。

**Comment by xuyeewang** [comment]
调试中关闭内存监控，主要是考虑到内存监控此时没有可视化的数据参考，对于定位问题意义不大。
你可以试试直接注释掉上述代码，看看能不能帮你解决问题。

**Comment by aiquantong** [comment]
// Check whether there's any analysis tool process logging memory.
    if (is_debug_tools_running //|| is_being_debugged()
        ) {
        return MS_ERRC_ANALYSIS_TOOL_RUNNING;
    }
	
	logging_is_enable = true;

//|| is_being_debugged() 需要需要注释掉，否则debug 启动不了
