### ISSUE TITLE
使用Resource Canary，如何拿到分析阶段的结果？

### ISSUE THREAD

**Issue by dengjiaming** [Tencent/matrix#49]
问题描述：客户端生成Hprof文件后，如何拿到分析结果呢？

**Comment by txfelixzhou** [comment]
![image](https://user-images.githubusercontent.com/15136816/50582364-0818ad00-0e9d-11e9-9537-041a111409b5.png)
在DumpStorageManager.java中这一段有定义hprof的存储路径: /sdcard/matrix_resource/

**Comment by dengjiaming** [comment]
在/data/data/sample.tencent.matrix/cache/和 /sdcard都没有找到matrix_resource文件夹，7.0，8.0，9.0的机型都没有找到

**Comment by helloworldgithub** [comment]
存储路径为/storage/emulated/0/Android/data/应用包名/cache/matrix_resource
