### ISSUE TITLE
完善对于 methodMapping.txt 文件内容的解释文档

### ISSUE THREAD

**Issue by Airsaid** [Tencent/matrix#512]
异常类型：无关

手机型号：无关
手机系统版本：无关

matrix版本：0.6.5

gradle版本：3.5.3

问题描述：

methodMapping.txt 文件中每行有三个数据，分别用 , 号分隔，每个又代表什么意思呢？没有文档上写清楚这些，能否完善下文档？
```
1,1,com.bytedance.device_register.i$1 run ()V
2,1,androidx.fragment.app.BackStackRecord toString ()Ljava.lang.String;
3,1,androidx.fragment.app.BackStackRecord dump (Ljava.lang.String;Ljava.io.PrintWriter;)V
4,131073,androidx.room.DatabaseConfiguration isMigrationRequiredFrom (I)Z
5,1,androidx.room.DatabaseConfiguration isMigrationRequired (II)Z
......
```

堆栈/日志：无关

**Comment by aishang5wpj** [comment]
![image](https://user-images.githubusercontent.com/7829473/103280973-a0a28300-4a0c-11eb-8de1-8c8642e8e563.png)

https://github.com/Tencent/matrix/wiki/Matrix-Android-TraceCanary

**Comment by hero0812** [comment]
> ![image](https://user-images.githubusercontent.com/7829473/103280973-a0a28300-4a0c-11eb-8de1-8c8642e8e563.png)
> 
> https://github.com/Tencent/matrix/wiki/Matrix-Android-TraceCanary

这个图好像解答不了他这个问题啊，methodMapping.txt 文件中每行有三个数据，分别用逗号分隔，第一个应该是methodid，第三个应该是方法所属类和方法签名，第二个数字代表什么意思？

**Comment by William353** [comment]
第二个数字表示方法权限修饰符，常见的值为ACC_PUBLIC = 1; ACC_PRIVATE = 2;ACC_PROTECTED = 4; ACC_STATIC = 8等等。
