### ISSUE TITLE
是否考虑增加app线上的耗电量统计情况检测

### ISSUE THREAD

**Issue by JessonYue** [Tencent/matrix#52]
是否考虑增加app线上的耗电量统计情况检测？我看目前开源的apm系统没有做这方面的检测，但是线上需求也是有的。

**Comment by hfutgl** [comment]
耗电量统计现在代码比较少，我是自己修改安卓系统Settings里统计模块来搞的，这个和安卓版本强相关

**Comment by pphdsny** [comment]
> 电量这块我们一直测试中，当前效果不达预期，所以没有跟着此次开源，后续会开源出来

耗电量这块是否有新进展
