### ISSUE TITLE
ApkChecker ApkResourceDecoder.class.getResourceAsStream("android/android-framework.jar")返回null

### ISSUE THREAD

**Issue by xialonghua** [Tencent/matrix#53]
ApkChecker 只有-manifest的时候这一行ApkResourceDecoder.class.getResourceAsStream("android/android-framework.jar")返回null报错

**Comment by xialonghua** [comment]
改成绝对路径好了

**Comment by jqctop1** [comment]
@xialonghua 是直接运行的jar吗？

**Comment by xialonghua** [comment]
> @xialonghua 是直接运行的jar吗？

AS里直接run的
![Uploading image.png…]()

**Comment by jqctop1** [comment]
恩，as直接run应该是不太一样的，改成绝对路径的话打成jar包就无法访问了

**Comment by xialonghua** [comment]
> 恩，as直接run应该是不太一样的，改成绝对路径的话打成jar包就无法访问了

嗯了解
