### ISSUE TITLE
源码中日志调用问题

### ISSUE THREAD

**Issue by andasl** [Tencent/matrix#536]
MatrixLog.w(TAG, "caught unexpected exception when unbind drawables.", thr);
后面的thr没有得到输出
看了下w()中的代码
            matrixLogImp.w(tag, msg, obj);

String log = (params == null || params.length == 0) ? format : String.format(format, params);
            android.util.Log.w(tag, log);

这一行日志的format没有带参数

**Comment by gryamy** [comment]
请参考一下 String.format[https://developer.android.com/reference/java/lang/String#format(java.lang.String,%20java.lang.Object...)] 的用法
