### ISSUE TITLE
线上环境怎么使用

### ISSUE THREAD

**Issue by zzzzhongzhen** [Tencent/matrix#544]
怎么拿到线上监测到的数据？

**Comment by microrain0130** [comment]
这只是个采集工具，你还要做上报、数据分析、展示的后续动作……

**Comment by chris-power** [comment]
这只是个采集工具，你还要做上报、数据分析、展示的后续动作……

**Comment by zzzzhongzhen** [comment]
> 分析
ok
iOS是需要重新启动应用程序才拿得到监控数据吗，还是我使用的不对

**Comment by chzhij5** [comment]
是的，目前没有提供后台分析展示。
