### ISSUE TITLE
慢函数的堆栈如何解读，现在是一堆数字

### ISSUE THREAD

**Issue by helloworldgithub** [Tencent/matrix#57]
如题

**Comment by txfelixzhou** [comment]
这个数字是我们一个包/类/方法的的映射值，目的是方便聚合和降低数据大小，文件名为后缀名.methodmap, 在Sample中可以自己配置存入的路径，如下图
![image](https://user-images.githubusercontent.com/15136816/50634573-14c6ff00-0f8a-11e9-9cec-46cc4b6e60e7.png)

**Comment by zhmy** [comment]
能具体给个分析的例子吗？另外debug下是不是可以直接把堆栈打出来，或者增加个工具做转换

**Comment by txfelixzhou** [comment]
请查看 Wiki, [[Matrix 输出内容的含义解析](https://github.com/Tencent/matrix/wiki/Matrix--%E8%BE%93%E5%87%BA%E5%86%85%E5%AE%B9%E7%9A%84%E5%90%AB%E4%B9%89%E8%A7%A3%E6%9E%90)] 找到"慢函数"

至于数字转堆栈，有了methodmap， 应该很简单的，写个python脚本就可以了
