### ISSUE TITLE
0.8.1报错

### ISSUE THREAD

**Issue by mrkyee** [Tencent/matrix#571]
demo里MATRIX_VERSION是0.8.1报错。
![image](https://user-images.githubusercontent.com/35887438/114397564-66cb4600-9bd1-11eb-930e-97a3088ba51a.png)

**Comment by Yves0** [comment]
https://repo.maven.apache.org/maven2/com/tencent/matrix/matrix-resource-canary-android/0.8.1/matrix-resource-canary-android-0.8.1.pom

**Comment by mrkyee** [comment]
> 浏览器中能否访问这两个 url 呢？
> https://repo.maven.apache.org/maven2/com/tencent/matrix/matrix-resource-canary-android/0.8.1/matrix-resource-canary-android-0.8.1.pom
> https://repo.maven.apache.org/maven2/com/tencent/matrix/matrix-gradle-plugin/0.8.1/matrix-gradle-plugin-0.8.1.pom

前面我重跑了一下项目，可以下载下来了
