### ISSUE TITLE
请问Resource Canary中的dump mode SILENCE_DUMP和NO_DUMP有什么区别

### ISSUE THREAD

**Issue by mrkyee** [Tencent/matrix#572]
我看源码好像这两种上报方式都做了相同的事情，请问他们真正的区别在哪？
![image](https://user-images.githubusercontent.com/35887438/114492562-65d6fa80-9c4b-11eb-901e-348eb26f8d75.png)
### 
![image](https://user-images.githubusercontent.com/35887438/114492590-71c2bc80-9c4b-11eb-9b82-8374a505c1f8.png)

**Comment by Yves0** [comment]
不同的 dump mode 对应不同的策略，SILENCE_DUMP 是在息屏之后 dump hprof 解析并上报引用链，NO_DUMP 顾名思义是只报一下泄漏不 dump hprof。

看你截图的这份代码比较旧了，是通过旁路 onLeak callback 回去处理的，现在 SILENCE_DUMP 的策略整合进来 Matrix 了，可以看下最新 master 的实现

**Comment by mrkyee** [comment]
> 不同的 dump mode 对应不同的策略，SILENCE_DUMP 是在息屏之后 dump hprof 解析并上报引用链，NO_DUMP 顾名思义是只报一下泄漏不 dump hprof。
> 
> 看你截图的这份代码比较旧了，是通过旁路 onLeak callback 回去处理的，现在 SILENCE_DUMP 的策略整合进来 Matrix 了，可以看下最新 master 的实现

但是我看了一下，我clone的就是master上的代码。但是demo里的是0.8.1下不下来，改成里0.8.0

**Comment by Yves0** [comment]
@mrkyee 现在应该可以了，0.8.1 同步 publish 到 maven central 了。另外 fetch/pull 看一下你的代码是不是最新的呢？最新代码跟截图中的已经不一样了哦~

**Comment by mrkyee** [comment]
> @mrkyee 现在应该可以了，0.8.1 同步 publish 到 maven central 了。另外 fetch/pull 看一下你的代码是不是最新的呢？最新代码跟截图中的已经不一样了哦~

OK我试试
