### ISSUE TITLE
sample-Android 运行不了  

### ISSUE THREAD

**Issue by Qiang11** [Tencent/matrix#573]
A problem occurred configuring root project 'sample-android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.tencent.matrix:matrix-gradle-plugin:0.8.1.
     Searched in the following locations:
       - file:/D:/IDEA/apache-maven-3.6.3-bin/LocalWarehouse/com/tencent/matrix/matrix-gradle-plugin/0.8.1/matrix-gradle-plugin-0.8.1.pom
       - https://dl.google.com/dl/android/maven2/com/tencent/matrix/matrix-gradle-plugin/0.8.1/matrix-gradle-plugin-0.8.1.pom
       - https://repo.maven.apache.org/maven2/com/tencent/matrix/matrix-gradle-plugin/0.8.1/matrix-gradle-plugin-0.8.1.pom
       - https://jcenter.bintray.com/com/tencent/matrix/matrix-gradle-plugin/0.8.1/matrix-gradle-plugin-0.8.1.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Qiang11** [comment]
sample里面是MATRIX_VERSION=0.8.1改成MATRIX_VERSION=0.8.0就可以了

**Comment by Qiang11** [comment]
sample里面是MATRIX_VERSION=0.8.1改成MATRIX_VERSION=0.8.0就可以了

**Comment by Yves0** [comment]
see #571

**Comment by Yves0** [comment]
如果下载不了的话，可以在 matrix-android 目录下执行 `./gradlew publishToMavenLocal`，然后将 sample 中的 MATRIX_VERSION 更改为 matrix-android/gradle.properties 中定义的版本号加 `-SNAPSHOT` 后缀
