### ISSUE TITLE
taskDescription：Unzip the apk to dest path

### ISSUE THREAD

**Issue by mmmssy** [Tencent/matrix#58]
命令：java -jar matrix-apk-canary-0.4.7.jar --apk ./app-debug.apk --format mm.json
得到的结果是apk中包含的文件按类型统计，得到的json结果中
apk的total-size为3668342，而各类文件(.so,.dex,.arsc......)的total-size总和为3603336，小于apk的total-size，这是因为？不应该是等于apk的total-size吗？

**Comment by jqctop1** [comment]
不能这样直接去等价吧？又不是二进制文件，zip文件肯定会多一些信息来保存这个zip文件的结构啊

**Comment by mmmssy** [comment]
> 不能这样直接去等价吧？又不是二进制文件，zip文件肯定会多一些信息来保存这个zip文件的结构啊
那为什么.so文件的total-size就是所有.so文件的entry-size之和
{
      "suffix": ".so",
      "total-size": 1953404,
      "files": [
        {
          "entry-name": "lib/armeabi-v7a/libSqliteLint-lib.so",
          "entry-size": 332587
        },
        {
          "entry-name": "lib/armeabi-v7a/libio-canary.so",
          "entry-size": 236285
        },
        {
          "entry-name": "lib/armeabi/libSqliteLint-lib.so",
          "entry-size": 336985
        },
        {
          "entry-name": "lib/armeabi/libio-canary.so",
          "entry-size": 240989
        },
        {
          "entry-name": "lib/x86/libSqliteLint-lib.so",
          "entry-size": 472914
        },
        {
          "entry-name": "lib/x86/libio-canary.so",
          "entry-size": 333644
        }
      ]
}

**Comment by jqctop1** [comment]
so的total-size就是各个so文件的累加，而apk的total-size其实apk文件的大小

**Comment by mmmssy** [comment]
又回到问题本身，那为什么apk的total-size不等于所有类型文件大小之和呢
