### ISSUE TITLE
iOS在崩溃后，json文件生成完成有回调方法吗？

### ISSUE THREAD

**Issue by shijinliang** [Tencent/matrix#584]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```
异常类型：崩溃回调

手机型号：iPhone

手机系统版本：

matrix版本：0.6.7

问题描述：iOS触发崩溃后，json文件写入完成，此时想尝试做一下上报，现在没有找到json写入完成的回调

堆栈/日志：
1. 如是编译异常，请在执行 gradle 命令时，加上 --stacktrace;
2. 日志我们需要过滤" Matrix. "关键字;
```

**Comment by chzhij5** [comment]
https://github.com/Tencent/matrix/blob/603b8eed9c2e342aa33fc35884f0d4518d1a2786/matrix/matrix-iOS/Matrix/WCCrashBlockMonitor/CrashBlockPlugin/WCCrashBlockMonitorConfig.h#L53

这个接口了解下。

**Comment by shijinliang** [comment]
@chzhij5 谢谢回复，看了下源码，`kscm_handleSignal(&ksTmpSingal);`这个地方会回调一下。

初始化config的时候，设置上回调可以使用

```
// 回调
void kscrash_sentryHandleSignal(siginfo_t *info) {
    
}
```

```
// 初始化config
crashBlockConfig.onHandleSignalCallBack = kscrash_sentryHandleSignal;
```
