### ISSUE TITLE
关于内存泄漏检测的疑惑。

### ISSUE THREAD

**Issue by Caij** [Tencent/matrix#585]
![image](https://user-images.githubusercontent.com/8597839/118393003-34e54d80-b66f-11eb-8f94-06ba2d8f8e7b.png)
之前看过wiki内存泄漏检测机制的优化，觉得很有道理。增加一个一定能被回收的“哨兵”对象，用来确认系统确实进行了GC
直接通过WeakReference.get()来判断对象是否已被回收，避免因延迟导致误判。

**但是发现代码中已经注释掉了，改为三次GC来代替。  这个其中是遇到什么坑才改成这样吗？**

**Comment by Yves0** [comment]
有可能出现即使多次触发了 gc (通过 Activity 的 WeakReference 检查确定发生了 gc)，但“哨兵”对象一直没有被回收的情况，可能是没有触发 full gc。这会导致有些泄漏无法被检测到，遇到的极端情况是所有泄漏判定都被哨兵挡住了。暂时没有找到更好的代替方案，只能靠增加触发 gc 的时机和检测次数来减少误判。
我们使用的默认策略是在前台 1min 检查一次，累计检查 10 次依然没有回收才判定为泄漏。

**Comment by Caij** [comment]
了解了  ths
