### ISSUE TITLE
matrix-trace-canary模块com.tencent.matrix.util.DeviceUtil.java类中getLevel方法有2个逻辑问题

### ISSUE THREAD

**Issue by lanlianhuashi** [Tencent/matrix#586]
public static LEVEL getLevel(Context context) {
        if (null != sLevelCache) {
            return sLevelCache;
        }
        long start = System.currentTimeMillis();
        long totalMemory = getTotalMemory(context);
        int coresNum = getNumOfCores();
        MatrixLog.i(TAG, "[getLevel] totalMemory:%s coresNum:%s", totalMemory, coresNum);
        if (totalMemory >= 8 * 1024 * MB) {
            sLevelCache = LEVEL.BEST;
        } else if (totalMemory >= 6 * 1024 * MB) {
            sLevelCache = LEVEL.HIGH;
        } else if (totalMemory >= 4 * 1024 * MB) {
            sLevelCache = LEVEL.MIDDLE;
        } else if (totalMemory >= 2 * 1024 * MB) { //1处
            if (coresNum >= 4) {
                sLevelCache = LEVEL.MIDDLE;
            } else if (coresNum >= 2) { //2处
                sLevelCache = LEVEL.LOW;
            } else if (coresNum > 0) { //3处
                sLevelCache = LEVEL.LOW;
            }
        } else if (0 <= totalMemory && totalMemory < 1024 * MB) { //4处
            sLevelCache = LEVEL.BAD;
        } else {//5处
            sLevelCache = LEVEL.UN_KNOW;
        }

        MatrixLog.i(TAG, "getLevel, cost:" + (System.currentTimeMillis() - start) + ", level:" + sLevelCache);
        return sLevelCache;
    }
该方法存2个问题：
问题1、由方法的第1处、4处可知，totalMemory[1G,2G)这个区间被漏掉了，落在了5处，所得结果为LEVEL.UN_KNOW，这样明显不太合理。
问题2、由方法的2处和3处可知，sLevelCache均为LEVEL.LOW，那为什么还要分成2个分支呢？

**Comment by gryamy** [comment]
Fixed in 2.0 beta. #615
