### ISSUE TITLE
如何定位到影响帧率的地方，现在看起来只是展示帧率功能

### ISSUE THREAD

**Issue by helloworldgithub** [Tencent/matrix#59]
如题

**Comment by txfelixzhou** [comment]
输出字段“Scene”的含义就是出现掉帧所有的Activity 
请查看Wiki中关于帧率输出内容的解释，[帧率](https://github.com/Tencent/matrix/wiki/Matrix--%E8%BE%93%E5%87%BA%E5%86%85%E5%AE%B9%E7%9A%84%E5%90%AB%E4%B9%89%E8%A7%A3%E6%9E%90#%E5%B8%A7%E7%8E%87)
