### ISSUE TITLE
关于 FrameTracer 计算帧率和掉帧数的疑惑

### ISSUE THREAD

**Issue by AliMaster** [Tencent/matrix#593]
`UIThreadMonitor`中在  Main Looper 中每个消息的结束时调用 `dispatchEnd`方法，`dispatchEnd` 中会调用 `observer.doFrame`方法，而 `FrameTracer` 作为 `observer` 的实现类，其 `doFrame`方法中，计算了掉帧数，并在 `FPSCollector`中进行了按场景收集。

```java
//FrameTracer#notifyListener
final long jiter = endNs - intendedFrameTimeNs;
final int dropFrame = (int) (jiter / frameIntervalNs);
```
追踪此处计算掉帧数所用的时间差 `endNs` 和 `intendedFrameTimeNs` ，并非常规理解的两次垂直同步信号的时间差；`endNs` 为Main Looper 中消息结束的时间，`intendedFrameTimeNs` 在非垂直同步信号时，是 Main Looper 中该消息开始的时间，否则为 垂直信号时间。

```java
//UIThreadMonitor#dispatchEnd
long startNs = token;
        long intendedFrameTimeNs = startNs;
        if (isVsyncFrame) {
            doFrameEnd(token);
            intendedFrameTimeNs = getIntendedFrameTimeNs(startNs);
        }

long endNs = System.nanoTime();
```

假如两次垂直同步信号之间执行了多个主线程任务消息，且耗时都极短，那在 `FPSCollector` 中计算掉帧次数，掉帧程度分布次数和帧总耗时等都是错误的，最终会造成整体 FPS 偏高的现象。

```java
//FrameCollectItem#collect
void collect(int droppedFrames) {
            float frameIntervalCost = 1f * UIThreadMonitor.getMonitor().getFrameIntervalNanos()
                    / Constants.TIME_MILLIS_TO_NANO;
            sumFrameCost += (droppedFrames + 1) * frameIntervalCost;
            sumDroppedFrames += droppedFrames;
            sumFrame++;
            if (droppedFrames >= frozenThreshold) {
                dropLevel[DropStatus.DROPPED_FROZEN.index]++;
                dropSum[DropStatus.DROPPED_FROZEN.index] += droppedFrames;
            } 
        ……
        }
        void report() {
            float fps = Math.min(60.f, 1000.f * sumFrame / sumFrameCost);
            MatrixLog.i(TAG, "[report] FPS:%s %s", fps, toString());
     ……
    }
```

举例: 通过下面的代码在 sample android 的 `TestTraceMainActivity` 中在 onCreate 中 持续向 MainLooper 发送空消息，可以发现界面没有任何刷新时变动时，FPS 和 掉帧程度分布在持续累计计算

```java
//TestTraceMainActivity
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
    ……
    mHandler.post(mRunnable);
  }
  
  Handler mHandler = new Handler();
  Runnable mRunnable = new Runnable() {
      @Override
      public void run() {
          mHandler.postDelayed(this,100);
      }
  };

```
翻 Tag 代码，发现在大概 0.4.x 时在使用 `Choreographer的FrameCallback` 进行帧率计算，Wiki 中的文章也能佐证；但是大概在 0.6.x 时改成了现在这种基于 Looper 消息的方式，这是为什么？

**Comment by qinhehu** [comment]
![image](https://user-images.githubusercontent.com/17612332/122735810-f6683180-d2b1-11eb-8c42-577301ea8368.png)

**Comment by AliMaster** [comment]
@qinhehu 这里确实看漏了。之前一直拿 0.6.5 版本分析，后来发 issue 时粗略看最新版以为逻辑差不多。

对于 issue 中的疑问，前两天翻到了 @linjiang 大佬的 blog ，看完以后已经解惑了
这里贴出来给大家 https://linjiang.tech/2019/11/12/matrix-trace-canary/
