### ISSUE TITLE
对FrameTracer的onChange方法的疑问

### ISSUE THREAD

**Issue by toutoumama** [Tencent/matrix#60]
matrix version：0.4.10

FrameTracer的onChange方法中会先判断activity和fragment是否为空，任意为空都将返回。
但是ApplicationLifeObserver中的onActivityResumed中在调用onChange方法时，直接将fragment设置为null，这将导致无法对activity加上onDrawListener，那么doFrame就会直接返回。

不知道我的理解是否正确，谢谢。

**Comment by txfelixzhou** [comment]
请merge dev代码，或查看此次提交 https://github.com/Tencent/matrix/commit/6085c25e3bcabe17f7d9f3d1a5b33210592fd280
