### ISSUE TITLE
CONFIG-FILE_PATH配置返回null

### ISSUE THREAD

**Issue by wustor** [Tencent/matrix#61]
感谢腾讯能够开源Matrix这么好的库.

我在接入的时候在配置CONFIG-FILE_PATH的时候，困扰了我很很久，首先我是一名Android开发，在公司负责CI这块，相对于负责别的模块的同事，对Shell脚本及Python接触地稍微多一点，但是依然在配置的时候困扰了很久，文档中提供了一个Json示例以及配置Json的方式。

ApkChecker跟config.json是放置在同级目录下，基于Python以及Shell脚本的开发经验，我是这么配置的：
`java -jar ApkChecker.jar --config config.json`
始终返回null,在这里我卡了很久，后来在关闭的Issue中，才发现必须这么配置：
`
java -jar ApkChecker.jar --config ./config.json
`
我觉得这个其实很容易误导使用者，因为文档没有示例，同时在示例的Json中给的是全路径，在CI接入ApkChecker的时候大多数都是传的相对路径。

这个问题同样存在于Json文件中，一开始我是这么写的：
`{
  "--apk":"mobike.apk",
  "--mappingTxt":"mapping.txt",
  "--output":"apk-checker-result"
}`
始终返回null，我调试了很久，才知道必须加上"./"
`{
  "--apk":"./demo.apk",
  "--mappingTxt":"./mapping.txt",
  "--output":"./apk-checker-result"
}`
因为当路径输入错误时，没有明显的提示，而且路径必须加上"./"，对开发者不友好，希望作者能够对错误给予相应的提示，谢谢。

**Comment by txfelixzhou** [comment]
使用绝对路径是更可靠的，当然我们后续会考虑兼容

**Comment by wustor** [comment]
认可，但是能否在文档中进行说明一下？

**Comment by txfelixzhou** [comment]
![image](https://user-images.githubusercontent.com/15136816/50635966-48f0ee80-0f8f-11e9-8142-b173e6e75ac2.png)
