### ISSUE TITLE
iOS 监测CPU使用，永远触发不到onBlockMonitorCurrentCPUTooHigh回到方法

### ISSUE THREAD

**Issue by zichengbohan** [Tencent/matrix#610]
异常类型：CPU永远触发不到onBlockMonitorCurrentCPUTooHigh回调方法

手机型号：iPhone x

手机系统版本：14.5.1

matrix版本：1.0.1

问题描述：在iphone X g_CPUUsagePercent = 480,    cpuUsage的最大值才是100，
 if (cpuUsage > g_CPUUsagePercent) {
            MatrixInfo(@"check cpu over usage dump %f", cpuUsage);
            BM_SAFE_CALL_SELECTOR_NO_RETURN(_delegate, @selector(onBlockMonitorCurrentCPUTooHigh:), onBlockMonitorCurrentCPUTooHigh:self)
            if ([_monitorConfigHandler getShouldGetCPUHighLog]) {
                if (m_powerConsumeStackCollector && [m_powerConsumeStackCollector isCPUHighBlock]) {
                    return EDumpType_CPUBlock;
                }
            }
        }
这个条件怎么能成立呢？？？？？

**Comment by chzhij5** [comment]
"cpuUsage的最大值才是100" 一个核心是100。

跑多几个线程试试。
