### ISSUE TITLE
未找到 “ANR Trace” 日志

### ISSUE THREAD

**Issue by e-snail** [Tencent/matrix#618]
我运行 android-sample项目并模拟ANR后，并未看到traceplugin输出的 ANR Trace 日志。

matrix声称通过PLT Hookwrite()函数可以获取该日志

请指正！

**Comment by e-snail** [comment]
with following configuration

`
        TraceConfig traceConfig = new TraceConfig.Builder()
                .dynamicConfig(dynamicConfig)
                .anrTracePath("/data/data/sample.tencent.matrix/files/trace.txt")
                .printTracePath("/data/data/sample.tencent.matrix/files/trace_print.txt")
                .enableFPS(fpsEnable)
                .......
`

**Comment by yeleaveszi** [comment]
配置加上enableSignalAnrTrace(true)
发生ANR后Trace会保存到anrTracePath文件中
目前是通过MatrixLog打印出来，后面会添加相应的回调

**Comment by e-snail** [comment]
@yeleaveszi   
1. enableSignalAnrTrace(true) 这个已经配置了
2. 我看native中源码MatrixTracer.cc中（如下）是把 ANR Trace写到 anrTracePath() 配置的路径中，并不是输出在 log中。

`
ssize_t (*original_write)(int fd, const void* const __pass_object_size0 buf, size_t count);
ssize_t my_write(int fd, const void* const buf, size_t count) {
    if(isTraceWrite && gettid() == signalCatcherTid) {
        isTraceWrite = false;
        signalCatcherTid = 0;
        if (buf != nullptr) {
            std::string targetFilePath;
            if (fromMyPrintTrace) {
                targetFilePath = printTracePathstring;
            } else {
                targetFilePath = anrTracePathstring;
            }
            if (!targetFilePath.empty()) {
                char *content = (char *) buf;
                writeAnr(content, targetFilePath);
                if(!fromMyPrintTrace) {
                    anrDumpTraceCallback();
                } else {
                    printTraceCallback();
                }
                fromMyPrintTrace = false;
            }
        }
    }
    return original_write(fd, buf, count);
}
`

**Comment by yeleaveszi** [comment]
文件生成后会打印到MatrixLog中，sample目前的MatrixLog没有具体实现，请使用Matrix.setLogIml方法设置具体的log实现。

**Comment by e-snail** [comment]
> 文件生成后会打印到MatrixLog中，sample目前的MatrixLog没有具体实现，请使用Matrix.setLogIml方法设置具体的log实现。

“文件生成后”  你指的是hook  Signal Catcher的write()函数后 写的 ANR Trace 文件吗？

**Comment by yeleaveszi** [comment]
确认MatrixLog默认是会用android.util.Log实现的，我自己测试没问题，文件可以生成，Trace也会打印在logcat里面。

**Comment by yeleaveszi** [comment]
请确认是否有/data/data/sample.tencent.matrix/files/这个目录存在，如果没有，需要先建立这个目录

**Comment by e-snail** [comment]
> 请确认是否有/data/data/sample.tencent.matrix/files/这个目录存在，如果没有，需要先建立这个目录

这个目录存在

**Comment by yeleaveszi** [comment]
请您提供测试设备的型号，以及完整的TraceConfig。

**Comment by e-snail** [comment]
设备OnePlus 7T


        TraceConfig traceConfig = new TraceConfig.Builder()
                .dynamicConfig(dynamicConfig)
                .anrTracePath("/data/data/sample.tencent.matrix/files/trace.txt")
                .printTracePath("/data/data/sample.tencent.matrix/files/trace_print.txt")
                .enableFPS(fpsEnable)
                .enableEvilMethodTrace(traceEnable)
                .enableAnrTrace(traceEnable)
                .enableStartup(traceEnable)
                .enableIdleHandlerTrace(traceEnable)                    // Introduced in Matrix 2.0
                .enableMainThreadPriorityTrace(true)                    // Introduced in Matrix 2.0
                .enableSignalAnrTrace(signalAnrTraceEnable)             // Introduced in Matrix 2.0
                .splashActivities("sample.tencent.matrix.SplashActivity;")
                .isDebug(true)
                .isDevEnv(false)
                .build();

**Comment by yeleaveszi** [comment]
请确认的确发生了ANR（有ANR弹窗），可以观察如果有"detail":"SIGNAL_ANR"的issue上报说才说明产生了一个ANR。Sample中的例子是sleep了10秒，在有的机型上可能达不到ANR的阈值，可以尝试增加sleep的时间。

**Comment by yeleaveszi** [comment]
先关闭了，后续会完善和补充sample，谢谢反馈

**Comment by TedaLIEz** [comment]
+1, Samsung S20+, API 30 遇到同样问题

Matrix version: 2.0.0-beta

config:

```java
String path = getExternalCacheDir().getAbsolutePath() + File.separator + "trace.txt";
TracePlugin plugin = new TracePlugin(new TraceConfig.Builder()
                .enableIdleHandlerTrace(false)
                .enableAnrTrace(false)
                .enableAppMethodBeat(false)
                .enableEvilMethodTrace(false)
                .enableFPS(false)
                .enableMainThreadPriorityTrace(false)
                .enableStartup(false)
                .isDebug(true)
                .anrTracePath(path)
                .printTracePath(path)
                .enableSignalAnrTrace(true)
                .build());
```


此path参数可以被当做`Debug.startMethodTracingSampling`的参数生成profile文件，因此路径应该可用。

日志中找到信息:


```
SignalAnrTracer: happens real ANR : {"machine":"BEST","cpu_app":0,"mem":11049529344,"mem_free":6893200,"detail":"SIGNAL_ANR","scene":"....","isProcessForeground":true,"tag":"Trace_EvilMethod","process":"...","time":1627895835837} 

```

**Comment by e-snail** [comment]
@TedaLIEz 有ANR弹窗吗？没有的话你得调一下时间让它有弹窗

**Comment by TedaLIEz** [comment]
> @TedaLIEz 有ANR弹窗吗？没有的话你得调一下时间让它有弹窗

有系统“应用未响应弹窗”，这个我可以确认，因为是公司项目，这里就不方便给出截图了。

**Comment by e-snail** [comment]
有files这个文件夹吗？

**Comment by TedaLIEz** [comment]
> 有files这个文件夹吗？

有的，我adb shell ls可以看到

**Comment by yeleaveszi** [comment]
已知问题，在少数机型上会有hook不到trace的问题，参考#621，该问题内部已经修复，近期会PR，请留意后续版本，谢谢反馈

**Comment by TedaLIEz** [comment]
Thx

**Comment by yeleaveszi** [comment]
@TedaLIEz 已修复

**Comment by TedaLIEz** [comment]
2.0.0能看到txt文件信息，谢谢
