### ISSUE TITLE
鸿蒙双系统上ANR监控问题

### ISSUE THREAD

**Issue by lhwbest** [Tencent/matrix#621]
鸿蒙双系统上遇到两个问题
~~1) Mate30pro机型捕获不到sigquit信号~~
2) p40机型SignalCatcher线程对应的sigblk为0×5000

**Comment by yeleaveszi** [comment]
1. 华为某些系统使用了自己的ANR机制（**APPEYE ANR**，logcat可以过滤**ZRHungService**看到相关日志），此时不会发送sigquit信号，的确会有漏报的情况，不过好在该问题只在Mate 20/Mate 30/Mate 30 Pro的**某些系统版本**上发现过。我们也在联系华为，了解他们相关的计划。
2. 该问题确实在少数机型上存在，会导致无法获取ANR Trace，但不会影响ANR的监控；我们已经修复，请留意后续更新。
两个问题都与鸿蒙系统关系不大，ANR监控在鸿蒙系统上也可以正常工作，**感谢你的反馈。**

**Comment by yeleaveszi** [comment]
> 1. 华为某些系统使用了自己的ANR机制（**APPEYE ANR**，logcat可以过滤**ZRHungService**看到相关日志），此时不会发送sigquit信号，的确会有漏报的情况，不过好在该问题只在华为的**某些系统版本**上发现过。我们也在联系华为，了解他们相关的计划。
> 2. 该问题确实在少数机型上存在，会导致无法获取ANR Trace，但不会影响ANR的监控。我们已经修复，请留意后续更新。
> 
> 两个问题都与鸿蒙系统关系不大，ANR监控在鸿蒙系统上也可以正常工作，**感谢你的反馈。**

关于第一点的补充：经过进一步的测试和了解，我们之前测试中出现的在少数华为机型上收不到sigquit信号的情况，是因为我们特殊的测试环境导致的，在实际的真机环境上，并不存在该问题。华为虽然自定义了自己的ANR监控机制，但是也确保了，**绝大部分情况下**，华为自己的ANR和原生的ANR流程会同时发起。我们也向华为的同事确认了并不会修改原生的ANR流程。所以该方案的兼容性在可见的将来应该都没什么问题。

**Comment by yeleaveszi** [comment]
@lhwbest 已修复
