### ISSUE TITLE
Android 手机编译后 运行app 报错：NoClassDefFoundError: Failed resolution of: Lcom/google/gson/reflect/TypeToken;

### ISSUE THREAD

**Issue by hunaifeng007** [Tencent/matrix#624]
异常类型：app 运行时异常

手机型号：小米 MI MAX2  

手机系统版本：android 7.0
matrix版本：1.0.0

gradle版本：4.1.0

问题描述：编译后运行报错

接入前 项目minSdkVersion 是21 com.android.tools.build:gradle是 3.6.0  gradle-5.6.4
接入后 项目minSdkVersion 是21 gradle 插件版本需要升级  4.1.0 gradle-6.5
运行到手机总是报找不到gson中的文件 是因为sdk 为21 时我的项目没有开启65535分包机制导致的吗

![B91C6414-2250-45bf-B2F6-55C7C6689274](https://user-images.githubusercontent.com/87982607/126992759-b68c74bc-510e-469b-bd45-8b6d21911c68.png)

**Comment by hunaifeng007** [comment]
不清为什么照着首页文档的方式去配置跑不起来，后来研究了一下demo，照着demo去配置才能运行。

**Comment by shiduan** [comment]
你好这个你怎么解决的？
