### ISSUE TITLE
WCMemoryStatPlugin 能全量线上使用吗？

### ISSUE THREAD

**Issue by NonMacAliyun** [Tencent/matrix#626]
WCMemoryStatPlugin 能全量线上使用吗？
我使用低端进行了测试（主要关心爆内存），发现其CPU、内存的占用并不高，流畅性影响也不大。所以demo中提及的对性能损耗体现在哪些方面？
我们想在线上使用这个功能。

**Comment by ganvinalix** [comment]
抽样可以

**Comment by chzhij5** [comment]
抽样使用
