### ISSUE TITLE
pod方式引入后编译报错问题

### ISSUE THREAD

**Issue by kenny-alt** [Tencent/matrix#633]
![截屏2021-08-05 下午10 50 37](https://user-images.githubusercontent.com/79312856/128370905-af9f2c91-ae9f-4bfa-9c10-e3a0b879ee29.png)

**Comment by ganvinalix** [comment]
我这也有这个问题 怎么处理的呢

**Comment by ganvinalix** [comment]
找到了原因了
![image](https://user-images.githubusercontent.com/2315308/129005479-a5a34962-045c-4f3d-9c59-c5b2a19ecd53.png)
和openssl冲突了ssl里里面有一个stack.h头文件

**Comment by ganvinalix** [comment]
应该可以关闭这个bug 或sdk 以后 重新改下下stack命名吧

**Comment by chzhij5** [comment]
感谢
