### ISSUE TITLE
android studio 2020.3.1 编译不通过

### ISSUE THREAD

**Issue by jiyewushen** [Tencent/matrix#634]
```
matrix版本:2.0.0

gradle版本：com.android.tools.build:gradle:7.0.0 

堆栈/日志：
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Users\xxx\.gradle\caches\transforms-3\d5f94688e7b002e24579d12785e95cad\transformed\jetified-matrix-hooks-2.0.0\jni\arm64-v8a\libc++_shared.so
      - C:\Users\xxx\.gradle\caches\transforms-3\6ad9f61fcabb05d3a22920887c5a80d9\transformed\jetified-matrix-backtrace-2.0.0\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```
使用 jniLibs 明确打包库会导致重复，https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets

**Comment by HAIWWH** [comment]
我出现了，请问你解决了么

**Comment by jiyewushen** [comment]
没有

**Comment by HAIWWH** [comment]
> 没有
在app的gradle文件中加下面这个，可以解决
packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }

**Comment by jiyewushen** [comment]
😅，👍！

**Comment by youuupeng** [comment]
packagingOptions {
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libwechatbacktrace.so'
        pickFirst 'lib/arm64-v8a/libwechatbacktrace.so'
}

**Comment by MmingY** [comment]
我也遇到这个问题了，请问有谁解决了吗？

**Comment by youuupeng** [comment]
已收到，谢谢。我会尽快查收的。
