### ISSUE TITLE
android的UIThreadMonitor能兼容一下android11版本吗？部分反射，在android11不生效

### ISSUE THREAD

**Issue by datong1016** [Tencent/matrix#647]
Accessing hidden field Landroid/view/Choreographer$FrameDisplayEventReceiver;->mTimestampNanos:J (greylist-max-o, reflection, denied)

 Accessing hidden field Landroid/view/Choreographer;->mLock:Ljava/lang/Object; (greylist-max-p, reflection, denied)

**Comment by QiuDa** [comment]
我也发现了Android 11 中 ReflectUtils.reflectObject(choreographer, "mLock", new Object()); 获取Lock锁对象失败，在执行callback 的时候实际没有进行有效的同步操作。

**Comment by QiuDa** [comment]
Android 11 已经禁止mLock 反射获取，所以初始化时实际得到的是 new Object对象，所以在Queue 添加回调时，会产生同步问题。

**Comment by yeleaveszi** [comment]
fixing
在修了 在修了

**Comment by datong1016** [comment]
不止同步问题，通过反射获取的ReflectUtils.reflectObject(vsyncReceiver, "mTimestampNanos", defaultValue);
也会获取不到，永远是defaultValue，而这个值是不对的，不是起始绘制时间，写个按钮sleep一下就测出来了，丢帧数不对

**Comment by kuyue** [comment]
> 



> fixing 在修了 在修了

请问修复好了么？
部分机型上好像会报这个crash：

---java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1155)
android.view.Choreographer.doCallbacks(Choreographer.java:977)
android.view.Choreographer.doFrame(Choreographer.java:904)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1140)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:257)
android.app.ActivityThread.main(ActivityThread.java:8281)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by yeleaveszi** [comment]
请留意后续版本的更新，会改变目前帧率监控的方案，谢谢支持。

**Comment by NetaGuo** [comment]
@yeleaveszi  hello  截止目前  针对这个反射的问题有新的版本么？

**Comment by yeleaveszi** [comment]
已经fix了，请等待Matrix下个版本发布

**Comment by yeleaveszi** [comment]
已经Fix，高版本系统已改用Window.OnFrameMetricsAvailableListener监控帧率

**Comment by wsycomeon** [comment]
修复了帧率，但是没版本细看vSync每个步骤的详细耗时了？
那么这个帧率的刷新 和 市面上普通的 Choreographer post回调 计算帧率方案相比，有什么优势？
