### ISSUE TITLE
PThreadHook怎么使用，如何查看效果？

### ISSUE THREAD

**Issue by lyhighfly** [Tencent/matrix#650]
问题：
我运行最近加入Matrix全家桶的PthreadHook 的demo：'Test Thread Hook'，我用常用的的工具(top查看VIRT列、dumpsys meminfo )查看内存的变化，发现并没有变化。以下是Matrix Thread Hook demo工程产生的log内容：
`{
    "PthreadHook_not_exited": [
        {
            "hash": "5772876107891757802",
            "native": "#pc 50580 wechat_backtrace::unwind_adapter(wechat_backtrace::Frame*, unsigned long, unsigned long&) (/data/app/sample.tencent.matrix-ObLEV0-28vH9ErzsHzRFnw==/lib/arm64/libwechatbacktrace.so);#pc 3c00 (null) (/data/app/sample.tencent.matrix-ObLEV0-28vH9ErzsHzRFnw==/lib/arm64/libmatrix-pthreadhook.so);#pc 36e0 (null) (/data/app/sample.tencent.matrix-ObLEV0-28vH9ErzsHzRFnw==/lib/arm64/libmatrix-pthreadhook.so);#pc 7fcc (null) (/data/app/sample.tencent.matrix-ObLEV0-28vH9ErzsHzRFnw==/lib/arm64/libmatrix-pthreadhook.so);#pc 4f2a34 art::Thread::CreateNativeThread(_JNIEnv*, _jobject*, unsigned long, bool) (/apex/com.android.runtime/lib64/libart.so);#pc 42d548 (null) (/apex/com.android.runtime/lib64/libart.so);#pc 4ae41c (null) (/system/framework/arm64/boot.oat);#pc 707f693574 (null) (null);#pc 61c914224fccbf (null) (null);",
            "java": "dalvik.system.VMStack.getThreadStackTrace(Native Method);com.tencent.matrix.hook.HookManager.getStack(HookManager.java:163);sample.tencent.matrix.hooks.TestHooksActivity.threadTest(TestHooksActivity.java:231);java.lang.reflect.Method.invoke(Native Method);android.view.View$DeclaredOnClickListener.onClick(View.java:6009);android.view.View.performClick(View.java:7160);android.view.View.performClickInternal(View.java:7137);android.view.View.access$3500(View.java:810);android.view.View$PerformClick.run(View.java:27418);android.os.Handler.handleCallback(Handler.java:883);android.os.Handler.dispatchMessage(Handler.java:100);android.os.Looper.loop(Looper.java:224);android.app.ActivityThread.main(ActivityThread.java:7520);java.lang.reflect.Method.invoke(Native Method);com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539);com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950);",
            "count": "50",
            "threads": [
                {
                    "tid": "19129",
                    "name": "Test"
                },
                .
                .
                .
                {
                    "tid": "19074",
                    "name": "Test"
                },
                {
                    "tid": "19073",
                    "name": "Test"
                }
            ]
        }
    ],
    "PthreadHook_not_released": []
}`
测试设备：MI 9
Android版本：10
MIUI版本：11.0.5.0
内核版本：4.14.117-perf-gd771a6b

根据 https://mp.weixin.qq.com/s/ZbFQQ5AVsHy0YL_kKMAiYA 所提到的，PThread的hook主要是将thread的栈空间减小，以达到减小虚拟内存占用的目的，请问你们在做这个功能时，测试工具以及测试指标是怎么样的？

**Comment by Yves0** [comment]
pthread hook 包含了两项功能，sample 中目前只有检测线程泄漏的 demo，要压缩栈空间的话可以在 Application#onCreate 中添加以下代码（需要 ignore 的 so 自行替换正则）

```Java
if (!is64BitRuntime()) {
    try {
        final PthreadHook.ThreadStackShrinkConfig config = new PthreadHook.ThreadStackShrinkConfig()
                .setEnabled(true)
                .addIgnoreCreatorSoPatterns(".*/app_tbs/.*")
                .addIgnoreCreatorSoPatterns(".*/libany\\.so$");
        HookManager.INSTANCE.addHook(PthreadHook.INSTANCE.setThreadStackShrinkConfig(config)).commitHooks();
    } catch (HookManager.HookFailedException e) {
        e.printStackTrace();
    }
}
```

**Comment by Yves0** [comment]
验证方法：查看 `/proc/<pid>/maps` 里面新创建的线程对应的栈内存的 size，或者在 native 代码中获取 pthread_attr_t
