### ISSUE TITLE
iOS--耗电日志怎么符号化

### ISSUE THREAD

**Issue by 734566743** [Tencent/matrix#654]
## Issue /提问须知
**在提交 issue 之前，我们应该先查询是否已经有相关的 issue 以及[常见问题](https://github.com/tencent/matrix/wiki/Matrix-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交 issue 时，我们需要写明 issue 的原因，以及编译或运行过程的日志。issue 需要以下面的格式：**

```


matrix版本：如: 0.6.8

使用 battery2apple 对json进行解析后。怎么符号化，定位到对应的模块/函数。求解，谢谢。

**Comment by gerald8** [comment]
+1

**Comment by PeleLee** [comment]
请问你最终的解析结果是什么样子的，我通过battery2apple.py脚本解析日志后还是不知道如何定位问题
