### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by muzitianya** [Tencent/matrix#66]
java.lang.RuntimeException: plugin start, plugin listener is null

使用 ioCanaryPlugin  出现这种错误.

**Comment by txfelixzhou** [comment]
![image](https://user-images.githubusercontent.com/15136816/50672114-05d75f80-1011-11e9-8ee4-7f0c82aa8605.png)

没有配置listener，在首页的README.md和sample都有详细的使用说明，请先仔细查看。谢谢
