### ISSUE TITLE
Io Cananry只能对主线程的Small Buffer做检测，为何异步线程的 Buffer错误使用不做采集呢？

### ISSUE THREAD

**Issue by LiuchengGit** [Tencent/matrix#69]
在io_canary_jni.cc中所有hook prox均加了判断：
 if(!IsMainThread()) 
那么请问，一个子线程使用较小Buffer的问题，就不算Io 问题吗 ？ 对于主线程等待子线程数据的场景，是不是会漏报 ？，这个遗漏和官方wiki描述不一致，官方wiki 描述为“检测读写 Buffer 过小”，并未限定主线程

matrix版本：如: 0.4.10

gradle版本：如: 3.0.0

问题描述：如：在 android O 出现系统不兼容

**Comment by astrozhou** [comment]
如果不加线程限制的话，目前的方案在 detector 部分会出现多线程问题，加锁的情况下反而可能影响主线程的性能，得不偿失。因此目前暂时只发现主线程上的不合理 IO 操作。后续会继续优化方案，寻求解决多线程问题的方案

**Comment by LiuchengGit** [comment]
好的，感谢解答

**Comment by arstao** [comment]
> 如果不加线程限制的话，目前的方案在 detector 部分会出现多线程问题，加锁的情况下反而可能影响主线程的性能，得不偿失。因此目前暂时只发现主线程上的不合理 IO 操作。后续会继续优化方案，寻求解决多线程问题的方案

如果是用ThreadLocal，在open、write、read、close各个线程操作各自的数据保存在ThreadLocal，然后close的取出来再post到单独线程处理。这样子可以解决多线程同步带来的性能损耗？

**Comment by JackyAndroid** [comment]
> 如果不加线程限制的话，目前的方案在 detector 部分会出现多线程问题，加锁的情况下反而可能影响主线程的性能，得不偿失。因此目前暂时只发现主线程上的不合理 IO 操作。后续会继续优化方案，寻求解决多线程问题的方案

@astrozhou 加锁的话影响主线程会多大，有具体数据可参考吗？如果只是在debug版本使用，稍微影响性能其实还可以接受
