### ISSUE TITLE
anrTracePath与printTracePath参数有何区别

### ISSUE THREAD

**Issue by TedaLIEz** [Tencent/matrix#692]
Matrix 2.0.2下提供了`printTracePath`和`anrTracePath`两个参数，这两个参数都用在了SignalAnrTracer里面，我想问一下他们的区别是什么？

从source code看，printTracePath只是在SignalAnrTracer中的`printTrace`被主动调用时才会被使用到，最后出现在我们hook的my_write函数中，但是其他地方，包括监听ANR Signal时，似乎并没有用到。那监听ANR Signal后，将ANR的trace信息的写入，对应的配置项应该是`anrTracePath`，我的理解正确吗？ 如果是这样，设计`printTracePath`是用来解决什么问题的呢？

谢谢

**Comment by yeleaveszi** [comment]
您好，可以参考这篇文章：

**Comment by yeleaveszi** [comment]
您好，可以参考这篇文章的3.3小节
https://mp.weixin.qq.com/s/fWoXprt2TFL1tTapt7esYg
设置了printTracePath参数后，调用SignalAnrTracer.printTrace()，可以主动获取当时的Trace，拿到当时所有线程的堆栈和状态，对于查某些特定问题，例如非主线程的死锁等问题会有帮助。
如果您只关注ANR，可以忽略这个参数，谢谢支持。

**Comment by TedaLIEz** [comment]
明白，谢谢
