### ISSUE TITLE
关于Anr监控和Bugly共同使用的疑惑

### ISSUE THREAD

**Issue by tudiheshifu123** [Tencent/matrix#697]
我想问下，这个Anr的监控，如果用在了线上，会对原来Bugly的收集有影响吗，目前项目用的是Bugly

**Comment by yeleaveszi** [comment]
我们内部跟bugly也有一些交流，使用的方法有相似之处也有不同之处，具体两者是否兼容，我们并没有进行过相关的测试，建议尽量只使用其中一个。

**Comment by tudiheshifu123** [comment]
已经确认过，暂时不影响，bugly版本为3.1.0

**Comment by newhope821** [comment]
在开发中也碰到了这个问题，同时集成了matrix和bugly，想同时收集ANR。
经测试发现（matrix版本为2.1.0）：
如果bugly用4.0.4及以前的旧版本，matrix和bugly都能收到ANR；
但是如果bugly用4.0.4以后的新版本，只有其中一个能收到（谁后初始化，谁收到）。
