### ISSUE TITLE
关于anr的堆栈dump疑问，是否可以直接hookRuntime::DumpForSigQuit

### ISSUE THREAD

**Issue by datong1016** [Tencent/matrix#706]
源码中hook了socket的connect和write，获取signal_catcher线程往socket里写的堆栈，而堆栈其实是Runtime::DumpForSigQuit拿到的，那能不能尝试直接Runtime::DumpForSigQuit呢，这样不就能直接拿到堆栈了吗？

**Comment by yeleaveszi** [comment]
你指的hook具体是指通过符号直接调用DumpForSigQuit吗？
的确是可以的，我们也尝试过这种方案，但是主要考虑到两方面：
1、兼容性问题，这类方案都会有比较大的兼容性问题（实际上也的确遇到了），而plt hook的兼容性要好得多
2、性能、效率问题，hook socket的方案，只是搭了系统dump行为的便车，而不用dump两次（dump本身也是很重的行为）

**Comment by yeleaveszi** [comment]
hook DumpForSigQuit具体是指通过符号直接调用DumpForSigQuit吗？
的确是可以的，我们也尝试过这种方案，但是主要考虑到两方面：
1、兼容性问题，这类方案都会有比较大的兼容性问题（实际上也的确遇到了），而plt hook的兼容性要好得多
2、性能、效率问题，hook socket的方案，只是搭了系统dump行为的便车，而不用dump两次（dump本身也是很重的行为）

**Comment by datong1016** [comment]
xcrash确实使用符号直接调用DumpForSigQuit
我的意思是还是使用plt hook，用my_dump替换原始的DumpForSigQuit
void my_dump(std::ostream& os) {
    origin_dump(os);
    //os.str直接拿到堆栈
}

**Comment by yeleaveszi** [comment]
plt hook只能hook在got表里的方法，您可以再了解下plt hook的原理

**Comment by yeleaveszi** [comment]
谢谢提问，我先close了

**Comment by datong1016** [comment]
理解了 DumpForSigQuit不是外部调用  感谢
