### ISSUE TITLE
请教一下为什么ANR监控在子线程初始化会不生效？

### ISSUE THREAD

**Issue by datong1016** [Tencent/matrix#707]
已知SignalCatcher线程使用sigwait等待SIGQUIT，而sigwait需要所有线程都阻塞该信号，才会走到sigwait的处理中。
目前应该是必须在主线程unblock SIGQUIT，才能让sig_handler去接管SIGQUIT的信号处理，为什么子线程去unblock不行？
这两者有什么区别吗，对信号处理不是很了解，查了很久资料也没找到原因，求解，十分感谢。

**Comment by yeleaveszi** [comment]
子线程初始化？一般来说，子线程初始化完就被释放了哦，怎么起到作用呢？

**Comment by yeleaveszi** [comment]
先关掉了
