### ISSUE TITLE
Evil Method 新增的 LAG 类型是啥意思

### ISSUE THREAD

**Issue by shaoshuai904** [Tencent/matrix#725]
Wiki 里的字段说明已经 跟不上代码更新的速度了，Evil Method 新增的 LAG 类型是啥意思，辛苦开发补全一下吧

**Comment by newCaoTao** [comment]
我也发现了这个问题，是在android的崩溃的时候，detail值为lag

**Comment by yeleaveszi** [comment]
Lag的含义是主线程的卡顿，默认是2秒以上的卡顿
卡顿和ANR很多时候不是一类问题，很多问题会导致非常普遍的卡顿，但是不至于产生ANR
Lag根据卡顿监控的来源目前分成3类

**Comment by yeleaveszi** [comment]
Lag是指主线程阻塞导致的卡顿，默认是2秒以上的卡顿
很多问题会导致大量、普遍的卡顿，但却很少产生ANR
Lag根据监控来源不同分为了三种
LAG：表示主线程Message耗时导致的卡顿
LAG_TOUCH：表示touch event耗时导致的卡顿
LAG_IDLE_HANDLER：表示idle handler耗时导致的卡顿
