### ISSUE TITLE
ApkChecker的日志信息

### ISSUE THREAD

**Issue by jaydenyuhy** [Tencent/matrix#73]
请问Apk Checker有参数支持关闭运行时打印的日志吗？

[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_title
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMargin
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMarginBottom
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMarginEnd
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMarginStart
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMarginTop
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleMargins
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleTextAppearance
[DEBUG][Matrix.UnusedResourcesTask]ignore resource R.styleable.Toolbar_titleTextColor

**Comment by jqctop1** [comment]
暂时没有，后面加上

**Comment by jqctop1** [comment]
新的master已经支持 --log 来设置日志级别
