### ISSUE TITLE
Touch 事件监控疑问

### ISSUE THREAD

**Issue by 2227056071** [Tencent/matrix#737]
求教。Touch 事件监控，系统源码里 UI 线程是通过 recv 和 send 方法来接收、消费事件的，按理说应该 hook recv 和 send 方法。 可是 Matrix 源码里是通过 hook recvfrom 和 sendto 方法。

**Comment by yeleaveszi** [comment]
源码继续往下看，recv/send最终还是通过recvfrom/sendto实现的
