### ISSUE TITLE
SIGNAL_ANR_NATIVE_BACKTRACE

### ISSUE THREAD

**Issue by jiayuliang1314** [Tencent/matrix#743]
公司项目上报上来的都是SIGNAL_ANR_NATIVE_BACKTRACE，没有SIGNAL_ANR
有两个问题
1.SIGNAL_ANR_NATIVE_BACKTRACE是不生成anr trace文件吗？没看见anr trace文件
2.没有上传SIGNAL_ANR，全都上传的SIGNAL_ANR_NATIVE_BACKTRACE，是有问题吗？

**Comment by yeleaveszi** [comment]
收到SIGNAL_ANR_NATIVE_BACKTRACE一般是由于SIGNAL_ANR超时导致的，可以检查下处理SIGNAL_ANR的回调方法是不是一直执行不完，有什么逻辑导致卡死了

**Comment by jiayuliang1314** [comment]
我们把bugly注释掉，看着有SIGNAL_ANR 了，bugly导致onANRDumpTrace不回调，目前用的
bugly_report 版本3.4.4
bugly_native 版本3.9.2

把bugly升级到了4.0.0，好使了onANRDumpTrace

**Comment by zhangxiangdong** [comment]
@yeleaveszi 同问，无法升级bugly，要用matrix，如何处理这个问题呢？

**Comment by jiayuliang1314** [comment]
调整一下bugly，matrix初始化顺序
