### ISSUE TITLE
请问下，这两个是什么意思

### ISSUE THREAD

**Issue by jiayuliang1314** [Tencent/matrix#744]
1.calculateCpuUsage 方法返回的，Cpu Usage：11.58%
2.getAppCpuRate返回的，App Cpu Rate：0.08912865950882479

请问下，这两个参数是什么意思

**Comment by dontknowhy** [comment]
> 1.calculateCpuUsage 方法返回的，Cpu Usage：11.58%
> 2.getAppCpuRate返回的，App Cpu Rate：0.08912865950882479
> 
> 请问下，这两个参数是什么意思

1应该是微信占用CPU百分比
2不知道
（这东西也不看看放在哪，不是随便瞎看的，当然看FPS还是很有用的）
