### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by zhangxiangdong** [Tencent/matrix#746]
异常类型：编译异常

手机型号：

手机系统版本：

matrix版本：2.0.8

gradle版本：7.2

问题描述：编译报错

堆栈/日志：

app/build/intermediates/transforms/MatrixTraceTransform/qa/debug/4.jar e:JSR/RET are not supported with computeFrames option
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$31.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$10.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$17$1.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$30$1.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$29.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/d$1.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/gatewayauth/PhoneNumberAuthHelperProxy$17$2.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/ab/a$a.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/ab/c.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/o/a$1.class
trace jar output ERROR: Emty try catch block handler range, com/mobile/auth/s/a.class

**Comment by zhangxiangdong** [comment]
设置 isSkipCheckClass 跳过异常就可以编译了

**Comment by lodqc** [comment]
> 设置 isSkipCheckClass 跳过异常就可以编译了

这样设置吗？plugin源码默认是true的，还要写什么文件吗
matrix {
    trace {
        enable = true	//if you don't want to use trace canary, set false
       skipCheckClass = true
        baseMethodMapFile = "${project.buildDir}/matrix_output/Debug.methodmap"
        blackListFile = "${project.projectDir}/matrixTrace/blackMethodList.txt"
    }
}

**Comment by zhangxiangdong** [comment]
> 

com.tencent.matrix.plugin.transform.MatrixTraceLegacyTransform 中 skipCheckClass 有用到

com.tencent.matrix.plugin.transform.MatrixTraceTransform 没有用到 skipCheckClass

你的 agp 版本是什么？

**Comment by lodqc** [comment]
手机型号：realme

手机系统版本：Android 12

matrix版本：2.0.8

gradle版本：gradle-7.4.2

**Comment by zhangxiangdong** [comment]
> 手机型号：realme
> 
> 手机系统版本：Android 12
> 
> matrix版本：2.0.8
> 
> gradle版本：gradle-7.4.2

agp 大于 4.0 默认使用 com.tencent.matrix.plugin.transform.MatrixTraceTransform，skipCheckClass没有设置上

逻辑在这里：

- com.tencent.matrix.plugin.compat.MatrixTraceCompat#inject

- com.tencent.matrix.plugin.transform.MatrixTraceTransform#configure

可以问问作者，这块具体的逻辑，看能不能支持上
