### ISSUE TITLE
无法排除getIdentifier资源

### ISSUE THREAD

**Issue by fuzhijun52058237** [Tencent/matrix#78]
代码中如果通过getIdentifier引用的资源，还是会被认为是未使用资源，造成异常。

**Comment by jqctop1** [comment]
@fuzhijun52058237 对于getIdentifier的方式引用，目前只能是加白名单

**Comment by fuzhijun52058237** [comment]
private int[] pics = new int[] {
   R.drawable.xxx_1,
    R.drawable.xxx_2
};

在数组里面定义资源，也会认为未使用，麻烦确认下

**Comment by jqctop1** [comment]
好，我确认下哈

**Comment by fuzhijun52058237** [comment]
另外，咨询下能够扫描assets下面的资源吗？  比如未使用的字体

**Comment by jqctop1** [comment]
@fuzhijun52058237 数组那个确实有问题，我改下，如果这种方式不多的话，可以先加白名单

**Comment by jqctop1** [comment]
@fuzhijun52058237 assets下现在是以文件为单位去扫描的，UnusedAssets就会给出没有使用的asset文件

**Comment by fuzhijun52058237** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/4945960/50819742-ebc9b400-1365-11e9-9369-fe98bd85bdc6.png">


我项目中有些字体是没使用的，但是未扫出来

**Comment by fuzhijun52058237** [comment]
apk不太方便，我全局搜索过字体名称，确认没有引用的地方，且matrix.json没改动过，是否有其它规则？

<img width="385" alt="image" src="https://user-images.githubusercontent.com/4945960/50876403-d3aa7100-1407-11e9-864b-c0cea86bc644.png">

**Comment by jqctop1** [comment]
@fuzhijun52058237 你的是windows系统吗？

**Comment by jqctop1** [comment]
@fuzhijun52058237 会不会其他的第三方库的代码有使用到这些字体？我拿demo工程的app试了没有问题

![image](https://user-images.githubusercontent.com/15994990/50878259-c34ac400-1410-11e9-9370-754c1b6f009d.png)

![image](https://user-images.githubusercontent.com/15994990/50878271-d1004980-1410-11e9-9999-4915d73daf5c.png)

**Comment by fuzhijun52058237** [comment]
没有的，这个能确认，对字体有过滤吗？

**Comment by jqctop1** [comment]
没有的，你可以改下源码，加些log看看？在UnusedAssetsTask

**Comment by jqctop1** [comment]
过滤的话，可以看你的配置文件里是否有ignoreAssets

**Comment by fuzhijun52058237** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4945960/50955840-15651580-14f5-11e9-898f-093c32ed36cc.png">
去掉了ignoreAssets

**Comment by jqctop1** [comment]
@fuzhijun52058237 去掉就可以了？

**Comment by fuzhijun52058237** [comment]
也不行，但是我发现情况是这样的，字体确实没实际用到，但是在string.xml里面定义了名字，生成了R文件，对于图片能够识别出未使用，对于asset无法这样做到吗？

**Comment by jqctop1** [comment]
![image](https://user-images.githubusercontent.com/15994990/50956647-2f075c80-14f7-11e9-9a30-e0cf7318a95d.png)

应该只在代码里引用才会算，没有去扫描xml的。不过这里判断引用是以assets的文件名结尾的，可能存在误判。

**Comment by jqctop1** [comment]
假设代码里有用到 ".ttf" 字符串，那么可能所有的ttf文件都会认为是使用了

**Comment by jqctop1** [comment]
@fuzhijun52058237 这里我再fix下

**Comment by fuzhijun52058237** [comment]
感谢，当前正在APP瘦身中，期待！~

**Comment by jqctop1** [comment]
最新master已经合入修改
