### ISSUE TITLE
有适配Android 12 的计划吗？

### ISSUE THREAD

**Issue by whxpro** [Tencent/matrix#794]
Targeting S+ (version 31 and above) requires that one of `FLAG_IMMUTABLE`  or `FLAG_MUTABLE`  be specified when creating a PendingIntent.

**Comment by igottime** [comment]
你这是啥功能报错？ 我在12上没问题。

**Comment by dust365** [comment]
我也遇到相同的问题，期望赶紧修改
![image](https://user-images.githubusercontent.com/19433729/206616284-de6e9e4d-92e7-4d5c-9b1e-2c0aa906d44b.png)
