### ISSUE TITLE
SQLiteLintPlugin的issue不会通过onReportIssue回调！！！

### ISSUE THREAD

**Issue by seasonfif** [Tencent/matrix#81]
DefaultPluginListener的onReportIssue，TracePlugin、IOCanaryPlugin都会将issue通过这个方法回调，但是SQLiteLintPlugin的issue不会走这个回调接口，请问怎么拿到SQLiteLintPlugin的issue信息？

**Comment by txfelixzhou** [comment]
请描述清楚问题，谢谢

**Comment by seasonfif** [comment]
DefaultPluginListener的onReportIssue，TracePlugin、IOCanaryPlugin都会将issue通过这个方法回调，但是SQLiteLintPlugin的issue不会走这个回调接口，请问怎么拿到SQLiteLintPlugin的issue信息？

**Comment by txfelixzhou** [comment]
对，这块也修改成reportissue方式，当前你可以借鉴sample的代码拿到issue数据
