### ISSUE TITLE
内存泄漏监控在开发模式下增加Java堆栈回溯

### ISSUE THREAD

**Issue by lintran-cn** [Tencent/matrix#820]
native内存泄漏堆栈只有native的，在开发模式下可以牺牲部分性能增加java堆栈回溯，更方便定位问题

1、过滤无需回溯的堆栈
2、过滤Native线程
3、过滤无需回溯的Java线程

**Comment by paozhuanyinyu** [comment]
支持回溯Java堆栈吗？
