### ISSUE TITLE
AppMethodBeat is close。请大大们百忙之中解答一下，谢谢~

### ISSUE THREAD

**Issue by zhoupeng2** [Tencent/matrix#842]
异常类型：app 运行时异常

手机型号： Oppo R9

手机系统版本：Android 9.0 (如是编译异常，则可以不填)

matrix版本： 2.0.5

gradle版本： 6.7.1

问题描述：如：各位开发大大，你们好。我的项目集成后提示 AppMethodBeat is close。没有输出 doFrame等信息是怎么回事？请各位百忙之中解答一下，谢谢~

堆栈/日志：
                                                                                                    >>>>>>>>>>>>>>>>>>>>> maybe happens Jankiness!(507ms) <<<<<<<<<<<<<<<<<<<<<
                                                                                                    |* [Status]
                                                                                                    |*		Scene: com.****y.**n.activity.MainActivity
                                                                                                    |*		Foreground: true
                                                                                                    |*		Priority: 10	Nice: -10
                                                                                                    |*		is64BitRuntime: false
                                                                                                    AppMethodBeat is close[true].
                                                                                                    =========================================================================

**Comment by zhoupeng2** [comment]
matrix {
        trace {
            enable = true	//if you don't want to use trace canary, set false
            baseMethodMapFile = "${project.buildDir}/matrix_output/Debug.methodmap"
            blackListFile = "${project.projectDir}/matrixTrace/blackMethodList.txt"
        }
    }

配置到build.grade文件的 android{

} 中最后一项就好了

**Comment by lonelyssl** [comment]
我也遇到该问题，上面的办法没解决，这个怎么解决那？
