### ISSUE TITLE
TestPluginListener日志收集次数比较少

### ISSUE THREAD

**Issue by xinxi1990** [Tencent/matrix#85]
异常类型：TestPluginListener日志收集次数比较少

手机型号: 小米8se 8.0版本 
matrix版本：0.4.7

问题描述：TestPluginListener日志收集次数比较少 ,再集成matrix后,运行app切换多个页面,在控制台
查看TestPluginListener的日志基本上就看到了一次,想问下这个日志收集是什么收集的频率或者是什么逻辑?

**Comment by txfelixzhou** [comment]
按理是有很多issue的，建议按照Readme和sample看看是不是使用不对
 另外，可以通过重写DynamicConfig来修改参数实现较快频率收集
