### ISSUE TITLE
疑问：为什么 BUFFER_SIZE 设置这么大呢

### ISSUE THREAD

**Issue by tennkou** [Tencent/matrix#854]
为什么 BUFFER_SIZE 要设置这么大呢，占用了 7.6M 的内存空间，用在线上的话，不会增加线上app oom的概率吗。一般来说方法调用栈不会占用这么多吧。设置这么大是为了尽可能多保存方法调用栈吗？

**Comment by zhangyy2017** [comment]
@tennkou  你们这个用在线上了么？

**Comment by zhangyy2017** [comment]
我最近也在调研这个，但是__syscall_logger 这个是私有方法，应该上线没办法上吧

**Comment by tennkou** [comment]
@zhangyy2017 没呢啊，最近在调研这个

**Comment by zhangyy2017** [comment]
@tennkou  加个V：fishman_luck，合伙研究研究😂

**Comment by TYZRPVX** [comment]
假设一个方法执行耗时 1us，7.6M 可以存储 100w 个方法，对应耗时 10s，可以反应真实 ANR 情况

**Comment by tennkou** [comment]
> 

matrix 可以用线上release 包吗

**Comment by tennkou** [comment]
> 假设一个方法执行耗时 1us，7.6M 可以存储 100w 个方法，对应耗时 10s，可以反应真实 ANR 情况

matrix 可以用线上release 包吗

**Comment by TYZRPVX** [comment]
> fishman_luck

可以的

**Comment by tennkou** [comment]
> > fishman_luck
> 
> 可以的

好的，谢谢大佬
