### ISSUE TITLE
CloseGuardHooker.tryHook没有适配9.0

### ISSUE THREAD

**Issue by weikano** [Tencent/matrix#86]
手机系统版本：android 9.0
matrix版本：如: 0.4.7
问题描述：在 android 9.0 出现系统不兼容 

```java
Field fieldREPORTER = closeGuardCls.getDeclaredField("reporter");
//这里为什么不直接反射调用CloseGuard.setEnable方法，而是通过field来设置？
Field fieldENABLED = closeGuardCls.getDeclaredField("stackAndTrackingEnabled");
```

**Comment by txfelixzhou** [comment]
@lolobug

**Comment by lolobug** [comment]
> 手机系统版本：android 9.0
> matrix版本：如: 0.4.7
> 问题描述：在 android 9.0 出现系统不兼容
> 
> ```java
> Field fieldREPORTER = closeGuardCls.getDeclaredField("reporter");
> //这里为什么不直接反射调用CloseGuard.setEnable方法，而是通过field来设置？
> Field fieldENABLED = closeGuardCls.getDeclaredField("stackAndTrackingEnabled");
> ```

感谢反馈和建议，我们尽快排期修复。

**Comment by weikano** [comment]
反射public方法比较好吧，两个属性都是private的
