### ISSUE TITLE
xcode15 模拟器iphone15运行demo报错，xcode14运行的时候没报错。

### ISSUE THREAD

**Issue by zziazm** [Tencent/matrix#871]
![WeChat80c10019768ccb6ecad6aee756931270](https://github.com/Tencent/matrix/assets/9669530/41604e56-1754-47ee-98b2-b04565f7aba4)

使用的是xcode15.0

**Comment by alfredking** [comment]
怎么解决的

**Comment by Maochengfag** [comment]
缺少一些libarclite_iphoneos.a文件
