### ISSUE TITLE
NORMAL慢方法所在的类名以及方法名在哪看呐，没统计么？

### ISSUE THREAD

**Issue by wcglws** [Tencent/matrix#89]
大神，如题

**Comment by wcglws** [comment]
只打印了除了方法名和类名之外的默认格式的数据tag,cost,stack,stackkey等，并没有方法名和类名

**Comment by cylee0909** [comment]
stack解析后会有详细的堆栈信息

> 只打印了除了方法名和类名之外的默认格式的数据tag,cost,stack,stackkey等，并没有方法名和类名

stack解析后会有详细的堆栈信息参考：https://github.com/Tencent/matrix/issues/104
