### ISSUE TITLE
matrix-io-canary和matrix-sqlite-lint-android-sdk 远程连接被终止

### ISSUE THREAD

**Issue by Isaac317o** [Tencent/matrix#90]
异常类型：app 编译异常

手机型号：

手机系统版本：

matrix版本： 0.4.10

gradle版本： 3.0.0

问题描述：gradle加载"matrix-io-canary"和"matrix-sqlite-lint-android-sdk"时出现远程连接终止，其他子库加载无异常

Error:
Could not determine artifacts for com.tencent.matrix:matrix-io-canary:0.4.10
Could not get resource 'https://jcenter.bintray.com/com/tencent/matrix/matrix-io-canary/0.4.10/matrix-io-canary-0.4.10.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/tencent/matrix/matrix-io-canary/0.4.10/matrix-io-canary-0.4.10.aar'.
Remote host closed connection during handshake
SSL peer shut down incorrectly

**Comment by txfelixzhou** [comment]
直接点击上面url,看是否可下载

**Comment by Isaac317o** [comment]
> 直接点击上面url,看是否可下载

今天都可以下载了，之前点击url浏览器会显示超时。之前是别的库都可以下，但是那两个库有问题
