### ISSUE TITLE
ResourceCanary 的两个疑问

### ISSUE THREAD

**Issue by hfutgl** [Tencent/matrix#92]
1、"我们可以通过创建一个持有已销毁的Activity的WeakReference，然后主动触发一次GC，如果这个Activity能被回收，则持有它的WeakReference会被置空，且这个被回收的Activity一段时间后会被加入事先注册到WeakReference的一个队列里。这样我们就能间接知道某个被销毁的Activity能否被回收了。"

 final WeakReference<Object> sentinelRef = new WeakReference<>(new Object());
 triggerGc();
看源码并没有创建已销毁Activity的弱引用，只是随便创建一个弱引用，用来判断gc有没有执行

2、ResourceCanary能都像ApkChecker一样，可以去监控任何一个app的内存问题，比如应用A集成了ResourceCanary，能否监控到应用B 应用C的泄露问题，从源码看只是传递了一个Application给ResourceCanry

**Comment by tomystang** [comment]
> 看源码并没有创建已销毁Activity的弱引用，只是随便创建一个弱引用，用来判断gc有没有执行

这个可以看下[DestroyedActivityInfo](https://github.com/Tencent/matrix/blob/master/matrix/matrix-android/matrix-resource-canary/matrix-resource-canary-android/src/main/java/com/tencent/matrix/resource/analyzer/model/DestroyedActivityInfo.java)这个类的源码，在构造函数里创建了对Activity的弱引用。

<br/>
<br/>

> ResourceCanary能都像ApkChecker一样，可以去监控任何一个app的内存问题，比如应用A集成了ResourceCanary，能否监控到应用B 应用C的泄露问题

“可以监控任何一个app的内存问题”指的肯定不是在App1里集成ResourceCanary去监控App2，App3...的问题哇，这句话的意思是说ResourceCanary可以集成到其他App里来分析这些App的内存问题，原文表述上可能不够清晰。

**Comment by hfutgl** [comment]
@tomystang  我最初的需求是“在App1里监控app2或者app3...的问题”，但是这种就算能做出来，也得在关闭selinux环境，我现在方案了，在编译转测apk的时候注入resourcecannary.aar；多谢
