### ISSUE TITLE
Multiple dex files define Lcom/tencent/tinker/ziputils/ziputil/Arrays;

### ISSUE THREAD

**Issue by 736870598** [Tencent/matrix#93]
```
异常类型：编译异常

手机型号：

手机系统版本：编译异常

matrix版本：如: 0.4.7

gradle版本：如: 3.0.1

问题描述：项目集成了buggly和matrix，无法正常通过编辑，报错。

堆栈/日志：
Multiple dex files define Lcom/tencent/tinker/ziputils/ziputil/Arrays;

**Comment by Pinick** [comment]
我也出现这个问题,和Tinker冲突具体冲突包com.tencent.tinker:tinker-ziputils这个

**Comment by Pinick** [comment]
冲突解决方法    compile (group: "com.tencent.matrix", name: "matrix-resource-canary-android", version: MATRIX_VERSION, changing: true){
        exclude group: 'com.tencent.tinker'
    }

**Comment by 736870598** [comment]
> 
> 
> 冲突解决方法 compile (group: "com.tencent.matrix", name: "matrix-resource-canary-android", version: MATRIX_VERSION, changing: true){
> exclude group: 'com.tencent.tinker'
> }

这是个办法，但是如果项目中真的需要使用tinker呢？
