### ISSUE TITLE
IO监控能监控到C层的IO吗？

### ISSUE THREAD

**Issue by zaki-kous** [Tencent/matrix#96]
IO监控能监控到C层的IO吗

**Comment by hfutgl** [comment]
@lolobug  我记得你们有本书上介绍 xposed hook java层  inline hook hook native层 

另外一个问题，IO监控能监控到所有进程的open write read操作么？还是只监控本进程

**Comment by zaki-kous** [comment]
C层的IO，需要hook哪个动态库，具体的函数是哪个。有研究过吗，或者有没有什么资料参考？

**Comment by hfutgl** [comment]
试了下 这个IO hook只能hook 自己进程的操作

**Comment by svenjung** [comment]
能監測C層的崩潰嗎？

**Comment by hfutgl** [comment]
@svenjung 这个是IO监控  只是hook io的读写创建等操作 崩溃应该不行
